-- Generated provider voice assignments. Do not hand-edit; regenerate from config/audio-voice-locks.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
START TRANSACTION;
UPDATE languages SET standalone_audio_voice_name='Hope - upbeat and clear', standalone_audio_voice_id='tnSpp4vdxKPjI9w0GnoV' WHERE code='de';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-iris' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'KXxZd16DiBqt82nbarJx';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Lucy Fennek -  Friendly and Open', c.elevenlabs_voice_id='KXxZd16DiBqt82nbarJx', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Lucy Fennek -  Friendly and Open','$.elevenLabsVoiceId','KXxZd16DiBqt82nbarJx') WHERE l.code='de' AND c.character_key='char-de-iris';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-jonas' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'MJ0RnG71ty4LH3dvNfSd';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Leon - Soothing and Grounded', c.elevenlabs_voice_id='MJ0RnG71ty4LH3dvNfSd', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Leon - Soothing and Grounded','$.elevenLabsVoiceId','MJ0RnG71ty4LH3dvNfSd') WHERE l.code='de' AND c.character_key='char-de-jonas';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-lena' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'yatuMX0k4Dh41R64sbGj';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Cécile – Interactive Customer Support', c.elevenlabs_voice_id='yatuMX0k4Dh41R64sbGj', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Cécile – Interactive Customer Support','$.elevenLabsVoiceId','yatuMX0k4Dh41R64sbGj') WHERE l.code='de' AND c.character_key='char-de-lena';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-max' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'uUnmYv9aJqaqzs1wcFRH';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Chris - Supportive and Cool', c.elevenlabs_voice_id='uUnmYv9aJqaqzs1wcFRH', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Chris - Supportive and Cool','$.elevenLabsVoiceId','uUnmYv9aJqaqzs1wcFRH') WHERE l.code='de' AND c.character_key='char-de-max';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-mia' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'NE7AIW5DoJ7lUosXV2KR';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Ela - Urban and Playful v.2', c.elevenlabs_voice_id='NE7AIW5DoJ7lUosXV2KR', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Ela - Urban and Playful v.2','$.elevenLabsVoiceId','NE7AIW5DoJ7lUosXV2KR') WHERE l.code='de' AND c.character_key='char-de-mia';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-paul' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'70DeQK5Ztp7WmEGGysLT';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Hyun - Friendly and Natural', c.elevenlabs_voice_id='70DeQK5Ztp7WmEGGysLT', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Hyun - Friendly and Natural','$.elevenLabsVoiceId','70DeQK5Ztp7WmEGGysLT') WHERE l.code='de' AND c.character_key='char-de-paul';
COMMIT;
