-- Generated provider voice assignments. Do not hand-edit; regenerate from config/audio-voice-locks.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
START TRANSACTION;
UPDATE languages SET standalone_audio_voice_name='Hope - upbeat and clear', standalone_audio_voice_id='tnSpp4vdxKPjI9w0GnoV' WHERE code='de';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-iris' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'GZHDPDohOOwIocbPemTq';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Chelsea Boddie', c.elevenlabs_voice_id='GZHDPDohOOwIocbPemTq', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Chelsea Boddie','$.elevenLabsVoiceId','GZHDPDohOOwIocbPemTq') WHERE l.code='de' AND c.character_key='char-de-iris';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-jonas' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'s3TPKV1kjDlVtZbl4Ksh';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Adam - Authentic & Engaging Conversationalist', c.elevenlabs_voice_id='s3TPKV1kjDlVtZbl4Ksh', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Adam - Authentic & Engaging Conversationalist','$.elevenLabsVoiceId','s3TPKV1kjDlVtZbl4Ksh') WHERE l.code='de' AND c.character_key='char-de-jonas';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-lena' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'yatuMX0k4Dh41R64sbGj';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Cécile – Interactive Customer Support', c.elevenlabs_voice_id='yatuMX0k4Dh41R64sbGj', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Cécile – Interactive Customer Support','$.elevenLabsVoiceId','yatuMX0k4Dh41R64sbGj') WHERE l.code='de' AND c.character_key='char-de-lena';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-max' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'uUnmYv9aJqaqzs1wcFRH';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Chris - Supportive and Cool', c.elevenlabs_voice_id='uUnmYv9aJqaqzs1wcFRH', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Chris - Supportive and Cool','$.elevenLabsVoiceId','uUnmYv9aJqaqzs1wcFRH') WHERE l.code='de' AND c.character_key='char-de-max';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-mia' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'gJx1vCzNCD1EQHT212Ls';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Ava – Natural AI Voice', c.elevenlabs_voice_id='gJx1vCzNCD1EQHT212Ls', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Ava – Natural AI Voice','$.elevenLabsVoiceId','gJx1vCzNCD1EQHT212Ls') WHERE l.code='de' AND c.character_key='char-de-mia';
UPDATE dialogue_turns t JOIN characters c ON c.id=t.speaker_character_id JOIN languages l ON l.id=c.language_id SET t.audio_status='stale' WHERE l.code='de' AND c.character_key='char-de-paul' AND t.audio_status='ready' AND t.audio_voice_id IS NOT NULL AND t.audio_voice_id<>'70DeQK5Ztp7WmEGGysLT';
UPDATE characters c JOIN languages l ON l.id=c.language_id SET c.voice_name='Hyun - Friendly and Natural', c.elevenlabs_voice_id='70DeQK5Ztp7WmEGGysLT', c.voice_profile=JSON_SET(COALESCE(c.voice_profile,JSON_OBJECT()),'$.voiceName','Hyun - Friendly and Natural','$.elevenLabsVoiceId','70DeQK5Ztp7WmEGGysLT') WHERE l.code='de' AND c.character_key='char-de-paul';
COMMIT;
