-- German A1: close Unit 3 for review, open Unit 4 and build the first daily-routine lesson.
-- Base content never overwrites generated audio state.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);
SET @unit3 := (SELECT id FROM units WHERE unit_key='de-a1-unit-home-and-nearby' LIMIT 1);
UPDATE units SET status='review',notes='بازبینی پوشش انجام شد. دو درس موجود وسایل پایهٔ اتاق، مالکیت ساده، موقعیت راست و چپ و جلو و عقب و یک ویژگی سادهٔ خانه را پوشش می‌دهند. برای هدف فعلی این واحد شکاف ضروری مستقلی برای درس سوم پیدا نشد؛ توصیف گسترده‌تر مکان بعداً در واحد مسیر و مکان‌های عمومی ادامه پیدا می‌کند.' WHERE id=@unit3 AND status <> 'final';
INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES('src-wikibooks-de-lesson-022-daily-routine','Deutschkurs für Anfänger/Lektion 022','روتین روزانه: صبح، کار و بخش‌های روز','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_022','Item 936: questions and answers about morning, late morning, midday and afternoon routines, including work, school, meals and going home.','بخش ۹۳۶؛ پرسش و پاسخ دربارهٔ کارهای صبح، پیش از ظهر، ظهر و بعدازظهر، از جمله کار، مدرسه، غذا و برگشتن به خانه.','2026-08-16','maintained_current','صفحهٔ زندهٔ ویکی‌بوکس در ۱۷ سپتامبر ۲۰۲۶ بررسی شد و آخرین ویرایش ثبت‌شدهٔ آن ۱۶ اوت ۲۰۲۶ است. بخش انتخاب‌شده پرسش و پاسخ‌های کوتاه و امروزی دربارهٔ بخش‌های روز، کار، مدرسه و کارهای روزمره دارد.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 022','reuse_with_attribution','2026-09-17','منبع آغاز واحد روتین روزانه است. در گام نخست فقط پرسش و پاسخ‌های روشن بخش ۹۳۶ دربارهٔ صبح و پیش از ظهر و چند جملهٔ مقایسه‌ای از همان بخش استفاده می‌شوند. متن‌های پیچیده‌تر صفحه برای مراحل بعدی جداگانه ارزیابی خواهند شد.') ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-022-daily-routine' LIMIT 1);
INSERT INTO units(unit_key,language_level_id,sequence_index,title_fa,grouping_rationale,status,metadata,notes) VALUES('de-a1-unit-daily-routine-work-school',@level,4,'روتین روزانه: کار و مدرسه','پس از معرفی شخص، خانواده و محیط نزدیک، گام بعدی پیوند دادن زمان روز با کارهای معمول است. این واحد ابتدا با پرسش‌های کوتاه دربارهٔ صبح و پیش از ظهر شروع می‌شود و سپس در درس‌های بعدی مدرسه، بعدازظهر و برنامهٔ روزانه را گسترش می‌دهد.','draft',JSON_OBJECT('sourceRefs',JSON_ARRAY('src-wikibooks-de-lesson-022-daily-routine'),'learningTargets',JSON_ARRAY('فهم پرسش و پاسخ کوتاه دربارهٔ کارهای معمول در بخش‌های مختلف روز','اتصال صبح، پیش از ظهر، ظهر و بعدازظهر به کارهای روزمره','فهم اطلاعات ساده دربارهٔ کار یا مدرسه در بافت روتین','دنبال کردن چند کار روزمره در توالی زمانی ساده')),'درس نخست صبح و پیش از ظهر و یک الگوی سادهٔ کار روزانه را پوشش می‌دهد. مرحلهٔ بعد باید مدرسه و بخش‌های دیگر روز را با جمله‌های منبع‌دار گسترش دهد، نه با جمله‌سازی آزاد.') ON DUPLICATE KEY UPDATE sequence_index=VALUES(sequence_index),title_fa=VALUES(title_fa),grouping_rationale=VALUES(grouping_rationale),status=IF(status IN ('review','final'),status,VALUES(status)),metadata=VALUES(metadata),notes=VALUES(notes);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-daily-routine-work-school' LIMIT 1);
SET @iris := (SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1);
SET @paul := (SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1);
SET @t_routine := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-work-school-routine' LIMIT 1);
SET @t_routine_sit := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-sit-work-school' LIMIT 1);
SET @t_core := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-core-vocabulary' LIMIT 1);
SET @t_questions := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-questions' LIMIT 1);
SET @t_present := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-present-verbs' LIMIT 1);
INSERT IGNORE INTO unit_targets(unit_id,curriculum_target_id) VALUES(@unit,@t_routine),(@unit,@t_routine_sit),(@unit,@t_core),(@unit,@t_questions),(@unit,@t_present);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-routine-morning-q','936','بخش ۹۳۶','Was machen Sie morgens?',UNHEX(SHA2('Was machen Sie morgens?',256)),'پرسش دربارهٔ کار صبح.'),
(@src,'srcitem-de-a1-routine-morning-coffee','936','پاسخ ۹۳۶','Morgens trinke ich Kaffee.',UNHEX(SHA2('Morgens trinke ich Kaffee.',256)),'پاسخ دربارهٔ صبح.'),
(@src,'srcitem-de-a1-routine-late-morning-q','936','بخش ۹۳۶','Was machen Sie vormittags?',UNHEX(SHA2('Was machen Sie vormittags?',256)),'پرسش دربارهٔ پیش از ظهر.'),
(@src,'srcitem-de-a1-routine-late-morning-work','936','پاسخ ۹۳۶','Vormittags arbeite ich im Betrieb.',UNHEX(SHA2('Vormittags arbeite ich im Betrieb.',256)),'پاسخ دربارهٔ کار پیش از ظهر.'),
(@src,'srcitem-de-a1-routine-morning-tea','936','پاسخ ۹۳۶','Morgens trinke ich Tee.',UNHEX(SHA2('Morgens trinke ich Tee.',256)),'نمونهٔ دیگر صبح.'),
(@src,'srcitem-de-a1-routine-midday-restaurant','936','پاسخ ۹۳۶','Mittags esse ich in einem Restaurant.',UNHEX(SHA2('Mittags esse ich in einem Restaurant.',256)),'نمونهٔ ظهر.'),
(@src,'srcitem-de-a1-routine-afternoon-home','936','پاسخ ۹۳۶','Nachmittags gehe ich nach Hause.',UNHEX(SHA2('Nachmittags gehe ich nach Hause.',256)),'نمونهٔ بعدازظهر.'),
(@src,'srcitem-de-a1-word-morgens','936','بخش ۹۳۶','morgens',UNHEX(SHA2('morgens',256)),'قید زمان روز.'),
(@src,'srcitem-de-a1-word-vormittags','936','بخش ۹۳۶','vormittags',UNHEX(SHA2('vormittags',256)),'قید زمان روز.'),
(@src,'srcitem-de-a1-word-mittags','936','بخش ۹۳۶','mittags',UNHEX(SHA2('mittags',256)),'قید زمان روز.'),
(@src,'srcitem-de-a1-word-nachmittags','936','بخش ۹۳۶','nachmittags',UNHEX(SHA2('nachmittags',256)),'قید زمان روز.'),
(@src,'srcitem-de-a1-word-betrieb','936','پاسخ ۹۳۶','Betrieb',UNHEX(SHA2('Betrieb',256)),'واژهٔ محل کار.'),
(@src,'srcitem-de-a1-word-trinken','936','بخش ۹۳۶','trinken',UNHEX(SHA2('trinken',256)),'فعل نوشیدن.'),
(@src,'srcitem-de-a1-word-machen','936','بخش ۹۳۶','machen',UNHEX(SHA2('machen',256)),'فعل پرسش روتین.') ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
INSERT INTO lexemes(lexeme_key,language_id,lexeme_type,surface,normalized_surface,lemma,part_of_speech,part_of_speech_fa,cefr_level,translation_fa,usage_note_fa,flashcard_eligible,audio_status) VALUES
('lex-de-morgens',@de,'word','morgens','morgens','morgens','adverb','قید','A1','صبح‌ها / صبح','برای گفتن زمانی از روز که یک کار معمولاً صبح انجام می‌شود استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-vormittags',@de,'word','vormittags','vormittags','vormittags','adverb','قید','A1','پیش از ظهرها / پیش از ظهر','برای بیان کارهایی که در بخش پیش از ظهر انجام می‌شوند استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-mittags',@de,'word','mittags','mittags','mittags','adverb','قید','A1','ظهرها / ظهر','برای بیان کارهایی که حوالی ظهر انجام می‌شوند استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-nachmittags',@de,'word','nachmittags','nachmittags','nachmittags','adverb','قید','A1','بعدازظهرها / بعدازظهر','برای بیان کارهایی که در بعدازظهر انجام می‌شوند استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-betrieb',@de,'word','Betrieb','Betrieb','Betrieb','noun','اسم','A1','محل کار / شرکت','در این سطح برای اشارهٔ ساده به محل کار در جملهٔ روزمره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-trinken',@de,'word','trinken','trinken','trinken','verb','فعل','A1','نوشیدن','برای گفتن نوشیدنی‌ای که فرد در یک موقعیت روزمره می‌نوشد استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-machen',@de,'word','machen','machen','machen','verb','فعل','A1','انجام دادن / کردن','در پرسش ساده دربارهٔ کاری که فرد در بخشی از روز انجام می‌دهد استفاده می‌شود.',TRUE,'blocked_until_level_final') ON DUPLICATE KEY UPDATE language_id=VALUES(language_id),lexeme_type=VALUES(lexeme_type),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),lemma=VALUES(lemma),part_of_speech=VALUES(part_of_speech),part_of_speech_fa=VALUES(part_of_speech_fa),cefr_level=VALUES(cefr_level),translation_fa=VALUES(translation_fa),usage_note_fa=VALUES(usage_note_fa),flashcard_eligible=VALUES(flashcard_eligible);
SET @x_morgens := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-morgens'); SET @x_vormittags := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-vormittags'); SET @x_mittags := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-mittags'); SET @x_nachmittags := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-nachmittags'); SET @x_betrieb := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-betrieb'); SET @x_trinken := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-trinken'); SET @x_machen := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-machen'); SET @x_arbeiten := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-arbeiten'); SET @x_kaffee := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-kaffee'); SET @x_essen := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-essen');
INSERT INTO lexeme_forms(lexeme_form_key,lexeme_id,surface,normalized_surface,form_type,features,origin,review_status,notes) VALUES('lexform-de-trinken-trinke',@x_trinken,'trinke','trinke','inflected',JSON_OBJECT('tense','present','mood','indicative','person','1','number','singular'),'source_attested','approved','در پاسخ منبع‌دار مربوط به صبح، فعل نوشیدن به‌صورت اول‌شخص مفرد زمان حال آمده است.') ON DUPLICATE KEY UPDATE lexeme_id=VALUES(lexeme_id),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),form_type=VALUES(form_type),features=VALUES(features),origin=VALUES(origin),review_status=VALUES(review_status),notes=VALUES(notes);
SET @f_trinke := (SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-trinken-trinke'); SET @f_arbeite := (SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-arbeiten-arbeite');
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES('de-a1-lesson-daily-routine-work',@level,@unit,7,1,'صبح‌ها چه کار می‌کنی؟','Was machen Sie morgens? / Was machen Sie vormittags?','صبح‌ها چه کار می‌کنید؟ / پیش از ظهرها چه کار می‌کنید؟','draft','گفت‌وگو دو بخش نخست روز را در بافت وارد می‌کند؛ سپس چهار جملهٔ منبع‌دار به زمان مناسب وصل می‌شوند، جملهٔ مربوط به کار تشخیص داده می‌شود و در پایان پاسخ صبح بازسازی می‌شود.','درس از تعامل و فهم زمان روز به دسته‌بندی، تمایز معنایی و بازیابی فعال یک پاسخ کوتاه حرکت می‌کند و الگوی فعالیت آن با درس قبلی متفاوت است.','conversation_speaking>matching>multiple_choice>word_order','blocked_until_level_final','درس نخست واحد روتین روزانه؛ متن آلمانی زبان‌آموز فقط از بخش ۹۳۶ منبع ثبت‌شده می‌آید.') ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),source_title=VALUES(source_title),source_title_fa=VALUES(source_title_fa),status=VALUES(status),activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-daily-routine-work');
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role) VALUES(@lesson,@t_routine,'introduce'),(@lesson,@t_routine_sit,'introduce'),(@lesson,@t_core,'introduce'),(@lesson,@t_questions,'practice'),(@lesson,@t_present,'practice');
INSERT IGNORE INTO lesson_lexemes(lesson_id,lexeme_id,is_primary,role) VALUES(@lesson,@x_morgens,TRUE,'introduce'),(@lesson,@x_vormittags,TRUE,'introduce'),(@lesson,@x_mittags,TRUE,'introduce'),(@lesson,@x_nachmittags,TRUE,'introduce'),(@lesson,@x_betrieb,TRUE,'introduce'),(@lesson,@x_trinken,TRUE,'introduce'),(@lesson,@x_machen,TRUE,'introduce'),(@lesson,@x_arbeiten,FALSE,'review'),(@lesson,@x_kaffee,FALSE,'review'),(@lesson,@x_essen,FALSE,'review');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES('dlg-de-a1-daily-routine-work',@level,'آیریس از پاول دربارهٔ کارهای معمول صبح و پیش از ظهر می‌پرسد و پاول با دو پاسخ کوتاه دربارهٔ قهوه و کار جواب می‌دهد.','app','دو جفت پرسش و پاسخ بخش ۹۳۶ بدون بازنویسی کنار هم قرار گرفته‌اند و یک گفت‌وگوی طبیعی دربارهٔ دو بخش پیاپی روز می‌سازند.') ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dialogue := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-daily-routine-work');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-daily-routine-work-1',@dialogue,1,@iris,'app_assigned','unspecified','Was machen Sie morgens?','صبح‌ها چه کار می‌کنید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-daily-routine-work-2',@dialogue,2,@paul,'app_assigned','unspecified','Morgens trinke ich Kaffee.','صبح‌ها قهوه می‌نوشم.',TRUE,'blocked_until_level_final'),
('turn-de-a1-daily-routine-work-3',@dialogue,3,@iris,'app_assigned','unspecified','Was machen Sie vormittags?','پیش از ظهرها چه کار می‌کنید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-daily-routine-work-4',@dialogue,4,@paul,'app_assigned','unspecified','Vormittags arbeite ich im Betrieb.','پیش از ظهرها در محل کار کار می‌کنم.',TRUE,'blocked_until_level_final') ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-daily-routine-conversation',@lesson,1,'conversation_speaking','به آیریس بگو صبح و پیش از ظهر معمولاً چه کار می‌کنی.','دو جفت پرسش و پاسخ منبع‌دار، روتین صبح و کار پیش از ظهر را بدون توضیح دستوری سنگین وارد می‌کنند.',@dialogue,JSON_OBJECT('interaction','read_aloud_exchange','openingInitiator','app'),JSON_ARRAY('verbatim_dialogue','persian_translation_added','character_metadata_added'),NULL,'not_required'),
('act-de-a1-dayparts-matching',@lesson,2,'matching','هر جمله را به بخش درست روز وصل کن.','چهار پاسخ کامل از همان بخش منبع، ترتیب زمانی صبح تا بعدازظهر را با کارهای واقعی روزمره پیوند می‌دهند.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','Morgens trinke ich Kaffee.','leftFa','صبح‌ها قهوه می‌نوشم.','right','صبح','rightFa','صبح'),JSON_OBJECT('left','Vormittags arbeite ich im Betrieb.','leftFa','پیش از ظهرها در محل کار کار می‌کنم.','right','پیش از ظهر','rightFa','پیش از ظهر'),JSON_OBJECT('left','Mittags esse ich in einem Restaurant.','leftFa','ظهرها در یک رستوران غذا می‌خورم.','right','ظهر','rightFa','ظهر'),JSON_OBJECT('left','Nachmittags gehe ich nach Hause.','leftFa','بعدازظهرها به خانه می‌روم.','right','بعدازظهر','rightFa','بعدازظهر'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-routine-work-choice',@lesson,3,'multiple_choice','کدام جمله دربارهٔ کار کردن پیش از ظهر است؟','سه پاسخ کامل و منبع‌دار از همان تمرین، کار را از نوشیدن و غذا خوردن جدا می‌کنند.',NULL,JSON_OBJECT('options',JSON_ARRAY(JSON_OBJECT('textTarget','Vormittags arbeite ich im Betrieb.','translationFa','پیش از ظهرها در محل کار کار می‌کنم.','correct',TRUE),JSON_OBJECT('textTarget','Morgens trinke ich Tee.','translationFa','صبح‌ها چای می‌نوشم.','correct',FALSE),JSON_OBJECT('textTarget','Mittags esse ich in einem Restaurant.','translationFa','ظهرها در یک رستوران غذا می‌خورم.','correct',FALSE))),JSON_ARRAY('options_selected_from_source_material','persian_translation_added'),NULL,'not_required'),
('act-de-a1-morning-answer-order',@lesson,4,'word_order','پاسخ مربوط به صبح را دوباره بساز.','پاسخ آغاز گفت‌وگو پس از فهم و تمایز به بازیابی فعال منتقل می‌شود.',NULL,JSON_OBJECT('sourceText','Morgens trinke ich Kaffee.','sourceTextFa','صبح‌ها قهوه می‌نوشم.','tokens',JSON_ARRAY('Morgens','trinke','ich','Kaffee.'),'answer',JSON_ARRAY('Morgens','trinke','ich','Kaffee.')),JSON_ARRAY('sentence_tokenized_for_word_order','persian_translation_added'),NULL,'not_required') ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
SET @a1 := (SELECT id FROM activities WHERE activity_key='act-de-a1-daily-routine-conversation'); SET @a2 := (SELECT id FROM activities WHERE activity_key='act-de-a1-dayparts-matching'); SET @a3 := (SELECT id FROM activities WHERE activity_key='act-de-a1-routine-work-choice'); SET @a4 := (SELECT id FROM activities WHERE activity_key='act-de-a1-morning-answer-order');
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) VALUES(@a1,@t_routine),(@a1,@t_routine_sit),(@a1,@t_questions),(@a1,@t_present),(@a2,@t_routine),(@a2,@t_core),(@a3,@t_routine),(@a3,@t_present),(@a4,@t_routine),(@a4,@t_present);
INSERT IGNORE INTO activity_lexemes(activity_id,lexeme_id) VALUES(@a1,@x_machen),(@a1,@x_morgens),(@a1,@x_vormittags),(@a1,@x_trinken),(@a1,@x_kaffee),(@a1,@x_arbeiten),(@a1,@x_betrieb),(@a2,@x_morgens),(@a2,@x_vormittags),(@a2,@x_mittags),(@a2,@x_nachmittags),(@a2,@x_trinken),(@a2,@x_arbeiten),(@a2,@x_betrieb),(@a2,@x_essen),(@a3,@x_vormittags),(@a3,@x_arbeiten),(@a3,@x_betrieb),(@a3,@x_morgens),(@a3,@x_mittags),(@a4,@x_morgens),(@a4,@x_trinken),(@a4,@x_kaffee);
INSERT INTO lexeme_occurrences(occurrence_key,owner_type,owner_key,surface,start_offset,end_offset,lexeme_id,lexeme_form_id,resolution_status,resolution_notes) VALUES
('occ-turn-de-a1-routine-1-machen','dialogue_turn','turn-de-a1-daily-routine-work-1','machen',NULL,NULL,@x_machen,NULL,'approved','اتصال فعل پرسش تأیید شده است.'),
('occ-turn-de-a1-routine-1-morgens','dialogue_turn','turn-de-a1-daily-routine-work-1','morgens',NULL,NULL,@x_morgens,NULL,'approved','اتصال قید زمان تأیید شده است.'),
('occ-turn-de-a1-routine-2-morgens','dialogue_turn','turn-de-a1-daily-routine-work-2','Morgens',NULL,NULL,@x_morgens,NULL,'approved','اتصال قید زمان تأیید شده است.'),
('occ-turn-de-a1-routine-2-trinke','dialogue_turn','turn-de-a1-daily-routine-work-2','trinke',NULL,NULL,@x_trinken,@f_trinke,'approved','صورت صرفی به فعل نوشیدن متصل است.'),
('occ-turn-de-a1-routine-2-kaffee','dialogue_turn','turn-de-a1-daily-routine-work-2','Kaffee',NULL,NULL,@x_kaffee,NULL,'approved','اتصال واژهٔ قهوه تأیید شده است.'),
('occ-turn-de-a1-routine-3-machen','dialogue_turn','turn-de-a1-daily-routine-work-3','machen',NULL,NULL,@x_machen,NULL,'approved','اتصال فعل پرسش تأیید شده است.'),
('occ-turn-de-a1-routine-3-vormittags','dialogue_turn','turn-de-a1-daily-routine-work-3','vormittags',NULL,NULL,@x_vormittags,NULL,'approved','اتصال قید زمان تأیید شده است.'),
('occ-turn-de-a1-routine-4-vormittags','dialogue_turn','turn-de-a1-daily-routine-work-4','Vormittags',NULL,NULL,@x_vormittags,NULL,'approved','اتصال قید زمان تأیید شده است.'),
('occ-turn-de-a1-routine-4-arbeite','dialogue_turn','turn-de-a1-daily-routine-work-4','arbeite',NULL,NULL,@x_arbeiten,@f_arbeite,'approved','صورت صرفی به فعل کار کردن متصل است.'),
('occ-turn-de-a1-routine-4-betrieb','dialogue_turn','turn-de-a1-daily-routine-work-4','Betrieb',NULL,NULL,@x_betrieb,NULL,'approved','اتصال واژهٔ محل کار تأیید شده است.') ON DUPLICATE KEY UPDATE owner_type=VALUES(owner_type),owner_key=VALUES(owner_key),surface=VALUES(surface),lexeme_id=VALUES(lexeme_id),lexeme_form_id=VALUES(lexeme_form_id),resolution_status=VALUES(resolution_status),resolution_notes=VALUES(resolution_notes);
SET @si_q1 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-morning-q'); SET @si_a1 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-morning-coffee'); SET @si_q2 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-late-morning-q'); SET @si_a2 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-late-morning-work'); SET @si_tea := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-morning-tea'); SET @si_mid := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-midday-restaurant'); SET @si_aft := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-routine-afternoon-home'); SET @si_morgens := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-morgens'); SET @si_vormittags := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-vormittags'); SET @si_mittags := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-mittags'); SET @si_nachmittags := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-nachmittags'); SET @si_betrieb := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-betrieb'); SET @si_trinken := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-trinken'); SET @si_machen := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-word-machen');
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES
('dialogue_turn','turn-de-a1-daily-routine-work-1',@si_q1,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-daily-routine-work-2',@si_a1,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-daily-routine-work-3',@si_q2,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-daily-routine-work-4',@si_a2,'verbatim','متن هدف عین منبع است.'),('lexeme','lex-de-morgens',@si_morgens,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme','lex-de-vormittags',@si_vormittags,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme','lex-de-mittags',@si_mittags,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme','lex-de-nachmittags',@si_nachmittags,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme','lex-de-betrieb',@si_betrieb,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme','lex-de-trinken',@si_trinken,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme','lex-de-machen',@si_machen,'verbatim','صورت واژه در منبع ثبت شده است.'),('lexeme_form','lexform-de-trinken-trinke',@si_a1,'other','صورت صرفی از جملهٔ منبع‌دار استخراج شده است.'),('activity','act-de-a1-dayparts-matching',@si_a1,'source_items_grouped_for_matching','جملهٔ صبح عین منبع است.'),('activity','act-de-a1-dayparts-matching',@si_a2,'source_items_grouped_for_matching','جملهٔ پیش از ظهر عین منبع است.'),('activity','act-de-a1-dayparts-matching',@si_mid,'source_items_grouped_for_matching','جملهٔ ظهر عین منبع است.'),('activity','act-de-a1-dayparts-matching',@si_aft,'source_items_grouped_for_matching','جملهٔ بعدازظهر عین منبع است.'),('activity','act-de-a1-routine-work-choice',@si_a2,'options_selected_from_source_material','گزینهٔ درست عین منبع است.'),('activity','act-de-a1-routine-work-choice',@si_tea,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),('activity','act-de-a1-routine-work-choice',@si_mid,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),('activity','act-de-a1-morning-answer-order',@si_a1,'sentence_tokenized_for_word_order','جملهٔ عین منبع برای مرتب‌سازی بخش‌بندی شده است.');
UPDATE language_levels SET coverage=JSON_SET(coverage,'$.gaps[2]','سه واحد نخست به بازبینی رسیده‌اند؛ واحد چهارم روتین روزانه با نخستین درس منبع‌دار آغاز شده و باید مدرسه و بخش‌های دیگر روز را در ادامه پوشش دهد.'),notes='A1 همچنان در مرحلهٔ ساخت تدریجی است. سه واحد نخست در بازبینی‌اند. واحد چهارم روتین روزانه با درس صبح و پیش از ظهر آغاز شده و مرحلهٔ بعد باید مدرسه و بخش‌های دیگر روز را با منبع قابل‌بازاستفاده پوشش دهد.' WHERE id=@level;
COMMIT;
