-- German A1 Unit 5 — quantity, price and payment in one coherent shopping transaction.
-- Base content never overwrites generated audio state.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);
SET @iris := (SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1);
SET @lena := (SELECT id FROM characters WHERE character_key='char-de-lena' LIMIT 1);
INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-009-shopping','Deutschkurs für Anfänger/Lektion 009','خرید واقعی‌تر: قیمت، مقدار و پرداخت','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_009','Items 399 and 410: coherent supermarket transaction with price, weight, additional goods, cash desk and payment, plus quantity-price practice.','بخش‌های ۳۹۹ و ۴۱۰؛ گفت‌وگوی خرید با قیمت، گرم و کیلو، کالای اضافه، صندوق و پرداخت و تمرین مقدار و قیمت.','2021-04-02','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۷ سپتامبر ۲۰۲۶ بررسی شد. آخرین ویرایش ثبت‌شدهٔ صفحه ۲ آوریل ۲۰۲۱ است؛ عبارت‌های انتخاب‌شده دربارهٔ قیمت، وزن، درخواست کالا، صندوق و پرداخت در بازبینی فعلی همچنان آلمانی معیار و طبیعی‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 009','reuse_with_attribution','2026-09-17','استفاده به بخش‌های ۳۹۹ و ۴۱۰ محدود است. گفت‌وگوی ۳۹۹ تراکنش پیوستهٔ خرید را پوشش می‌دهد و تمرین ۴۱۰ دامنهٔ مقدار و قیمت را گسترش می‌دهد. فاصلهٔ چاپی پیش از نقطه در یکی از جمله‌ها فقط به نشانه‌گذاری استاندارد تبدیل می‌شود و واژگان آلمانی تغییر نمی‌کنند.') ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-009-shopping' LIMIT 1);
INSERT INTO units(unit_key,language_level_id,sequence_index,title_fa,grouping_rationale,status,metadata,notes) VALUES('de-a1-unit-shopping-quantity-payment',@level,5,'خرید واقعی‌تر: مقدار، قیمت و پرداخت','سطح پیشین فقط نیاز و خرید بسیار ساده را معرفی کرده بود. این واحد همان موقعیت را به یک تراکنش واقعی‌تر گسترش می‌دهد: قیمت، مقدار، افزودن کالا، پایان سفارش و پرداخت. گفت‌وگوی اصلی همهٔ این اجزا را پیوسته پوشش می‌دهد و تمرین مقدار و قیمت دامنهٔ کالاها را بدون ساخت جملهٔ آزاد گسترش می‌دهد.','review',JSON_OBJECT('sourceRefs',JSON_ARRAY('src-wikibooks-de-lesson-009-shopping'),'learningTargets',JSON_ARRAY('پرسیدن و فهم قیمت کالا','فهم گرم و کیلو در مقدار خرید','افزودن کالا و تعیین مقدار','فهم پرداخت در صندوق')),'بازبینی پوشش انجام شد. گفت‌وگوی هشت‌نوبتی بخش ۳۹۹ قیمت، گرم و کیلو، افزودن کالا، مقدار دوم و پرداخت در صندوق را پوشش می‌دهد و تمرین ۴۱۰ چند کالا و قیمت دیگر را اضافه می‌کند. برای هدف فعلی خرید A1 شکاف ضروری مستقلی برای درس دوم پیدا نشد.') ON DUPLICATE KEY UPDATE sequence_index=VALUES(sequence_index),title_fa=VALUES(title_fa),grouping_rationale=VALUES(grouping_rationale),status=IF(status='final',status,VALUES(status)),metadata=VALUES(metadata),notes=VALUES(notes);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-shopping-quantity-payment' LIMIT 1);
SET @t_shop := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-shopping' LIMIT 1);
SET @t_shop_sit := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-sit-shopping' LIMIT 1);
SET @t_core := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-core-vocabulary' LIMIT 1);
SET @t_numbers := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-numbers-dates-time' LIMIT 1);
SET @t_present := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-present-verbs' LIMIT 1);
INSERT IGNORE INTO unit_targets(unit_id,curriculum_target_id) VALUES(@unit,@t_shop),(@unit,@t_shop_sit),(@unit,@t_core),(@unit,@t_numbers),(@unit,@t_present);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-shop-1','399','بخش ۳۹۹','Wie viel kostet dieses Fleisch?',UNHEX(SHA2('Wie viel kostet dieses Fleisch?',256)),'پرسش قیمت.'),
(@src,'srcitem-de-a1-shop-2','399','بخش ۳۹۹','500 Gramm kosten 5,20 Euro.',UNHEX(SHA2('500 Gramm kosten 5,20 Euro.',256)),'پاسخ قیمت و مقدار.'),
(@src,'srcitem-de-a1-shop-3','399','بخش ۳۹۹','Bitte ein Kilo. Ich nehme auch noch Wurst.',UNHEX(SHA2('Bitte ein Kilo. Ich nehme auch noch Wurst.',256)),'درخواست مقدار و افزودن کالا.'),
(@src,'srcitem-de-a1-shop-4','399','بخش ۳۹۹','Wie viel möchten Sie?',UNHEX(SHA2('Wie viel möchten Sie?',256)),'پرسش مقدار.'),
(@src,'srcitem-de-a1-shop-5','399','بخش ۳۹۹','Bitte 250 Gramm.',UNHEX(SHA2('Bitte 250 Gramm.',256)),'پاسخ مقدار.'),
(@src,'srcitem-de-a1-shop-6','399','بخش ۳۹۹','Noch etwas?',UNHEX(SHA2('Noch etwas?',256)),'پرسش کالای دیگر.'),
(@src,'srcitem-de-a1-shop-7','399','بخش ۳۹۹','Danke, das ist alles.',UNHEX(SHA2('Danke, das ist alles.',256)),'نشانه‌گذاری استاندارد شده؛ واژگان منبع تغییر نکرده‌اند.'),
(@src,'srcitem-de-a1-shop-8','399','بخش ۳۹۹','Dort ist die Kasse. Bezahlen Sie bitte dort.',UNHEX(SHA2('Dort ist die Kasse. Bezahlen Sie bitte dort.',256)),'راهنمای صندوق و پرداخت.'),
(@src,'srcitem-de-a1-shop-410-wurst','410','بخش ۴۱۰','300 g Wurst kosten 5,99 Euro.',UNHEX(SHA2('300 g Wurst kosten 5,99 Euro.',256)),'تمرین مقدار و قیمت.'),
(@src,'srcitem-de-a1-shop-410-butter','410','بخش ۴۱۰','250 g Butter kosten 3,95 Euro.',UNHEX(SHA2('250 g Butter kosten 3,95 Euro.',256)),'تمرین مقدار و قیمت.'),
(@src,'srcitem-de-a1-shop-410-milch','410','بخش ۴۱۰','Zwei Flaschen Milch kosten 2,99 Euro.',UNHEX(SHA2('Zwei Flaschen Milch kosten 2,99 Euro.',256)),'تمرین مقدار و قیمت.'),
(@src,'srcitem-de-a1-shop-410-eier','410','بخش ۴۱۰','Fünf Eier kosten 2,67 Euro.',UNHEX(SHA2('Fünf Eier kosten 2,67 Euro.',256)),'تمرین مقدار و قیمت.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
INSERT INTO lexemes(lexeme_key,language_id,lexeme_type,surface,normalized_surface,lemma,part_of_speech,part_of_speech_fa,cefr_level,translation_fa,usage_note_fa,flashcard_eligible,audio_status) VALUES
('lex-de-fleisch',@de,'word','Fleisch','Fleisch','Fleisch','noun','اسم','A1','گوشت','در گفت‌وگوی خرید برای پرسیدن قیمت و درخواست مقدار مشخص استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-gramm',@de,'word','Gramm','Gramm','Gramm','noun','اسم','A1','گرم','برای بیان مقدار کالا در خرید استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-kilo',@de,'word','Kilo','Kilo','Kilo','noun','اسم','A1','کیلو / کیلوگرم','برای درخواست مقدار یک کیلو در خرید روزمره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-wurst',@de,'word','Wurst','Wurst','Wurst','noun','اسم','A1','سوسیس / کالباس','در گفت‌وگوی منبع به‌عنوان کالای دیگری که مشتری به خرید اضافه می‌کند استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-kosten',@de,'word','kosten','kosten','kosten','verb','فعل','A1','قیمت داشتن','برای پرسیدن و گفتن قیمت کالا استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-nehmen',@de,'word','nehmen','nehmen','nehmen','verb','فعل','A1','گرفتن / انتخاب کردن','در خرید برای گفتن اینکه مشتری کالایی را انتخاب یا اضافه می‌کند استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-kasse',@de,'word','Kasse','Kasse','Kasse','noun','اسم','A1','صندوق / صندوق پرداخت','برای اشاره به محل پرداخت در فروشگاه استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-bezahlen',@de,'word','bezahlen','bezahlen','bezahlen','verb','فعل','A1','پرداخت کردن','برای گفتن یا فهمیدن مرحلهٔ پرداخت در خرید استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-noch-etwas',@de,'phrase','noch etwas','noch etwas',NULL,NULL,NULL,'A1','چیز دیگری / چیز دیگری هم','در فروشگاه برای پرسیدن اینکه مشتری چیز دیگری هم می‌خواهد استفاده می‌شود.',TRUE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE language_id=VALUES(language_id),lexeme_type=VALUES(lexeme_type),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),lemma=VALUES(lemma),part_of_speech=VALUES(part_of_speech),part_of_speech_fa=VALUES(part_of_speech_fa),cefr_level=VALUES(cefr_level),translation_fa=VALUES(translation_fa),usage_note_fa=VALUES(usage_note_fa),flashcard_eligible=VALUES(flashcard_eligible);
SET @x_fleisch := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-fleisch'); SET @x_gramm := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-gramm'); SET @x_kilo := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-kilo'); SET @x_wurst := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-wurst'); SET @x_kosten := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-kosten'); SET @x_nehmen := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-nehmen'); SET @x_kasse := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-kasse'); SET @x_bezahlen := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-bezahlen'); SET @x_noch := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-noch-etwas'); SET @x_euro := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-euro');
INSERT INTO lexeme_forms(lexeme_form_key,lexeme_id,surface,normalized_surface,form_type,features,origin,review_status,notes) VALUES
('lexform-de-kosten-kostet',@x_kosten,'kostet','kostet','inflected',JSON_OBJECT('tense','present','mood','indicative','person','3','number','singular'),'source_attested','approved','در پرسش منبع‌دار دربارهٔ قیمت گوشت، فعل قیمت داشتن به‌صورت سوم‌شخص مفرد زمان حال آمده است.'),
('lexform-de-nehmen-nehme',@x_nehmen,'nehme','nehme','inflected',JSON_OBJECT('tense','present','mood','indicative','person','1','number','singular'),'source_attested','approved','در جملهٔ منبع‌دار افزودن سوسیس به خرید، فعل گرفتن به‌صورت اول‌شخص مفرد زمان حال آمده است.')
ON DUPLICATE KEY UPDATE lexeme_id=VALUES(lexeme_id),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),form_type=VALUES(form_type),features=VALUES(features),origin=VALUES(origin),review_status=VALUES(review_status),notes=VALUES(notes);
SET @f_kostet := (SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-kosten-kostet'); SET @f_nehme := (SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-nehmen-nehme');
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-shopping-quantity-payment',@level,@unit,9,1,'چقدر می‌خواهید؟','Wie viel kostet dieses Fleisch? / Wie viel möchten Sie?','این گوشت چقدر است؟ / چه مقدار می‌خواهید؟','draft','گفت‌وگوی کامل تراکنش را در بافت می‌آورد؛ تطبیق چهار کالای دیگر مقدار را به قیمت وصل می‌کند، انتخاب پاسخ مقدار فهم نوبت فروشنده را می‌سنجد و مرتب‌سازی جملهٔ پرداخت آخرین مرحلهٔ خرید را فعال می‌کند.','درس از مشارکت در یک تراکنش واقعی به خواندن مقدار و قیمت، انتخاب پاسخ مناسب و در پایان بازیابی هدایت‌شدهٔ دستور پرداخت حرکت می‌کند.','conversation_speaking>matching>choose_response>word_order','blocked_until_level_final','یک گفت‌وگوی منبع‌دار هشت‌نوبتی هستهٔ کل واحد خرید را می‌سازد.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),source_title=VALUES(source_title),source_title_fa=VALUES(source_title_fa),status=VALUES(status),activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-shopping-quantity-payment');
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role) VALUES(@lesson,@t_shop,'introduce'),(@lesson,@t_shop_sit,'introduce'),(@lesson,@t_core,'introduce'),(@lesson,@t_numbers,'practice'),(@lesson,@t_present,'practice');
INSERT IGNORE INTO lesson_lexemes(lesson_id,lexeme_id,is_primary,role) VALUES(@lesson,@x_fleisch,TRUE,'introduce'),(@lesson,@x_gramm,TRUE,'introduce'),(@lesson,@x_kilo,TRUE,'introduce'),(@lesson,@x_wurst,TRUE,'introduce'),(@lesson,@x_kosten,TRUE,'introduce'),(@lesson,@x_nehmen,TRUE,'introduce'),(@lesson,@x_kasse,TRUE,'introduce'),(@lesson,@x_bezahlen,TRUE,'introduce'),(@lesson,@x_noch,TRUE,'introduce'),(@lesson,@x_euro,FALSE,'review');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES('dlg-de-a1-shopping-quantity-payment',@level,'آیریس در فروشگاه از لنا قیمت گوشت را می‌پرسد، مقدار می‌خواهد، سوسیس هم اضافه می‌کند و در پایان راهنمای پرداخت در صندوق را می‌شنود.','learner','هشت نوبت بخش ۳۹۹ یک تراکنش کامل و طبیعی می‌سازند: سؤال قیمت، پاسخ قیمت، درخواست مقدار، افزودن کالا، تعیین مقدار دوم، پایان سفارش و پرداخت. فقط فاصلهٔ چاپی پیش از نقطه در یک نوبت به نشانه‌گذاری معمول تبدیل شده است.') ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dialogue := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-shopping-quantity-payment');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-1',@dialogue,1,@iris,'app_assigned','unspecified','Wie viel kostet dieses Fleisch?','این گوشت چقدر قیمت دارد؟',TRUE,'blocked_until_level_final'),
('turn-de-a1-shopping-2',@dialogue,2,@lena,'app_assigned','unspecified','500 Gramm kosten 5,20 Euro.','۵۰۰ گرم ۵٫۲۰ یورو قیمت دارد.',FALSE,'blocked_until_level_final'),
('turn-de-a1-shopping-3',@dialogue,3,@iris,'app_assigned','unspecified','Bitte ein Kilo. Ich nehme auch noch Wurst.','لطفاً یک کیلو. سوسیس هم می‌گیرم.',TRUE,'blocked_until_level_final'),
('turn-de-a1-shopping-4',@dialogue,4,@lena,'app_assigned','unspecified','Wie viel möchten Sie?','چه مقدار می‌خواهید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-shopping-5',@dialogue,5,@iris,'app_assigned','unspecified','Bitte 250 Gramm.','لطفاً ۲۵۰ گرم.',TRUE,'blocked_until_level_final'),
('turn-de-a1-shopping-6',@dialogue,6,@lena,'app_assigned','unspecified','Noch etwas?','چیز دیگری؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-shopping-7',@dialogue,7,@iris,'app_assigned','unspecified','Danke, das ist alles.','ممنون، همین کافی است.',TRUE,'blocked_until_level_final'),
('turn-de-a1-shopping-8',@dialogue,8,@lena,'app_assigned','unspecified','Dort ist die Kasse. Bezahlen Sie bitte dort.','صندوق آنجاست. لطفاً آنجا پرداخت کنید.',FALSE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-conversation',@lesson,1,'conversation_speaking','خرید را از پرسیدن قیمت تا رسیدن به صندوق انجام بده.','گفت‌وگوی هشت‌نوبتی منبع همهٔ مراحل اصلی تراکنش این واحد را به‌صورت پیوسته دارد.',@dialogue,JSON_OBJECT('interaction','read_aloud_exchange','openingInitiator','learner'),JSON_ARRAY('verbatim_dialogue','other','persian_translation_added','character_metadata_added'),NULL,'not_required'),
('act-de-a1-shopping-price-matching',@lesson,2,'matching','هر مقدار کالا را به قیمت منبع‌دار خودش وصل کن.','چهار نمونهٔ بخش ۴۱۰ مقدارهای متفاوت و چند کالای روزمره را با قیمت واقعی تمرین پیوند می‌دهند.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','300 g Wurst','leftFa','۳۰۰ گرم سوسیس','right','5,99 Euro','rightFa','۵٫۹۹ یورو'),JSON_OBJECT('left','250 g Butter','leftFa','۲۵۰ گرم کره','right','3,95 Euro','rightFa','۳٫۹۵ یورو'),JSON_OBJECT('left','zwei Flaschen Milch','leftFa','دو بطری شیر','right','2,99 Euro','rightFa','۲٫۹۹ یورو'),JSON_OBJECT('left','fünf Eier','leftFa','پنج تخم‌مرغ','right','2,67 Euro','rightFa','۲٫۶۷ یورو'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-shopping-quantity-response',@lesson,3,'choose_response','فروشنده مقدار را می‌پرسد؛ پاسخ درست را انتخاب کن.','پاسخ مقدار باید از دو نوبت دیگر همان تراکنش متمایز شود.',NULL,JSON_OBJECT('promptTarget','Wie viel möchten Sie?','promptFa','چه مقدار می‌خواهید؟','options',JSON_ARRAY(JSON_OBJECT('textTarget','Bitte 250 Gramm.','translationFa','لطفاً ۲۵۰ گرم.','correct',TRUE),JSON_OBJECT('textTarget','Noch etwas?','translationFa','چیز دیگری؟','correct',FALSE),JSON_OBJECT('textTarget','Danke, das ist alles.','translationFa','ممنون، همین کافی است.','correct',FALSE))),JSON_ARRAY('options_selected_from_source_material','persian_translation_added'),NULL,'not_required'),
('act-de-a1-shopping-payment-order',@lesson,4,'word_order','دستور پرداخت را دوباره بساز.','آخرین مرحلهٔ تراکنش از فهم و خواندن به بازیابی فعال جملهٔ پرداخت منتقل می‌شود.',NULL,JSON_OBJECT('sourceText','Bezahlen Sie bitte dort.','sourceTextFa','لطفاً آنجا پرداخت کنید.','tokens',JSON_ARRAY('Bezahlen','Sie','bitte','dort.'),'answer',JSON_ARRAY('Bezahlen','Sie','bitte','dort.')),JSON_ARRAY('sentence_tokenized_for_word_order','persian_translation_added'),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
SET @a1 := (SELECT id FROM activities WHERE activity_key='act-de-a1-shopping-conversation'); SET @a2 := (SELECT id FROM activities WHERE activity_key='act-de-a1-shopping-price-matching'); SET @a3 := (SELECT id FROM activities WHERE activity_key='act-de-a1-shopping-quantity-response'); SET @a4 := (SELECT id FROM activities WHERE activity_key='act-de-a1-shopping-payment-order');
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) VALUES(@a1,@t_shop),(@a1,@t_shop_sit),(@a1,@t_numbers),(@a1,@t_present),(@a2,@t_shop),(@a2,@t_numbers),(@a3,@t_shop),(@a3,@t_shop_sit),(@a4,@t_shop),(@a4,@t_present);
INSERT IGNORE INTO activity_lexemes(activity_id,lexeme_id) VALUES(@a1,@x_fleisch),(@a1,@x_gramm),(@a1,@x_kilo),(@a1,@x_wurst),(@a1,@x_kosten),(@a1,@x_nehmen),(@a1,@x_kasse),(@a1,@x_bezahlen),(@a1,@x_noch),(@a1,@x_euro),(@a2,@x_gramm),(@a2,@x_wurst),(@a2,@x_euro),(@a3,@x_gramm),(@a3,@x_noch),(@a4,@x_bezahlen);
INSERT INTO lexeme_occurrences(occurrence_key,owner_type,owner_key,surface,start_offset,end_offset,lexeme_id,lexeme_form_id,resolution_status,resolution_notes) VALUES
('occ-turn-de-a1-shop-1-kostet','dialogue_turn','turn-de-a1-shopping-1','kostet',NULL,NULL,@x_kosten,@f_kostet,'approved','صورت صرفی به فعل قیمت داشتن متصل است.'),('occ-turn-de-a1-shop-1-fleisch','dialogue_turn','turn-de-a1-shopping-1','Fleisch',NULL,NULL,@x_fleisch,NULL,'approved','اتصال واژهٔ گوشت تأیید شده است.'),('occ-turn-de-a1-shop-2-gramm','dialogue_turn','turn-de-a1-shopping-2','Gramm',NULL,NULL,@x_gramm,NULL,'approved','اتصال واحد گرم تأیید شده است.'),('occ-turn-de-a1-shop-2-kosten','dialogue_turn','turn-de-a1-shopping-2','kosten',NULL,NULL,@x_kosten,NULL,'approved','صورت پایه در جملهٔ جمع آمده است.'),('occ-turn-de-a1-shop-2-euro','dialogue_turn','turn-de-a1-shopping-2','Euro',NULL,NULL,@x_euro,NULL,'approved','اتصال یورو تأیید شده است.'),('occ-turn-de-a1-shop-3-kilo','dialogue_turn','turn-de-a1-shopping-3','Kilo',NULL,NULL,@x_kilo,NULL,'approved','اتصال کیلو تأیید شده است.'),('occ-turn-de-a1-shop-3-nehme','dialogue_turn','turn-de-a1-shopping-3','nehme',NULL,NULL,@x_nehmen,@f_nehme,'approved','صورت صرفی به فعل گرفتن متصل است.'),('occ-turn-de-a1-shop-3-wurst','dialogue_turn','turn-de-a1-shopping-3','Wurst',NULL,NULL,@x_wurst,NULL,'approved','اتصال سوسیس تأیید شده است.'),('occ-turn-de-a1-shop-5-gramm','dialogue_turn','turn-de-a1-shopping-5','Gramm',NULL,NULL,@x_gramm,NULL,'approved','اتصال واحد گرم تأیید شده است.'),('occ-turn-de-a1-shop-6-noch-etwas','dialogue_turn','turn-de-a1-shopping-6','Noch etwas',NULL,NULL,@x_noch,NULL,'approved','عبارت چیز دیگری ثبت شده است.'),('occ-turn-de-a1-shop-8-kasse','dialogue_turn','turn-de-a1-shopping-8','Kasse',NULL,NULL,@x_kasse,NULL,'approved','اتصال صندوق تأیید شده است.'),('occ-turn-de-a1-shop-8-bezahlen','dialogue_turn','turn-de-a1-shopping-8','Bezahlen',NULL,NULL,@x_bezahlen,NULL,'approved','اتصال فعل پرداخت تأیید شده است.')
ON DUPLICATE KEY UPDATE owner_type=VALUES(owner_type),owner_key=VALUES(owner_key),surface=VALUES(surface),lexeme_id=VALUES(lexeme_id),lexeme_form_id=VALUES(lexeme_form_id),resolution_status=VALUES(resolution_status),resolution_notes=VALUES(resolution_notes);
SET @si1 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-1'); SET @si2 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-2'); SET @si3 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-3'); SET @si4 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-4'); SET @si5 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-5'); SET @si6 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-6'); SET @si7 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-7'); SET @si8 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-8'); SET @siw := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-410-wurst'); SET @sib := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-410-butter'); SET @sim := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-410-milch'); SET @sie := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-shop-410-eier');
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES
('dialogue_turn','turn-de-a1-shopping-1',@si1,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-shopping-2',@si2,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-shopping-3',@si3,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-shopping-4',@si4,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-shopping-5',@si5,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-shopping-6',@si6,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-shopping-7',@si7,'other','فقط فاصلهٔ چاپی پیش از نقطه به نشانه‌گذاری معمول تبدیل شده است.'),('dialogue_turn','turn-de-a1-shopping-8',@si8,'verbatim','متن هدف عین منبع است.'),
('lexeme','lex-de-fleisch',@si1,'other','واژه در جملهٔ منبع آمده است.'),('lexeme','lex-de-gramm',@si2,'other','واژه در جملهٔ منبع آمده است.'),('lexeme','lex-de-kilo',@si3,'other','واژه در جملهٔ منبع آمده است.'),('lexeme','lex-de-wurst',@si3,'other','واژه در جملهٔ منبع آمده است.'),('lexeme','lex-de-kosten',@si1,'other','فعل در جملهٔ منبع آمده است.'),('lexeme','lex-de-nehmen',@si3,'other','فعل در جملهٔ منبع آمده است.'),('lexeme','lex-de-kasse',@si8,'other','واژه در جملهٔ منبع آمده است.'),('lexeme','lex-de-bezahlen',@si8,'other','فعل در جملهٔ منبع آمده است.'),('lexeme','lex-de-noch-etwas',@si6,'verbatim','عبارت عین منبع ثبت شده است.'),('lexeme_form','lexform-de-kosten-kostet',@si1,'other','صورت صرفی از جملهٔ منبع استخراج شده است.'),('lexeme_form','lexform-de-nehmen-nehme',@si3,'other','صورت صرفی از جملهٔ منبع استخراج شده است.'),
('activity','act-de-a1-shopping-price-matching',@siw,'source_items_grouped_for_matching','مقدار و قیمت از جملهٔ منبع استخراج شده‌اند.'),('activity','act-de-a1-shopping-price-matching',@sib,'source_items_grouped_for_matching','مقدار و قیمت از جملهٔ منبع استخراج شده‌اند.'),('activity','act-de-a1-shopping-price-matching',@sim,'source_items_grouped_for_matching','مقدار و قیمت از جملهٔ منبع استخراج شده‌اند.'),('activity','act-de-a1-shopping-price-matching',@sie,'source_items_grouped_for_matching','مقدار و قیمت از جملهٔ منبع استخراج شده‌اند.'),('activity','act-de-a1-shopping-quantity-response',@si4,'other','پرسش فعالیت عین منبع است.'),('activity','act-de-a1-shopping-quantity-response',@si5,'options_selected_from_source_material','گزینهٔ درست عین منبع است.'),('activity','act-de-a1-shopping-quantity-response',@si6,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),('activity','act-de-a1-shopping-quantity-response',@si7,'options_selected_from_source_material','گزینهٔ مقایسه‌ای با نشانه‌گذاری استاندارد منبع است.'),('activity','act-de-a1-shopping-payment-order',@si8,'sentence_tokenized_for_word_order','جملهٔ پرداخت از نوبت منبع برای مرتب‌سازی جدا شده است.');
UPDATE language_levels SET coverage=JSON_SET(coverage,'$.gaps[2]','پنج واحد نخست به بازبینی رسیده‌اند؛ مرحلهٔ بعد سفارش گسترده‌تر غذا و نوشیدنی است.'),notes='A1 همچنان در مرحلهٔ ساخت تدریجی است. پنج واحد نخست در بازبینی‌اند. مرحلهٔ بعد سفارش گسترده‌تر غذا و نوشیدنی است و باید با یک سناریوی منبع‌دار فراتر از سفارش تک‌قلمی سطح پیشین ساخته شود.' WHERE id=@level;
COMMIT;
