-- Replace second seven A1 depth lessons with new source-backed content.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);

-- de-a1-lesson-food-combinations-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-food-substitutes',@level,'مشتری موجودبودن دو گروه غذایی را می‌پرسد و پاسخ جایگزین موجود را معرفی می‌کند.','app','دو جفت سؤال‌وجواب منبع‌دارِ «موجود نیست، اما جایگزین هست» برای مهارت مدیریت نبودن یک قلم انتخاب شده‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-food-substitutes' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-food-substitutes-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Gibt es Käse?','پنیر هست؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-food-substitutes-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Nein, aber es gibt Wurst.','نه، اما سوسیس هست.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-food-substitutes-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Gibt es Gemüse?','سبزیجات هست؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-food-substitutes-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Nein, aber es gibt Obst.','نه، اما میوه هست.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-expanded-food-order' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-food-combinations-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='نداریم؛ این چطور؟',activity_selection_rationale='این درس مهارت تازهٔ مدیریت ناموجودبودن یک قلم را اضافه می‌کند؛ زبان‌آموز فقط سفارش حفظ‌شده نمی‌دهد و باید جایگزین را بفهمد.',sequence_rationale='مکالمه الگوی سؤال/جایگزین را معرفی می‌کند، تطبیق چهار جفت دامنه را گسترش می‌دهد و تکمیل جمله ساختار aber es gibt را تثبیت می‌کند.',template_signature='conversation_speaking>matching>fill_blank',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-food-combinations-review-conversation',@lesson,1,'conversation_speaking','بپرس چه چیزی موجود است و جایگزین پیشنهادی را بفهم.','دو جفت پرسش‌وپاسخ منبع‌دار الگوی نبودن یک قلم و وجود جایگزین را در بافت سفارش نشان می‌دهند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-food-substitutes' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-food-combinations-review-matching',@lesson,2,'matching','هر قلم ناموجود را به جایگزین منبع‌دارش وصل کن.','چهار جفت مختلف نشان می‌دهند الگو به یک خوراکی محدود نیست.',NULL,CAST('{"pairs":[{"left":"Käse","leftFa":"پنیر","right":"Wurst","rightFa":"سوسیس"},{"left":"Gemüse","leftFa":"سبزیجات","right":"Obst","rightFa":"میوه"},{"left":"Milch","leftFa":"شیر","right":"Tee","rightFa":"چای"},{"left":"Wasser","leftFa":"آب","right":"Kakao","rightFa":"کاکائو"}]}' AS JSON),CAST('["source_items_grouped_for_matching","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-food-combinations-review-order',@lesson,3,'fill_blank','پاسخ جایگزین را کامل کن.','تکمیل aber es gibt ساختار کاربردی پاسخ به نبودن یک قلم را فعال می‌کند.',NULL,CAST('{"sourceText":"Nein, aber es gibt Tee.","sourceTextFa":"نه، اما چای هست.","blankedText":"Nein, aber es gibt ___.","blankedTextFa":"نه، اما ___ هست.","choices":["Tee","Milch","Wasser"],"choicesFa":["چای","شیر","آب"],"answer":"Tee"}' AS JSON),CAST('["source_sentence_blank_created","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-time-plans-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-reschedule-exact-time',@level,'یک زمان مشخص رد می‌شود و بعد یک زمان و محل دقیق جایگزین تأیید می‌شود.','app','پاسخ رد ساعت از تمرین ۸۸۶ و جفت توافق زمان/مکان از گفت‌وگوی ۸۷۷ عین منبع حفظ شده‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-reschedule-exact-time' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-reschedule-exact-time-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Warten Sie um 12 Uhr auf mich?','ساعت ۱۲ منتظر من می‌مانید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-reschedule-exact-time-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Es tut mir leid, um 12 Uhr geht es nicht.','متأسفم، ساعت ۱۲ نمی‌شود.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-reschedule-exact-time-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Dann warte ich morgen am Kino 19.45 Uhr. Ist Ihnen das Recht?','پس فردا ساعت ۱۹:۴۵ جلوی سینما منتظرتان می‌مانم. برایتان مناسب است؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-reschedule-exact-time-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ja, das passt mir. Gut, morgen Abend am Kino.','بله، برایم مناسب است. خوب، فردا شب جلوی سینما.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-time-plans-appointment' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-time-plans-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='این ساعت نمی‌شه؛ ساعت دیگه چطور؟',activity_selection_rationale='دو درس قبلی بازهٔ برنامه و دعوت را پوشش می‌دهند؛ این درس مذاکرهٔ واقعی روی ساعت دقیق و تأیید زمان/محل را اضافه می‌کند.',sequence_rationale='رد یک ساعت در مکالمه به پیشنهاد ساعت تازه می‌رسد، سپس تشخیص معنای توافق و بازسازی پرسش زمان تمرین می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-time-review-conversation',@lesson,1,'conversation_speaking','یک ساعت نامناسب را رد کن و زمان جایگزین را تأیید کن.','جفت‌های منبع‌دار ساعت ۱۲ و ۱۹:۴۵، چرخهٔ رد → پیشنهاد → تأیید را کامل می‌کنند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-reschedule-exact-time' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["other","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-time-review-matching',@lesson,2,'multiple_choice','کدام جمله یعنی «این زمان برای من مناسبه»؟','زبان‌آموز باید پاسخ توافق را از رد زمان تشخیص دهد.',NULL,CAST('{"options":[{"textTarget":"Ja, das passt mir.","translationFa":"بله، برایم مناسب است.","correct":true},{"textTarget":"Es tut mir leid, um 12 Uhr geht es nicht.","translationFa":"متأسفم، ساعت ۱۲ نمی‌شود.","correct":false},{"textTarget":"Morgen geht es vielleicht.","translationFa":"فردا شاید بشود.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-time-review-order',@lesson,3,'word_order','پرسش قرار ساعت ۱۲ را بساز.','بازسازی پرسش، الگوی um + ساعت را در یک درخواست واقعی تثبیت می‌کند.',NULL,CAST('{"sourceText":"Warten Sie um 12 Uhr auf mich?","sourceTextFa":"ساعت ۱۲ منتظر من می‌مانید؟","tokens":["Warten","Sie","um","12","Uhr","auf","mich?"],"answer":["Warten","Sie","um","12","Uhr","auf","mich?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-directions-public-places-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-hotel-restaurant-location',@level,'مسافر ابتدا هتل را پیدا می‌کند و بعد می‌پرسد آیا رستورانی در آن هست.','learner','چهار نوبت نخست گفت‌وگوی ۵-۲ منبع بدون ساخت جملهٔ تازه استفاده شده و موقعیت نسبی رستوران نسبت به هتل را آموزش می‌دهد.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-hotel-restaurant-location' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-hotel-restaurant-location-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Entschuldigen Sie bitte. Wo ist hier ein Hotel?','ببخشید. اینجا یک هتل کجاست؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-hotel-restaurant-location-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Gleich dort drüben. Das ist das Hotel "Zur Post".','همین آن طرف. آن هتل «Zur Post» است.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-hotel-restaurant-location-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Gibt es ein Restaurant darin?','داخلش رستوران هست؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-hotel-restaurant-location-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Ja gewiss! Ein Restaurant mit einfacher Küche, besonders zum Abendessen. Aber ich könnte Ihnen ein anderes Restaurant empfehlen. Es heißt ''Alt-Wien'', und es gibt dort das beste Frühstück. Das Restaurant ist links neben dem Hotel, um die Ecke.','بله، حتماً! یک رستوران با غذای ساده، مخصوصاً برای شام. اما می‌توانم رستوران دیگری پیشنهاد کنم. اسمش «Alt-Wien» است و آنجا بهترین صبحانه را دارند. رستوران سمت چپ هتل، سرِ پیچ است.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-directions-public-places' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-directions-public-places-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='هتل کجاست؟ رستورانش کجاست؟',activity_selection_rationale='این درس به‌جای فهرست‌کردن مقصدها، یک مسئلهٔ مکانی تازه را پوشش می‌دهد: پیدا کردن هتل و سپس مکان رستوران نسبت به آن.',sequence_rationale='مکالمه مکان را در بافت واقعی معرفی می‌کند، تمرین جهت نسبی را می‌سنجد و بازسازی پرسش محل هتل تولید هدایت‌شده می‌دهد.',template_signature='conversation_speaking>multiple_choice>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-places-review-conversation',@lesson,1,'conversation_speaking','خودت گفت‌وگو را شروع کن: هتل را پیدا کن و بعد دربارهٔ رستوران داخل یا کنار آن بپرس.','چهار نوبت نخست گفت‌وگوی منبع یک زنجیرهٔ واقعیِ مقصد → امکان → موقعیت نسبی می‌سازند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-hotel-restaurant-location' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"learner"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-places-review-matching',@lesson,2,'multiple_choice','رستوران «Alt-Wien» نسبت به هتل کجاست؟','پاسخ از جملهٔ منبع‌دار استخراج می‌شود و فهم موقعیت نسبی را می‌سنجد.',NULL,CAST('{"options":[{"textTarget":"links neben dem Hotel, um die Ecke","translationFa":"سمت چپ هتل، سرِ پیچ","correct":true},{"textTarget":"Rechts um die Ecke","translationFa":"سرِ پیچ سمت راست","correct":false},{"textTarget":"immer geradeaus","translationFa":"همیشه مستقیم","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-places-review-order',@lesson,3,'word_order','پرسش محل هتل را بساز.','پرسش Wo ist hier ... الگوی مستقیم پیدا کردن یک مکان را فعال می‌کند.',NULL,CAST('{"sourceText":"Wo ist hier ein Hotel?","sourceTextFa":"اینجا یک هتل کجاست؟","tokens":["Wo","ist","hier","ein","Hotel?"],"answer":["Wo","ist","hier","ein","Hotel?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-directions-sequence-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-train-arrival-station',@level,'مسافر زمان رسیدن قطار و محل ایستگاه را می‌پرسد.','app','دو جفت کاربردیِ زمان رسیدن و پیدا کردن ایستگاه از منابع جدا اما سازگار در یک سناریوی سفر کوتاه ترکیب شده‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-train-arrival-station' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-train-arrival-station-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wann kommt der Zug an?','قطار چه زمانی می‌رسد؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-train-arrival-station-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Der Zug kommt 16.20 Uhr an.','قطار ساعت ۱۶:۲۰ می‌رسد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-train-arrival-station-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wo ist der Bahnhof?','ایستگاه قطار کجاست؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-train-arrival-station-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Gleich dort drüben.','همین آن طرف.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-directions-public-places' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-directions-sequence-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='قطار چه ساعتی می‌رسه؟ ایستگاه کجاست؟',activity_selection_rationale='این درس جهت‌های چپ/راستِ درس اصلی را تکرار نمی‌کند؛ واحد را به یک نیاز سفر تازه یعنی زمان رسیدن قطار و پیدا کردن ایستگاه گسترش می‌دهد.',sequence_rationale='مکالمه زمان و مکان را ترکیب می‌کند، تطبیق واژگان حمل‌ونقل دامنه را باز می‌کند و بازسازی پرسش رسیدن قطار تولید هدایت‌شده می‌دهد.',template_signature='conversation_speaking>matching>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-sequence-review-conversation',@lesson,1,'conversation_speaking','زمان رسیدن قطار را بپرس و بعد ایستگاه را پیدا کن.','دو مسئلهٔ واقعی سفر در یک مکالمهٔ کوتاه و منبع‌دار ترکیب شده‌اند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-train-arrival-station' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["other","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-sequence-review-choice',@lesson,2,'matching','هر مکان حمل‌ونقل را به معنی درست وصل کن.','چهار مقصد پرتکرار، واژگان سفر شهری را فراتر از یک ایستگاه گسترش می‌دهند.',NULL,CAST('{"pairs":[{"left":"Bahnhof","leftFa":"ایستگاه قطار","right":"ایستگاه قطار","rightFa":"ایستگاه قطار"},{"left":"Bushaltestelle","leftFa":"ایستگاه اتوبوس","right":"ایستگاه اتوبوس","rightFa":"ایستگاه اتوبوس"},{"left":"Flughafen","leftFa":"فرودگاه","right":"فرودگاه","rightFa":"فرودگاه"},{"left":"Stadtmitte","leftFa":"مرکز شهر","right":"مرکز شهر","rightFa":"مرکز شهر"}]}' AS JSON),CAST('["source_items_grouped_for_matching","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-sequence-review-fill',@lesson,3,'word_order','پرسش زمان رسیدن قطار را بساز.','فعل جداشدنی ankommen در یک جملهٔ کوتاه و واقعی به‌صورت هدایت‌شده بازیابی می‌شود.',NULL,CAST('{"sourceText":"Wann kommt der Zug an?","sourceTextFa":"قطار چه زمانی می‌رسد؟","tokens":["Wann","kommt","der","Zug","an?"],"answer":["Wann","kommt","der","Zug","an?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-services-permission-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-clothing-store-help',@level,'کارمند فروشگاه پیشنهاد کمک می‌دهد؛ مشتری برای پیدا کردن سایز مناسب کمک می‌خواهد و اتاق پرو را می‌پرسد.','app','شش نوبت پیوسته از گفت‌وگوی فروشگاه منبع حفظ شده‌اند و درخواست کمک مشخص را در خدمات واقعی تمرین می‌کنند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-clothing-store-help' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-clothing-store-help-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Darf ich Ihnen helfen?','می‌توانم کمکتان کنم؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-clothing-store-help-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ja, können Sie mir helfen, diesen Rock in meiner Größe zu finden?','بله، می‌توانید کمکم کنید این دامن را در سایز من پیدا کنم؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-clothing-store-help-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Natürlich.','البته.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-clothing-store-help-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Hier ist der Rock in Ihrer Größe.','این هم دامن در سایز شما.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-clothing-store-help-5',@dlg,5,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Danke. Wo ist die Umkleidekabine?','ممنون. اتاق پرو کجاست؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-clothing-store-help-6',@dlg,6,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Dort drüben.','آن طرف.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-requests-services-help' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-services-permission-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='سایزم رو پیدا می‌کنید؟',activity_selection_rationale='این درس به‌جای تکرار اجازهٔ تلفن، یک خدمت واقعی تازه را آموزش می‌دهد: درخواست کمک مشخص از کارمند فروشگاه و پیدا کردن اتاق پرو.',sequence_rationale='مکالمهٔ کامل خدماتی اجرا می‌شود، سپس پاسخ مناسب به پیشنهاد کمک و پرسش محل اتاق پرو تمرین می‌شوند.',template_signature='conversation_speaking>choose_response>fill_blank',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-services-permission-review-conversation',@lesson,1,'conversation_speaking','از کارمند فروشگاه برای پیدا کردن سایز مناسب کمک بگیر و اتاق پرو را پیدا کن.','گفت‌وگوی پیوستهٔ منبع یک تعامل خدماتی کامل و طبیعی ارائه می‌کند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-clothing-store-help' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-services-permission-review-choice',@lesson,2,'choose_response','به «Darf ich Ihnen helfen?» پاسخ مناسب را انتخاب کن.','پاسخ درست دقیقاً درخواست کمک مشخص برای سایز مناسب است.',NULL,CAST('{"promptTarget":"Darf ich Ihnen helfen?","promptFa":"می‌توانم کمکتان کنم؟","options":[{"textTarget":"Ja, können Sie mir helfen, diesen Rock in meiner Größe zu finden?","translationFa":"بله، می‌توانید کمکم کنید این دامن را در سایز من پیدا کنم؟","correct":true},{"textTarget":"Danke. Wo ist die Umkleidekabine?","translationFa":"ممنون. اتاق پرو کجاست؟","correct":false},{"textTarget":"Dort drüben.","translationFa":"آن طرف.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-services-permission-review-order',@lesson,3,'fill_blank','پرسش محل اتاق پرو را کامل کن.','واژهٔ کلیدیِ خدمت فروشگاه در قالب پرسش واقعی تثبیت می‌شود.',NULL,CAST('{"sourceText":"Danke. Wo ist die Umkleidekabine?","sourceTextFa":"ممنون. اتاق پرو کجاست؟","blankedText":"Danke. Wo ist die ___?","blankedTextFa":"ممنون. ___ کجاست؟","choices":["Umkleidekabine","Größe","Rock"],"choicesFa":["اتاق پرو","سایز","دامن"],"answer":"Umkleidekabine"}' AS JSON),CAST('["source_sentence_blank_created","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-services-help-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-urgent-service-help',@level,'پاول می‌گوید کمک لازم دارد و بعد محل پیدا کردن پزشک را می‌پرسد؛ آیریس جهت کلی را نشان می‌دهد.','learner','جمله‌ها همگی مستقیماً از منابع ثبت‌شده آمده‌اند؛ فقط برای ساخت یک سناریوی خدمات ضروری کنار هم قرار گرفته‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-urgent-service-help' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-urgent-service-help-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ich brauche Hilfe.','کمک لازم دارم.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-urgent-service-help-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Natürlich.','البته.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-urgent-service-help-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wo finde ich einen Arzt?','کجا می‌توانم یک پزشک پیدا کنم؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-urgent-service-help-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Gleich dort drüben.','همین آن طرف.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-requests-services-help' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-services-help-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='کمک لازم دارم؛ پزشک کجاست؟',activity_selection_rationale='این درس کمک را از عبارت کلی به یک نیاز مشخص و قابل‌اقدام می‌برد: اعلام نیاز و پیدا کردن پزشک.',sequence_rationale='مکالمه نیاز را به مقصد خدماتی وصل می‌کند، سپس تشخیص پرسش مناسب و بازسازی عبارت کمک تمرین می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-services-help-review-conversation',@lesson,1,'conversation_speaking','خودت گفت‌وگو را شروع کن: بگو کمک لازم داری و محل پزشک را بپرس.','جمله‌های کوتاه از منابع معتبر در یک سناریوی خدمات ضروری کنار هم قرار گرفته‌اند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-urgent-service-help' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"learner"}' AS JSON),CAST('["other","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-services-help-review-response',@lesson,2,'multiple_choice','اگر دنبال پزشک هستی، کدام پرسش را می‌گویی؟','سه پرسش منبع‌دار از حوزه‌های مختلف، انتخاب هدف ارتباطی درست را می‌سنجند.',NULL,CAST('{"options":[{"textTarget":"Wo finde ich einen Arzt?","translationFa":"کجا می‌توانم یک پزشک پیدا کنم؟","correct":true},{"textTarget":"Wo ist der Bahnhof?","translationFa":"ایستگاه قطار کجاست؟","correct":false},{"textTarget":"Was brauchen Sie?","translationFa":"چه چیزی لازم دارید؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-services-help-review-matching',@lesson,3,'word_order','عبارت درخواست کمک را بساز.','یک عبارت بقای بسیار کوتاه و مستقیم به بازیابی فعال منتقل می‌شود.',NULL,CAST('{"sourceText":"Ich brauche Hilfe.","sourceTextFa":"کمک لازم دارم.","tokens":["Ich","brauche","Hilfe."],"answer":["Ich","brauche","Hilfe."]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-forms-signs-message-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-spell-personal-data',@level,'در یک فرم، از زبان‌آموز خواسته می‌شود نام و نام خانوادگی نمونهٔ منبع را حرف‌به‌حرف هجی کند.','app','دستورها و دو نام نمونه از تمرین ۲۹۸ منبع گرفته شده‌اند؛ نمایش حرف‌به‌حرف فقط تبدیل مکانیکی همان دو نمونه برای تمرین هجی‌کردن است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-spell-personal-data' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-spell-personal-data-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Buchstabieren Sie Ihren Vornamen.','نام کوچک‌تان را هجی کنید.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-spell-personal-data-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','M-A-R-C-U-S.','م ـ ا ـ ر ـ ک ـ و ـ س.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-spell-personal-data-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Buchstabieren Sie Ihren Familiennamen.','نام خانوادگی‌تان را هجی کنید.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-spell-personal-data-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','C-L-I-N-T-O-N.','ک ـ ل ـ ی ـ ن ـ ت ـ و ـ ن.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-forms-signs-messages' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-forms-signs-message-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='اسم و آدرست را هجی کن',activity_selection_rationale='درس اول فقط الفبا و فیلدهای فرم را آماده کرده بود؛ این درس مهارت عملیِ بعدی یعنی هجی‌کردن واقعی اطلاعات شخصی را اضافه می‌کند.',sequence_rationale='مکالمه هجی نام را اجرا می‌کند، تطبیق فیلدهای فرم با نمونه‌ها دامنه را گسترش می‌دهد و در پایان درخواست آهسته‌هجی‌کردن بازسازی می‌شود.',template_signature='conversation_speaking>matching>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-forms-review-conversation',@lesson,1,'conversation_speaking','نام و نام خانوادگی نمونه را حرف‌به‌حرف هجی کن.','دو دستور و دو نمونهٔ تمرین ۲۹۸ به یک نقش‌آفرینی فرم تبدیل شده‌اند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-spell-personal-data' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["other","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-forms-review-matching',@lesson,2,'matching','هر فیلد را به نمونهٔ درست منبع وصل کن.','چهار نمونهٔ همان تمرین نشان می‌دهند هجی‌کردن فقط برای نام کوچک نیست.',NULL,CAST('{"pairs":[{"left":"Vorname","leftFa":"نام کوچک","right":"Marcus","rightFa":"مارکوس"},{"left":"Familienname","leftFa":"نام خانوادگی","right":"Clinton","rightFa":"کلینتون"},{"left":"Straßenname","leftFa":"نام خیابان","right":"Hauptstraße","rightFa":"هاوپت‌اشتراسه"},{"left":"Stadt","leftFa":"شهر","right":"Werdau","rightFa":"ورداو"}]}' AS JSON),CAST('["source_items_grouped_for_matching","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-forms-review-order',@lesson,3,'word_order','درخواست «لطفاً آهسته هجی کنید» را بساز.','این جمله مستقیماً مهارت هجی‌کردن را به مدیریت سرعت گفتار وصل می‌کند.',NULL,CAST('{"sourceText":"Können Sie das bitte langsam buchstabieren?","sourceTextFa":"می‌توانید لطفاً آن را آهسته هجی کنید؟","tokens":["Können","Sie","das","bitte","langsam","buchstabieren?"],"answer":["Können","Sie","das","bitte","langsam","buchstabieren?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

UPDATE language_levels SET audio_status='pending' WHERE id=@level;
COMMIT;
