-- German A1 Unit 9 — clarification, permission and everyday services.
-- Base content never overwrites generated audio state.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);
SET @iris := (SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1);
SET @paul := (SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-002-service-clarification','Deutschkurs für Anfänger/Lektion 002','درخواست تکرار و آهسته‌تر گفتن','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_002','Item 075 and vocabulary: asking for repetition and slower speech.','بخش ۰۷۵؛ درخواست تکرار و آهسته‌تر گفتن.','2023-12-13','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ بررسی شد؛ آخرین ویرایش صفحه ۱۳ دسامبر ۲۰۲۳ ثبت شده است. عبارت انتخاب‌شده برای درخواست تکرار و آهسته‌تر گفتن در بازبینی فعلی همچنان طبیعی و کاربردی است.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 002','reuse_with_attribution','2026-09-18','استفاده در این واحد به عبارت بخش ۰۷۵ برای درخواست تکرار و آهسته‌تر گفتن محدود است.'),
('src-wikivoyage-german-phrasebook-services','German phrasebook — Basics and Problems','عبارت‌های خدمات، کمک و اجازه','Wikivoyage contributors','de','website','https://en.wikivoyage.org/wiki/German_phrasebook','Basics and Problems sections: English question, understanding, help, phone permission, toilet and pharmacy.','بخش‌های پایه و مشکلات؛ زبان، فهم، کمک، تلفن، سرویس بهداشتی و داروخانه.',NULL,'maintained_current','بخش‌های پایه و مشکلات در عبارت‌نامهٔ آلمانی ویکی‌ویاژ در ۱۸ سپتامبر ۲۰۲۶ بررسی شدند. پرسش دربارهٔ انگلیسی، بیان نفهمیدن، درخواست کمک، اجازهٔ استفاده از تلفن، سرویس بهداشتی و داروخانه در نسخهٔ فعلی صفحه حضور دارند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikivoyage contributors — German phrasebook','reuse_with_attribution','2026-09-18','در گزینه‌هایی که منبع دو شکل دوستانه و رسمی را کنار هم نوشته، این واحد فقط شکل رسمی را انتخاب می‌کند و این انتخاب در ردگیری منبع ثبت می‌شود.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
SET @sb := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-002-service-clarification');
SET @sv := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-services');

INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@sb,'srcitem-de-a1-service-repeat','075','بخش ۰۷۵','Wie bitte? Noch einmal, bitte langsam.',UNHEX(SHA2('Wie bitte? Noch einmal, bitte langsam.',256)),'درخواست تکرار و آهسته‌تر گفتن.'),
(@sv,'srcitem-de-a1-service-english','Basics','بخش پایه','Sprechen Sie Englisch?',UNHEX(SHA2('Sprechen Sie Englisch?',256)),'پرسش رسمی دربارهٔ زبان انگلیسی.'),
(@sv,'srcitem-de-a1-service-understand','Basics','بخش پایه','Ich verstehe das nicht.',UNHEX(SHA2('Ich verstehe das nicht.',256)),'بیان نفهمیدن.'),
(@sv,'srcitem-de-a1-service-toilet','Basics','بخش پایه','Wo ist die Toilette, bitte?',UNHEX(SHA2('Wo ist die Toilette, bitte?',256)),'پرسش خدماتی.'),
(@sv,'srcitem-de-a1-service-help','Problems','بخش مشکلات','Ich brauche deine/Ihre Hilfe.',UNHEX(SHA2('Ich brauche deine/Ihre Hilfe.',256)),'منبع دو شکل دوستانه و رسمی را کنار هم دارد.'),
(@sv,'srcitem-de-a1-service-phone','Problems','بخش مشکلات','Kann ich dein/Ihr Telefon benutzen?',UNHEX(SHA2('Kann ich dein/Ihr Telefon benutzen?',256)),'منبع دو شکل دوستانه و رسمی را کنار هم دارد.'),
(@sv,'srcitem-de-a1-service-apotheke','At the doctor','بخش پزشک','Apotheke',UNHEX(SHA2('Apotheke',256)),'واژهٔ داروخانه.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);

INSERT INTO units(unit_key,language_level_id,sequence_index,title_fa,grouping_rationale,status,metadata,notes) VALUES
('de-a1-unit-requests-services-help',@level,9,'درخواست، اجازه و خدمات روزمره','این واحد توانایی‌های بقای سطح پیشین را از عبارت‌های ثابت به مدیریت یک مشکل ارتباطی ساده گسترش می‌دهد: روشن‌سازی، اجازه گرفتن و درخواست کمک مشخص. یک درس پنج‌فعالیتی این سه کارکرد را بدون ساخت درس‌های تکراری پوشش می‌دهد.','review',JSON_OBJECT('sourceRefs',JSON_ARRAY('src-wikibooks-de-lesson-002-service-clarification','src-wikivoyage-german-phrasebook-services'),'learningTargets',JSON_ARRAY('درخواست تکرار و آهسته‌تر گفتن','اجازهٔ ساده','درخواست کمک مشخص','واژگان خدمات پایه')),'بازبینی پوشش انجام شد. درخواست تکرار و آهسته‌تر گفتن، اجازهٔ استفاده از تلفن، درخواست کمک و واژگان خدمات پایه پوشش دارند؛ برای هدف فعلی خدمات و کمک شکاف ضروری مستقلی برای درس دوم دیده نشد.')
ON DUPLICATE KEY UPDATE sequence_index=VALUES(sequence_index),title_fa=VALUES(title_fa),grouping_rationale=VALUES(grouping_rationale),status=IF(status='final',status,VALUES(status)),metadata=VALUES(metadata),notes=VALUES(notes);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-requests-services-help');
SET @t_help := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-requests-help');
SET @t_sit := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-sit-services-help');
SET @t_modal := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-modal-request-patterns');
SET @t_reg := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-pronouns-register');
SET @t_core := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-core-vocabulary');
INSERT IGNORE INTO unit_targets(unit_id,curriculum_target_id) VALUES(@unit,@t_help),(@unit,@t_sit),(@unit,@t_modal),(@unit,@t_reg),(@unit,@t_core);

INSERT INTO lexemes(lexeme_key,language_id,lexeme_type,surface,normalized_surface,lemma,part_of_speech,part_of_speech_fa,cefr_level,translation_fa,usage_note_fa,flashcard_eligible,audio_status) VALUES
('lex-de-langsam',@de,'word','langsam','langsam','langsam','adverb','قید','A1','آهسته','در درخواست منبع‌دار برای آهسته‌تر تکرار کردن استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-noch-einmal',@de,'phrase','noch einmal','noch einmal',NULL,NULL,NULL,'A1','یک بار دیگر / دوباره','در درخواست کوتاه برای تکرار دوباره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-telefon',@de,'word','Telefon','Telefon','Telefon','noun','اسم','A1','تلفن','در پرسش اجازهٔ استفاده از تلفن آمده است.',TRUE,'blocked_until_level_final'),
('lex-de-benutzen',@de,'word','benutzen','benutzen','benutzen','verb','فعل','A1','استفاده کردن','در پرسش اجازهٔ استفاده از تلفن به کار می‌رود.',TRUE,'blocked_until_level_final'),
('lex-de-apotheke',@de,'word','Apotheke','Apotheke','Apotheke','noun','اسم','A1','داروخانه','از مکان‌های خدماتی پایه در عبارت‌نامه است.',TRUE,'blocked_until_level_final'),
('lex-de-verstehen',@de,'word','verstehen','verstehen','verstehen','verb','فعل','A1','فهمیدن','برای گفتن اینکه چیزی را نمی‌فهمیم استفاده می‌شود.',TRUE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE language_id=VALUES(language_id),lexeme_type=VALUES(lexeme_type),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),lemma=VALUES(lemma),part_of_speech=VALUES(part_of_speech),part_of_speech_fa=VALUES(part_of_speech_fa),cefr_level=VALUES(cefr_level),translation_fa=VALUES(translation_fa),usage_note_fa=VALUES(usage_note_fa),flashcard_eligible=VALUES(flashcard_eligible);
SET @x_langsam=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-langsam'); SET @x_noch=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-noch-einmal'); SET @x_telefon=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-telefon'); SET @x_benutzen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-benutzen'); SET @x_apotheke=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-apotheke'); SET @x_verstehen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-verstehen'); SET @x_hilfe=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-hilfe'); SET @x_toilette=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-toilette'); SET @x_sprechen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-sprechen'); SET @x_englisch=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-englisch');

INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-clarify-permission-help',@level,@unit,14,1,'لطفاً یک بار دیگر، آهسته','Noch einmal, bitte langsam. / Kann ich Ihr Telefon benutzen?','یک بار دیگر، لطفاً آهسته / می‌توانم از تلفن شما استفاده کنم؟','draft','گفت‌وگو درخواست تکرار را در بافت واقعی تمرین می‌کند؛ سپس اجازهٔ استفاده از تلفن، درخواست کمک، واژگان خدمات و در پایان بازسازی عبارت تکرار پوشش داده می‌شوند.','درس از یک مشکل فهم واقعی به تشخیص اجازه و کمک، تثبیت واژگان خدمات و بازیابی فعال درخواست روشن‌سازی حرکت می‌کند.','conversation_speaking>multiple_choice>choose_response>matching>word_order','blocked_until_level_final','یک درس پنج‌فعالیتی برای پوشش روشن‌سازی، اجازه و کمک مشخص کافی است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),source_title=VALUES(source_title),source_title_fa=VALUES(source_title_fa),status=VALUES(status),activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),notes=VALUES(notes);
SET @lesson=(SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-clarify-permission-help');
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role) VALUES(@lesson,@t_help,'introduce'),(@lesson,@t_sit,'introduce'),(@lesson,@t_modal,'practice'),(@lesson,@t_reg,'practice'),(@lesson,@t_core,'introduce');
INSERT IGNORE INTO lesson_lexemes(lesson_id,lexeme_id,is_primary,role) VALUES(@lesson,@x_langsam,TRUE,'introduce'),(@lesson,@x_noch,TRUE,'introduce'),(@lesson,@x_telefon,TRUE,'introduce'),(@lesson,@x_benutzen,TRUE,'introduce'),(@lesson,@x_apotheke,TRUE,'introduce'),(@lesson,@x_verstehen,TRUE,'introduce'),(@lesson,@x_hilfe,FALSE,'review'),(@lesson,@x_toilette,FALSE,'review'),(@lesson,@x_sprechen,FALSE,'review'),(@lesson,@x_englisch,FALSE,'review');

INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-clarify-slowly',@level,'آیریس یک پرسش ساده به پاول می‌گوید؛ پاول درخواست می‌کند دوباره و آهسته‌تر گفته شود و آیریس همان پرسش منبع‌دار را تکرار می‌کند.','app','تکرار دقیق پرسش پس از درخواست «یک بار دیگر، لطفاً آهسته» بخشی طبیعی از خود سناریوی روشن‌سازی است. هیچ جملهٔ آلمانی تازه ساخته نشده و دو منبع فقط در یک تعامل کوتاه کنار هم قرار گرفته‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dialogue=(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-clarify-slowly');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-service-1',@dialogue,1,@iris,'app_assigned','unspecified','Sprechen Sie Englisch?','انگلیسی صحبت می‌کنید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-service-2',@dialogue,2,@paul,'app_assigned','unspecified','Wie bitte? Noch einmal, bitte langsam.','ببخشید؟ یک بار دیگر، لطفاً آهسته.',TRUE,'blocked_until_level_final'),
('turn-de-a1-service-3',@dialogue,3,@iris,'app_assigned','unspecified','Sprechen Sie Englisch?','انگلیسی صحبت می‌کنید؟',FALSE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);

INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-service-conversation',@lesson,1,'conversation_speaking','اگر پرسش را نفهمیدی، بخواه یک بار دیگر و آهسته گفته شود.','سه نوبت منبع‌دار یک چرخهٔ طبیعی پرسش، درخواست تکرار و تکرار همان پرسش را می‌سازند.',@dialogue,JSON_OBJECT('interaction','read_aloud_exchange','openingInitiator','app'),JSON_ARRAY('other','persian_translation_added','character_metadata_added'),NULL,'not_required'),
('act-de-a1-phone-permission-choice',@lesson,2,'multiple_choice','کدام عبارت برای اجازه گرفتنِ استفاده از تلفن است؟','شکل رسمی از گزینهٔ رسمی منبع انتخاب شده و با دو پرسش خدماتی دیگر مقایسه می‌شود.',NULL,JSON_OBJECT('options',JSON_ARRAY(JSON_OBJECT('textTarget','Kann ich Ihr Telefon benutzen?','translationFa','می‌توانم از تلفن شما استفاده کنم؟','correct',TRUE),JSON_OBJECT('textTarget','Wo ist die Toilette, bitte?','translationFa','سرویس بهداشتی کجاست، لطفاً؟','correct',FALSE),JSON_OBJECT('textTarget','Sprechen Sie Englisch?','translationFa','انگلیسی صحبت می‌کنید؟','correct',FALSE))),JSON_ARRAY('options_selected_from_source_material','other','persian_translation_added'),NULL,'not_required'),
('act-de-a1-specific-help-response',@lesson,3,'choose_response','در پاسخ به «چه چیزی لازم دارید؟» کدام جمله مستقیم می‌گوید به کمک نیاز داری؟','عبارت رسمی درخواست کمک از منبع خدمات با دو عبارت نامرتبط همان منبع مقایسه می‌شود.',NULL,JSON_OBJECT('promptTarget','Was brauchen Sie?','promptFa','چه چیزی لازم دارید؟','options',JSON_ARRAY(JSON_OBJECT('textTarget','Ich brauche Ihre Hilfe.','translationFa','به کمک شما نیاز دارم.','correct',TRUE),JSON_OBJECT('textTarget','Ich verstehe das nicht.','translationFa','این را نمی‌فهمم.','correct',FALSE),JSON_OBJECT('textTarget','Wo ist die Toilette, bitte?','translationFa','سرویس بهداشتی کجاست، لطفاً؟','correct',FALSE))),JSON_ARRAY('options_selected_from_source_material','other','persian_translation_added'),NULL,'not_required'),
('act-de-a1-service-words-matching',@lesson,4,'matching','هر واژهٔ خدماتی را به معنی درستش وصل کن.','دو واژهٔ آشنا و دو واژهٔ تازه در یک شبکهٔ خدمات روزمره تثبیت می‌شوند.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','Hilfe','leftFa','کمک','right','کمک','rightFa','کمک'),JSON_OBJECT('left','Telefon','leftFa','تلفن','right','تلفن','rightFa','تلفن'),JSON_OBJECT('left','Toilette','leftFa','سرویس بهداشتی','right','سرویس بهداشتی','rightFa','سرویس بهداشتی'),JSON_OBJECT('left','Apotheke','leftFa','داروخانه','right','داروخانه','rightFa','داروخانه'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-repeat-slowly-order',@lesson,5,'word_order','درخواست تکرار و آهسته‌تر گفتن را دوباره بساز.','عبارت کلیدی گفت‌وگو در پایان به بازیابی فعال منتقل می‌شود.',NULL,JSON_OBJECT('sourceText','Wie bitte? Noch einmal, bitte langsam.','sourceTextFa','ببخشید؟ یک بار دیگر، لطفاً آهسته.','tokens',JSON_ARRAY('Wie','bitte?','Noch','einmal,','bitte','langsam.'),'answer',JSON_ARRAY('Wie','bitte?','Noch','einmal,','bitte','langsam.')),JSON_ARRAY('sentence_tokenized_for_word_order','persian_translation_added'),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
SET @a1=(SELECT id FROM activities WHERE activity_key='act-de-a1-service-conversation'); SET @a2=(SELECT id FROM activities WHERE activity_key='act-de-a1-phone-permission-choice'); SET @a3=(SELECT id FROM activities WHERE activity_key='act-de-a1-specific-help-response'); SET @a4=(SELECT id FROM activities WHERE activity_key='act-de-a1-service-words-matching'); SET @a5=(SELECT id FROM activities WHERE activity_key='act-de-a1-repeat-slowly-order');
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) VALUES(@a1,@t_help),(@a1,@t_sit),(@a2,@t_help),(@a2,@t_modal),(@a2,@t_reg),(@a3,@t_help),(@a3,@t_sit),(@a4,@t_sit),(@a4,@t_core),(@a5,@t_help);
INSERT IGNORE INTO activity_lexemes(activity_id,lexeme_id) VALUES(@a1,@x_langsam),(@a1,@x_noch),(@a1,@x_sprechen),(@a1,@x_englisch),(@a2,@x_telefon),(@a2,@x_benutzen),(@a2,@x_toilette),(@a2,@x_englisch),(@a3,@x_hilfe),(@a3,@x_verstehen),(@a3,@x_toilette),(@a4,@x_hilfe),(@a4,@x_telefon),(@a4,@x_toilette),(@a4,@x_apotheke),(@a5,@x_langsam),(@a5,@x_noch);

INSERT INTO lexeme_occurrences(occurrence_key,owner_type,owner_key,surface,start_offset,end_offset,lexeme_id,lexeme_form_id,resolution_status,resolution_notes) VALUES
('occ-turn-de-a1-service-1-sprechen','dialogue_turn','turn-de-a1-service-1','Sprechen',NULL,NULL,@x_sprechen,NULL,'approved','اتصال فعل صحبت کردن تأیید شده است.'),
('occ-turn-de-a1-service-1-englisch','dialogue_turn','turn-de-a1-service-1','Englisch',NULL,NULL,@x_englisch,NULL,'approved','اتصال زبان انگلیسی تأیید شده است.'),
('occ-turn-de-a1-service-2-noch','dialogue_turn','turn-de-a1-service-2','Noch einmal',NULL,NULL,@x_noch,NULL,'approved','اتصال عبارت دوباره تأیید شده است.'),
('occ-turn-de-a1-service-2-langsam','dialogue_turn','turn-de-a1-service-2','langsam',NULL,NULL,@x_langsam,NULL,'approved','اتصال آهسته تأیید شده است.'),
('occ-turn-de-a1-service-3-sprechen','dialogue_turn','turn-de-a1-service-3','Sprechen',NULL,NULL,@x_sprechen,NULL,'approved','تکرار همان پرسش منبع‌دار است.'),
('occ-turn-de-a1-service-3-englisch','dialogue_turn','turn-de-a1-service-3','Englisch',NULL,NULL,@x_englisch,NULL,'approved','تکرار همان پرسش منبع‌دار است.')
ON DUPLICATE KEY UPDATE owner_type=VALUES(owner_type),owner_key=VALUES(owner_key),surface=VALUES(surface),lexeme_id=VALUES(lexeme_id),lexeme_form_id=VALUES(lexeme_form_id),resolution_status=VALUES(resolution_status),resolution_notes=VALUES(resolution_notes);

SET @repeat=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-repeat'); SET @english=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-english'); SET @understand=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-understand'); SET @toilet=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-toilet'); SET @help=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-help'); SET @phone=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-phone'); SET @apo=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-service-apotheke'); SET @needq=(SELECT id FROM source_items WHERE item_key='srcitem-de-u3-need-question');
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES
('dialogue_turn','turn-de-a1-service-1',@english,'verbatim','متن هدف عین منبع است.'),
('dialogue_turn','turn-de-a1-service-2',@repeat,'verbatim','متن هدف عین منبع است.'),
('dialogue_turn','turn-de-a1-service-3',@english,'verbatim','پرسش عین منبع برای پاسخ به درخواست تکرار دوباره استفاده شده است.'),
('lexeme','lex-de-langsam',@repeat,'other','قید از عبارت منبع استخراج شده است.'),
('lexeme','lex-de-noch-einmal',@repeat,'other','عبارت از جملهٔ منبع استخراج شده است.'),
('lexeme','lex-de-telefon',@phone,'other','واژه از پرسش منبع استخراج شده است.'),
('lexeme','lex-de-benutzen',@phone,'other','فعل از پرسش منبع استخراج شده است.'),
('lexeme','lex-de-apotheke',@apo,'verbatim','واژه عین منبع ثبت شده است.'),
('lexeme','lex-de-verstehen',@understand,'other','فعل از جملهٔ منبع استخراج شده است.'),
('activity','act-de-a1-phone-permission-choice',@phone,'other','شکل رسمی Ihr از گزینهٔ رسمی منبع انتخاب شده است.'),
('activity','act-de-a1-phone-permission-choice',@toilet,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),
('activity','act-de-a1-phone-permission-choice',@english,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),
('activity','act-de-a1-specific-help-response',@needq,'options_selected_from_source_material','پرسش فعالیت عین منبع ثبت‌شدهٔ پیشین است.'),
('activity','act-de-a1-specific-help-response',@help,'other','شکل رسمی Ihre از گزینهٔ رسمی منبع انتخاب شده است.'),
('activity','act-de-a1-specific-help-response',@understand,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),
('activity','act-de-a1-specific-help-response',@toilet,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),
('activity','act-de-a1-service-words-matching',@help,'source_items_grouped_for_matching','واژهٔ کمک از عبارت منبع استخراج شده است.'),
('activity','act-de-a1-service-words-matching',@phone,'source_items_grouped_for_matching','واژهٔ تلفن از پرسش منبع استخراج شده است.'),
('activity','act-de-a1-service-words-matching',@toilet,'source_items_grouped_for_matching','واژهٔ سرویس بهداشتی از پرسش منبع استخراج شده است.'),
('activity','act-de-a1-service-words-matching',@apo,'source_items_grouped_for_matching','واژهٔ داروخانه عین منبع است.'),
('activity','act-de-a1-repeat-slowly-order',@repeat,'sentence_tokenized_for_word_order','عبارت عین منبع برای مرتب‌سازی بخش‌بندی شده است.');

UPDATE language_levels SET coverage=JSON_SET(coverage,'$.gaps[2]','نه واحد نخست به بازبینی رسیده‌اند؛ مرحلهٔ بعد پیام، فرم، اعلان و جمع‌بندی A1 است.'),notes='A1 همچنان در مرحلهٔ ساخت تدریجی است. نه واحد نخست در بازبینی‌اند. مرحلهٔ بعد پیام، فرم، اعلان و جمع‌بندی A1 است؛ درخواست تکرار، اجازهٔ ساده و کمک مشخص در واحد خدمات پوشش داده شده‌اند.' WHERE id=@level;
COMMIT;