-- German A1 Unit 10 — personal forms, common signs and short phone messages.
-- Base content never overwrites generated audio state.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);
SET @iris := (SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1);
SET @paul := (SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-007-form-spelling','Deutschkurs für Anfänger/Lektion 007','هجی‌کردن و اطلاعات فرم شخصی','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_007','Items 294, 297, 298 and 304: alphabet groups, spelling language, personal-form labels and example values.','بخش‌های ۲۹۴، ۲۹۷، ۲۹۸ و ۳۰۴؛ الفبا، هجی‌کردن، برچسب‌های فرم و مثال‌های اطلاعات شخصی.','2025-01-04','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ دوباره بررسی شد و آخرین ویرایش ثبت‌شدهٔ آن ۴ ژانویهٔ ۲۰۲۵ است. بخش‌های انتخاب‌شده فقط حروف الفبا، هجی‌کردن و برچسب‌های اطلاعات شخصی را پوشش می‌دهند و در بازبینی فعلی طبیعی و قابل‌استفاده‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 007','reuse_with_attribution','2026-09-18','استفاده به بخش‌های ۲۹۴، ۲۹۷، ۲۹۸ و ۳۰۴ محدود است. مثال‌های نام، نام خانوادگی، نام خیابان و شهر فقط در فعالیت هدایت‌شدهٔ فرم استفاده می‌شوند.'),
('src-wikivoyage-german-phrasebook-signs','German phrasebook — Common signs','تابلوهای بسیار کوتاه روزمره','Wikivoyage contributors','de','website','https://en.wikivoyage.org/wiki/German_phrasebook','Basics — Common signs: open, closed, entrance and exit.','بخش تابلوهای رایج؛ باز، بسته، ورودی و خروجی.',NULL,'maintained_current','بخش تابلوهای رایج در عبارت‌نامهٔ آلمانی ویکی‌ویاژ در ۱۸ سپتامبر ۲۰۲۶ بررسی شد. چهار تابلوی انتخاب‌شده در نسخهٔ فعلی صفحه حضور دارند و برای خواندن متن‌های بسیار کوتاه روزمره مناسب‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikivoyage contributors — German phrasebook','reuse_with_attribution','2026-09-18','فقط چهار تابلوی بسیار پرتکرار مربوط به بازبودن، بسته‌بودن، ورودی و خروجی وارد این واحد می‌شوند.'),
('src-wikibooks-de-lesson-024-short-messages','Deutschkurs für Anfänger/Lektion 024','پیام کوتاه تماس و هماهنگی','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_024','Items 1007 and 1010: callback messages and short coordination question-answer pairs.','بخش‌های ۱۰۰۷ و ۱۰۱۰؛ پیام‌های تماس و پرسش‌وپاسخ کوتاه برای هماهنگی.','2024-12-04','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ دوباره بررسی شد و آخرین ویرایش ثبت‌شدهٔ آن ۴ دسامبر ۲۰۲۴ است. پیام‌های تماس و جفت‌های کوتاه هماهنگی انتخاب‌شده در بازبینی فعلی طبیعی و مناسب ارتباط روزمره‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 024','reuse_with_attribution','2026-09-18','استفاده به بخش‌های ۱۰۰۷ و ۱۰۱۰ محدود است. پیام‌های کوتاه تماس برای شنیدن، خواندن و بازسازی هدایت‌شده به کار می‌روند؛ بخش‌های دستوری پیشرفته‌تر صفحه وارد این سطح نمی‌شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
SET @s_form := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-007-form-spelling');
SET @s_sign := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-signs');
SET @s_msg := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-024-short-messages');

INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@s_form,'srcitem-de-a1-form-vorname','304','بخش ۳۰۴','Vorname',UNHEX(SHA2('Vorname',256)),'برچسب نام کوچک.'),
(@s_form,'srcitem-de-a1-form-familienname','Vocabulary','واژگان درس','Familienname',UNHEX(SHA2('Familienname',256)),'برچسب نام خانوادگی.'),
(@s_form,'srcitem-de-a1-form-adresse','304','بخش ۳۰۴','Adresse',UNHEX(SHA2('Adresse',256)),'برچسب نشانی.'),
(@s_form,'srcitem-de-a1-form-stadt','304','بخش ۳۰۴','Stadt',UNHEX(SHA2('Stadt',256)),'برچسب شهر.'),
(@s_form,'srcitem-de-a1-form-example-first','298','بخش ۲۹۸','Buchstabieren Sie Ihren Vornamen. (Marcus)',UNHEX(SHA2('Buchstabieren Sie Ihren Vornamen. (Marcus)',256)),'نمونهٔ نام کوچک.'),
(@s_form,'srcitem-de-a1-form-example-family','298','بخش ۲۹۸','Buchstabieren Sie Ihren Familiennamen. (Clinton)',UNHEX(SHA2('Buchstabieren Sie Ihren Familiennamen. (Clinton)',256)),'نمونهٔ نام خانوادگی.'),
(@s_form,'srcitem-de-a1-form-example-street','298','بخش ۲۹۸','Buchstabieren Sie den Straßennamen ihrer Adresse. (Hauptstraße)',UNHEX(SHA2('Buchstabieren Sie den Straßennamen ihrer Adresse. (Hauptstraße)',256)),'نمونهٔ نام خیابان.'),
(@s_form,'srcitem-de-a1-form-example-city','298','بخش ۲۹۸','Buchstabieren Sie den Namen der Stadt. (Werdau)',UNHEX(SHA2('Buchstabieren Sie den Namen der Stadt. (Werdau)',256)),'نمونهٔ شهر.'),
(@s_form,'srcitem-de-a1-form-alpha-1','294','بخش ۲۹۴','A B C D E F',UNHEX(SHA2('A B C D E F',256)),'گروه حروف.'),
(@s_form,'srcitem-de-a1-form-alpha-2','294','بخش ۲۹۴','G H I J K L',UNHEX(SHA2('G H I J K L',256)),'گروه حروف.'),
(@s_form,'srcitem-de-a1-form-alpha-3','294','بخش ۲۹۴','M N O P Q',UNHEX(SHA2('M N O P Q',256)),'گروه حروف.'),
(@s_form,'srcitem-de-a1-form-alpha-4','294','بخش ۲۹۴','R S T',UNHEX(SHA2('R S T',256)),'گروه حروف.'),
(@s_form,'srcitem-de-a1-form-alpha-5','294','بخش ۲۹۴','U V W',UNHEX(SHA2('U V W',256)),'گروه حروف.'),
(@s_form,'srcitem-de-a1-form-alpha-6','294','بخش ۲۹۴','X Y Z',UNHEX(SHA2('X Y Z',256)),'گروه حروف.'),
(@s_sign,'srcitem-de-a1-sign-open','Common signs','تابلوهای رایج','Offen',UNHEX(SHA2('Offen',256)),'تابلوی باز.'),
(@s_sign,'srcitem-de-a1-sign-closed','Common signs','تابلوهای رایج','Geschlossen',UNHEX(SHA2('Geschlossen',256)),'تابلوی بسته.'),
(@s_sign,'srcitem-de-a1-sign-entrance','Common signs','تابلوهای رایج','Eingang',UNHEX(SHA2('Eingang',256)),'تابلوی ورودی.'),
(@s_sign,'srcitem-de-a1-sign-exit','Common signs','تابلوهای رایج','Ausgang',UNHEX(SHA2('Ausgang',256)),'تابلوی خروجی.'),
(@s_msg,'srcitem-de-a1-msg-q-call','1010','بخش ۱۰۱۰','Können Sie mich morgen noch einmal anrufen?',UNHEX(SHA2('Können Sie mich morgen noch einmal anrufen?',256)),'پرسش تماس دوباره.'),
(@s_msg,'srcitem-de-a1-msg-a-call','1010','پاسخ ۱۰۱۰','Ja, ich rufe Sie morgen noch einmal an.',UNHEX(SHA2('Ja, ich rufe Sie morgen noch einmal an.',256)),'پاسخ تماس دوباره.'),
(@s_msg,'srcitem-de-a1-msg-q-pickup','1010','بخش ۱۰۱۰','Möchten Sie die Karten morgen abholen?',UNHEX(SHA2('Möchten Sie die Karten morgen abholen?',256)),'پرسش تحویل گرفتن.'),
(@s_msg,'srcitem-de-a1-msg-a-pickup','1010','پاسخ ۱۰۱۰','Ja, ich möchte sie morgen abholen.',UNHEX(SHA2('Ja, ich möchte sie morgen abholen.',256)),'پاسخ تحویل گرفتن.'),
(@s_msg,'srcitem-de-a1-msg-monday','1007','پاسخ ۱۰۰۷','Rufen Sie bitte am Montag noch einmal an.',UNHEX(SHA2('Rufen Sie bitte am Montag noch einmal an.',256)),'پیام تماس دوشنبه.'),
(@s_msg,'srcitem-de-a1-msg-evening','1007','پاسخ ۱۰۰۷','Rufen Sie bitte heute Abend noch einmal an.',UNHEX(SHA2('Rufen Sie bitte heute Abend noch einmal an.',256)),'پیام تماس امشب.'),
(@s_msg,'srcitem-de-a1-msg-day-after','1007','پاسخ ۱۰۰۷','Rufen Sie bitte übermorgen noch einmal an.',UNHEX(SHA2('Rufen Sie bitte übermorgen noch einmal an.',256)),'پیام تماس پس‌فردا.'),
(@s_msg,'srcitem-de-a1-msg-ten','1007','پاسخ ۱۰۰۷','Rufen Sie bitte um zehn noch einmal an.',UNHEX(SHA2('Rufen Sie bitte um zehn noch einmal an.',256)),'پیام تماس ساعت ده.'),
(@s_msg,'srcitem-de-a1-msg-afternoon','1007','پاسخ ۱۰۰۷','Rufen Sie bitte am Nachmittag noch einmal an.',UNHEX(SHA2('Rufen Sie bitte am Nachmittag noch einmal an.',256)),'پیام تماس بعدازظهر.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);

INSERT INTO units(unit_key,language_level_id,sequence_index,title_fa,grouping_rationale,status,metadata,notes) VALUES
('de-a1-unit-forms-signs-messages',@level,10,'فرم، تابلو و پیام کوتاه','واحد پایانی مهارت‌های کوتاه اما واقعی بیرون از گفت‌وگوی آزاد را کنار هم می‌آورد: فرم و هجی‌کردن، تابلوهای محیطی و پیام تماس. دو درس جدا نگه داشته شده‌اند چون خواندن و تکمیل فرم با دریافت و تولید پیام کوتاه نیازهای متفاوتی دارند.','review',JSON_OBJECT('sourceRefs',JSON_ARRAY('src-wikibooks-de-residence-origin','src-wikibooks-de-lesson-007-form-spelling','src-wikivoyage-german-phrasebook-signs','src-wikibooks-de-lesson-024-short-messages'),'learningTargets',JSON_ARRAY('فرم و اطلاعات شخصی','تابلوهای کوتاه','هجی و وضوح حروف','پیام کوتاه شنیداری','بازسازی پیام کوتاه')),'بازبینی پوشش انجام شد. درس نخست فرم، تابلو و تلفظ حروف را پوشش می‌دهد؛ درس دوم گفت‌وگوی هماهنگی، پیام شنیداری، خواندن پیام و بازسازی نوشتاری را اضافه می‌کند. مرحلهٔ بعد بررسی پوشش کل سطح و رفع شکاف‌های واقعی پیش از تغییر وضعیت A1 است.')
ON DUPLICATE KEY UPDATE sequence_index=VALUES(sequence_index),title_fa=VALUES(title_fa),grouping_rationale=VALUES(grouping_rationale),status=IF(status='final',status,VALUES(status)),metadata=VALUES(metadata),notes=VALUES(notes);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-forms-signs-messages');

SET @t_listen_dialogue := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-listening-dialogue');
SET @t_listen_msg := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-listening-message-announcement');
SET @t_read := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-reading-short-texts');
SET @t_write := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-writing-form-message');
SET @t_spoken := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-spoken-questions-requests');
SET @t_short := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-sit-short-messages');
SET @t_core := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-core-vocabulary');
SET @t_word := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-basic-word-order');
SET @t_time := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-numbers-dates-time');
SET @t_pron := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-pron-intelligibility');
INSERT IGNORE INTO unit_targets(unit_id,curriculum_target_id) VALUES
(@unit,@t_listen_dialogue),(@unit,@t_listen_msg),(@unit,@t_read),(@unit,@t_write),(@unit,@t_spoken),(@unit,@t_short),(@unit,@t_core),(@unit,@t_word),(@unit,@t_time),(@unit,@t_pron);

INSERT INTO lexemes(lexeme_key,language_id,lexeme_type,surface,normalized_surface,lemma,part_of_speech,part_of_speech_fa,cefr_level,translation_fa,usage_note_fa,flashcard_eligible,audio_status) VALUES
('lex-de-vorname',@de,'word','Vorname','Vorname','Vorname','noun','اسم','A1','نام کوچک','در فرم‌های سادهٔ اطلاعات شخصی برای نام کوچک استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-familienname',@de,'word','Familienname','Familienname','Familienname','noun','اسم','A1','نام خانوادگی','در فرم‌های سادهٔ اطلاعات شخصی برای نام خانوادگی استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-stadt',@de,'word','Stadt','Stadt','Stadt','noun','اسم','A1','شهر','در فرم و نشانی برای نام شهر استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-buchstabieren',@de,'word','buchstabieren','buchstabieren','buchstabieren','verb','فعل','A1','هجی کردن','برای گفتن حروف نام، نام خانوادگی و نشانی استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-offen',@de,'word','Offen','Offen','offen','adjective','صفت','A1','باز','روی تابلوی کوتاه برای نشان‌دادن باز بودن مکان استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-geschlossen',@de,'word','Geschlossen','Geschlossen','geschlossen','adjective','صفت','A1','بسته','روی تابلوی کوتاه برای نشان‌دادن بسته بودن مکان استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-eingang',@de,'word','Eingang','Eingang','Eingang','noun','اسم','A1','ورودی','روی تابلوی کوتاه برای مشخص‌کردن ورودی استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-ausgang',@de,'word','Ausgang','Ausgang','Ausgang','noun','اسم','A1','خروجی','روی تابلوی کوتاه برای مشخص‌کردن خروجی استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-anrufen',@de,'word','anrufen','anrufen','anrufen','verb','فعل','A1','تماس گرفتن','در پیام‌های کوتاه برای درخواست تماس دوباره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-montag',@de,'word','Montag','Montag','Montag','noun','اسم','A1','دوشنبه','در پیام تماس برای تعیین روز تماس دوباره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-nachmittag',@de,'word','Nachmittag','Nachmittag','Nachmittag','noun','اسم','A1','بعدازظهر','در پیام تماس برای تعیین زمان تماس دوباره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-uebermorgen',@de,'word','übermorgen','übermorgen','übermorgen','adverb','قید','A1','پس‌فردا','در پیام کوتاه برای تعیین روز تماس دوباره استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-morgen-adverb',@de,'word','morgen','morgen','morgen','adverb','قید','A1','فردا','این مدخل از «Morgen» به معنی صبح جداست و در هماهنگی برنامه به معنی فردا استفاده می‌شود.',TRUE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE language_id=VALUES(language_id),lexeme_type=VALUES(lexeme_type),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),lemma=VALUES(lemma),part_of_speech=VALUES(part_of_speech),part_of_speech_fa=VALUES(part_of_speech_fa),cefr_level=VALUES(cefr_level),translation_fa=VALUES(translation_fa),usage_note_fa=VALUES(usage_note_fa),flashcard_eligible=VALUES(flashcard_eligible);

SET @x_vorname=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-vorname'); SET @x_familienname=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-familienname'); SET @x_adresse=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-adresse'); SET @x_stadt=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-stadt'); SET @x_buch=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-buchstabieren'); SET @x_offen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-offen'); SET @x_geschlossen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-geschlossen'); SET @x_eingang=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-eingang'); SET @x_ausgang=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-ausgang'); SET @x_wohnen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-wohnen'); SET @x_oesterreich=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-oesterreich');
SET @x_anrufen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-anrufen'); SET @x_montag=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-montag'); SET @x_nachmittag=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-nachmittag'); SET @x_uebermorgen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-uebermorgen'); SET @x_morgen_adv=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-morgen-adverb'); SET @x_noch=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-noch-einmal'); SET @x_moegen=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-moegen'); SET @x_ja=(SELECT id FROM lexemes WHERE lexeme_key='lex-de-ja');
SET @f_moechten=(SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-moegen-moechten'); SET @f_moechte=(SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-moegen-moechte');

INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-personal-form-signs',@level,@unit,15,1,'فرم را پر کن، تابلو را بخوان','Vorname / Familienname / Adresse / Stadt — common signs','نام کوچک، نام خانوادگی، نشانی، شهر و تابلوهای رایج','draft','درس با بازیابی اطلاعات شخصی شروع می‌شود؛ سپس برچسب‌های فرم، تکمیل یک فیلد واقعی، خواندن چهار تابلوی کوتاه و در پایان خواندن حروف برای هجی‌کردن تمرین می‌شوند.','ترتیب از تعامل آشنا به خواندن فرم، تولید هدایت‌شده، خواندن متن محیطی و سپس وضوح تلفظ حروف حرکت می‌کند.','conversation_speaking>matching>fill_blank>matching>pronunciation_read','blocked_until_level_final','درس نخست واحد پایانی، فرم و تابلو و هجی را در یک مسیر کاربردی ترکیب می‌کند.'),
('de-a1-lesson-short-phone-message',@level,@unit,16,2,'لطفاً دوشنبه دوباره تماس بگیرید','Rufen Sie bitte am Montag noch einmal an.','لطفاً دوشنبه دوباره تماس بگیرید','draft','گفت‌وگو هماهنگی کوتاه را می‌سازد؛ سپس یک پیام مستقل شنیده می‌شود، چهار پیام زمانی خوانده و تطبیق داده می‌شوند و در پایان یک پیام دیگر بازسازی می‌شود.','درس از تعامل به دریافت شنیداری، سپس خواندن چند نمونه و در پایان تولید هدایت‌شدهٔ پیام کوتاه حرکت می‌کند.','conversation_speaking>listen_choose>matching>word_order','blocked_until_level_final','درس دوم واحد پایانی، پیام کوتاه را در دریافت شنیداری، خواندن و تولید هدایت‌شده پوشش می‌دهد.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),source_title=VALUES(source_title),source_title_fa=VALUES(source_title_fa),status=VALUES(status),activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),notes=VALUES(notes);
SET @l1=(SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-personal-form-signs'); SET @l2=(SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-short-phone-message');

INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role) VALUES
(@l1,@t_listen_dialogue,'review'),(@l1,@t_read,'introduce'),(@l1,@t_write,'introduce'),(@l1,@t_spoken,'practice'),(@l1,@t_core,'practice'),(@l1,@t_pron,'introduce'),
(@l2,@t_listen_dialogue,'practice'),(@l2,@t_listen_msg,'introduce'),(@l2,@t_read,'practice'),(@l2,@t_write,'practice'),(@l2,@t_short,'introduce'),(@l2,@t_word,'practice'),(@l2,@t_time,'practice');
INSERT IGNORE INTO lesson_lexemes(lesson_id,lexeme_id,is_primary,role) VALUES
(@l1,@x_vorname,TRUE,'introduce'),(@l1,@x_familienname,TRUE,'introduce'),(@l1,@x_adresse,FALSE,'review'),(@l1,@x_stadt,TRUE,'introduce'),(@l1,@x_buch,TRUE,'introduce'),(@l1,@x_offen,TRUE,'introduce'),(@l1,@x_geschlossen,TRUE,'introduce'),(@l1,@x_eingang,TRUE,'introduce'),(@l1,@x_ausgang,TRUE,'introduce'),(@l1,@x_wohnen,FALSE,'review'),
(@l2,@x_anrufen,TRUE,'introduce'),(@l2,@x_montag,TRUE,'introduce'),(@l2,@x_nachmittag,TRUE,'introduce'),(@l2,@x_uebermorgen,TRUE,'introduce'),(@l2,@x_morgen_adv,TRUE,'introduce'),(@l2,@x_noch,FALSE,'review'),(@l2,@x_moegen,FALSE,'review'),(@l2,@x_ja,FALSE,'review');

INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-personal-form-review',@level,'آیریس در یک ثبت‌نام کوتاه اطلاعات پایهٔ پاول را مرور می‌کند: سلام، نام و محل زندگی.','app','شش نوبت عین نمونه‌های منبع‌دار سطح پیشین‌اند و فقط در یک موقعیت ثبت‌نام کوتاه دوباره کنار هم قرار گرفته‌اند؛ هیچ متن آلمانی تازه‌ای برای فرم ساخته نشده است.'),
('dlg-de-a1-short-message-coordination',@level,'آیریس و پاول در یک تماس کوتاه دو کار را هماهنگ می‌کنند: تماس دوباره برای فردا و گرفتن کارت‌ها در فردا.','app','چهار نوبت از دو جفت پرسش‌وپاسخ مجاور بخش ۱۰۱۰ عیناً حفظ شده‌اند و به‌عنوان دو کار کوتاه در یک تماس هماهنگی کنار هم قرار گرفته‌اند. نقش شخصیت‌ها افزوده شده اما متن آلمانی تغییر نکرده است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @d1=(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-personal-form-review'); SET @d2=(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-short-message-coordination');

INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-form-1',@d1,1,@iris,'app_assigned','unspecified','Guten Tag!','سلام / روز بخیر!',FALSE,'blocked_until_level_final'),
('turn-de-a1-form-2',@d1,2,@paul,'app_assigned','unspecified','Guten Tag!','سلام / روز بخیر!',TRUE,'blocked_until_level_final'),
('turn-de-a1-form-3',@d1,3,@iris,'app_assigned','unspecified','Wie heißen Sie?','اسمتان چیست؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-form-4',@d1,4,@paul,'app_assigned','unspecified','Ich heiße Paul Müller.','اسم من پاول مولر است.',TRUE,'blocked_until_level_final'),
('turn-de-a1-form-5',@d1,5,@iris,'app_assigned','unspecified','Wo wohnen Sie?','کجا زندگی می‌کنید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-form-6',@d1,6,@paul,'app_assigned','unspecified','Ich wohne in Österreich.','من در اتریش زندگی می‌کنم.',TRUE,'blocked_until_level_final'),
('turn-de-a1-message-1',@d2,1,@iris,'app_assigned','unspecified','Können Sie mich morgen noch einmal anrufen?','می‌توانید فردا دوباره با من تماس بگیرید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-message-2',@d2,2,@paul,'app_assigned','unspecified','Ja, ich rufe Sie morgen noch einmal an.','بله، فردا دوباره با شما تماس می‌گیرم.',TRUE,'blocked_until_level_final'),
('turn-de-a1-message-3',@d2,3,@iris,'app_assigned','unspecified','Möchten Sie die Karten morgen abholen?','می‌خواهید فردا کارت‌ها را تحویل بگیرید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-message-4',@d2,4,@paul,'app_assigned','unspecified','Ja, ich möchte sie morgen abholen.','بله، می‌خواهم فردا آن‌ها را تحویل بگیرم.',TRUE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);

INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-form-conversation',@l1,1,'conversation_speaking','اطلاعات پایهٔ نام و محل زندگی را در یک ثبت‌نام کوتاه پاسخ بده.','گفت‌وگوی منبع‌دار سطح پیشین اطلاعاتی را بازیابی می‌کند که بلافاصله در فرم استفاده می‌شوند.',@d1,JSON_OBJECT('interaction','read_aloud_exchange','openingInitiator','app'),JSON_ARRAY('other','persian_translation_added','character_metadata_added'),NULL,'not_required'),
('act-de-a1-form-fields-matching',@l1,2,'matching','هر برچسب فرم را به معنی درستش وصل کن.','چهار برچسب مستقیم از بخش فرم و واژگان منبع انتخاب شده‌اند.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','Vorname','leftFa','نام کوچک','right','نام کوچک','rightFa','نام کوچک'),JSON_OBJECT('left','Familienname','leftFa','نام خانوادگی','right','نام خانوادگی','rightFa','نام خانوادگی'),JSON_OBJECT('left','Adresse','leftFa','نشانی','right','نشانی','rightFa','نشانی'),JSON_OBJECT('left','Stadt','leftFa','شهر','right','شهر','rightFa','شهر'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-form-first-name-fill',@l1,3,'fill_blank','فیلد نام کوچک را با نمونهٔ درست کامل کن.','چهار مقدار از مثال‌های هجی‌کردن همان بخش منبع گرفته شده‌اند و فقط یکی برای فیلد نام کوچک مناسب است.',NULL,JSON_OBJECT('blankedText','Vorname: ___','blankedTextFa','نام کوچک: ___','choices',JSON_ARRAY('Marcus','Clinton','Hauptstraße','Werdau'),'choicesFa',JSON_ARRAY('مارکوس','کلینتون','هاوپت‌اشتراسه','ورداو'),'answer','Marcus'),JSON_ARRAY('other','persian_translation_added'),NULL,'not_required'),
('act-de-a1-common-signs-matching',@l1,4,'matching','هر تابلوی کوتاه را به معنی درستش وصل کن.','چهار تابلوی بسیار پرتکرار از بخش تابلوهای رایج منبع انتخاب شده‌اند.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','Offen','leftFa','باز','right','باز','rightFa','باز'),JSON_OBJECT('left','Geschlossen','leftFa','بسته','right','بسته','rightFa','بسته'),JSON_OBJECT('left','Eingang','leftFa','ورودی','right','ورودی','rightFa','ورودی'),JSON_OBJECT('left','Ausgang','leftFa','خروجی','right','خروجی','rightFa','خروجی'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-alphabet-pronunciation',@l1,5,'pronunciation_read','گروه‌های حروف را واضح و با صدای بلند بخوان.','شش خط الفبا عین بخش ۲۹۴ هستند و تمرین تلفظ را مستقیماً به نیاز هجی‌کردن فرم وصل می‌کنند.',NULL,JSON_OBJECT('lines',JSON_ARRAY('A B C D E F','G H I J K L','M N O P Q','R S T','U V W','X Y Z'),'audioTextTargetFa','حروف الفبا در شش گروه.'),JSON_ARRAY('other'),CONCAT_WS(CHAR(10),'A B C D E F','G H I J K L','M N O P Q','R S T','U V W','X Y Z'),'blocked_until_level_final'),
('act-de-a1-message-conversation',@l2,1,'conversation_speaking','تماس دوباره و گرفتن کارت‌ها برای فردا را هماهنگ کن.','دو جفت پرسش‌وپاسخ مجاور منبع، یک هماهنگی کوتاه و قابل‌فهم می‌سازند.',@d2,JSON_OBJECT('interaction','read_aloud_exchange','openingInitiator','app'),JSON_ARRAY('other','persian_translation_added','character_metadata_added'),NULL,'not_required'),
('act-de-a1-message-listen-callback',@l2,2,'listen_choose','پیام را گوش کن و زمان تماس دوباره را انتخاب کن.','جملهٔ کامل بخش ۱۰۰۷ به‌عنوان پیام مستقل شنیداری استفاده می‌شود و زمان درست از سه عبارت منبع‌دار انتخاب می‌شود.',NULL,JSON_OBJECT('audioTextTargetFa','لطفاً دوشنبه دوباره تماس بگیرید.','options',JSON_ARRAY(JSON_OBJECT('text','am Montag','translationFa','دوشنبه','correct',TRUE),JSON_OBJECT('text','heute Abend','translationFa','امشب','correct',FALSE),JSON_OBJECT('text','übermorgen','translationFa','پس‌فردا','correct',FALSE))),JSON_ARRAY('options_selected_from_source_material','persian_translation_added'),'Rufen Sie bitte am Montag noch einmal an.','blocked_until_level_final'),
('act-de-a1-message-reading-matching',@l2,3,'matching','هر پیام کوتاه را به زمان درستش وصل کن.','چهار پیام کامل از بخش ۱۰۰۷ انتخاب شده‌اند تا خواندن متن کوتاه و استخراج زمان تمرین شود.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','Rufen Sie bitte am Montag noch einmal an.','leftFa','لطفاً دوشنبه دوباره تماس بگیرید.','right','دوشنبه','rightFa','دوشنبه'),JSON_OBJECT('left','Rufen Sie bitte heute Abend noch einmal an.','leftFa','لطفاً امشب دوباره تماس بگیرید.','right','امشب','rightFa','امشب'),JSON_OBJECT('left','Rufen Sie bitte übermorgen noch einmal an.','leftFa','لطفاً پس‌فردا دوباره تماس بگیرید.','right','پس‌فردا','rightFa','پس‌فردا'),JSON_OBJECT('left','Rufen Sie bitte um zehn noch einmal an.','leftFa','لطفاً ساعت ده دوباره تماس بگیرید.','right','ساعت ده','rightFa','ساعت ده'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-message-write-order',@l2,4,'word_order','پیام کوتاه تماس برای بعدازظهر را دوباره بساز.','یک پیام کامل دیگر از همان تمرین به تولید هدایت‌شده منتقل می‌شود تا فقط پیام شنیده‌شده تکرار نشود.',NULL,JSON_OBJECT('sourceText','Rufen Sie bitte am Nachmittag noch einmal an.','sourceTextFa','لطفاً بعدازظهر دوباره تماس بگیرید.','tokens',JSON_ARRAY('Rufen','Sie','bitte','am','Nachmittag','noch','einmal','an.'),'answer',JSON_ARRAY('Rufen','Sie','bitte','am','Nachmittag','noch','einmal','an.')),JSON_ARRAY('sentence_tokenized_for_word_order','persian_translation_added'),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);

SET @a11=(SELECT id FROM activities WHERE activity_key='act-de-a1-form-conversation'); SET @a12=(SELECT id FROM activities WHERE activity_key='act-de-a1-form-fields-matching'); SET @a13=(SELECT id FROM activities WHERE activity_key='act-de-a1-form-first-name-fill'); SET @a14=(SELECT id FROM activities WHERE activity_key='act-de-a1-common-signs-matching'); SET @a15=(SELECT id FROM activities WHERE activity_key='act-de-a1-alphabet-pronunciation');
SET @a21=(SELECT id FROM activities WHERE activity_key='act-de-a1-message-conversation'); SET @a22=(SELECT id FROM activities WHERE activity_key='act-de-a1-message-listen-callback'); SET @a23=(SELECT id FROM activities WHERE activity_key='act-de-a1-message-reading-matching'); SET @a24=(SELECT id FROM activities WHERE activity_key='act-de-a1-message-write-order');

INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) VALUES
(@a11,@t_listen_dialogue),(@a11,@t_spoken),(@a12,@t_read),(@a12,@t_write),(@a12,@t_core),(@a13,@t_write),(@a14,@t_read),(@a15,@t_pron),
(@a21,@t_listen_dialogue),(@a21,@t_spoken),(@a22,@t_listen_msg),(@a22,@t_time),(@a23,@t_read),(@a23,@t_short),(@a24,@t_write),(@a24,@t_word),(@a24,@t_short);
INSERT IGNORE INTO activity_lexemes(activity_id,lexeme_id) VALUES
(@a11,@x_wohnen),(@a12,@x_vorname),(@a12,@x_familienname),(@a12,@x_adresse),(@a12,@x_stadt),(@a13,@x_vorname),(@a14,@x_offen),(@a14,@x_geschlossen),(@a14,@x_eingang),(@a14,@x_ausgang),(@a15,@x_buch),
(@a21,@x_anrufen),(@a21,@x_morgen_adv),(@a21,@x_noch),(@a21,@x_moegen),(@a21,@x_ja),(@a22,@x_anrufen),(@a22,@x_montag),(@a22,@x_uebermorgen),(@a22,@x_noch),(@a23,@x_anrufen),(@a23,@x_montag),(@a23,@x_uebermorgen),(@a23,@x_noch),(@a24,@x_anrufen),(@a24,@x_nachmittag),(@a24,@x_noch);

INSERT INTO lexeme_occurrences(occurrence_key,owner_type,owner_key,surface,start_offset,end_offset,lexeme_id,lexeme_form_id,resolution_status,resolution_notes) VALUES
('occ-turn-de-a1-msg-1-morgen','dialogue_turn','turn-de-a1-message-1','morgen',NULL,NULL,@x_morgen_adv,NULL,'approved','قید فردا از مدخل صبح جدا ثبت شده است.'),
('occ-turn-de-a1-msg-1-noch','dialogue_turn','turn-de-a1-message-1','noch einmal',NULL,NULL,@x_noch,NULL,'approved','عبارت دوباره به مدخل موجود متصل است.'),
('occ-turn-de-a1-msg-1-anrufen','dialogue_turn','turn-de-a1-message-1','anrufen',NULL,NULL,@x_anrufen,NULL,'approved','مصدر فعل تماس گرفتن عین متن است.'),
('occ-turn-de-a1-msg-2-ja','dialogue_turn','turn-de-a1-message-2','Ja',NULL,NULL,@x_ja,NULL,'approved','پاسخ مثبت به مدخل موجود متصل است.'),
('occ-turn-de-a1-msg-2-morgen','dialogue_turn','turn-de-a1-message-2','morgen',NULL,NULL,@x_morgen_adv,NULL,'approved','قید فردا ثبت شده است.'),
('occ-turn-de-a1-msg-2-noch','dialogue_turn','turn-de-a1-message-2','noch einmal',NULL,NULL,@x_noch,NULL,'approved','عبارت دوباره ثبت شده است.'),
('occ-turn-de-a1-msg-3-moechten','dialogue_turn','turn-de-a1-message-3','Möchten',NULL,NULL,@x_moegen,@f_moechten,'approved','صورت رسمی خواستن به فعل پایه متصل است.'),
('occ-turn-de-a1-msg-3-morgen','dialogue_turn','turn-de-a1-message-3','morgen',NULL,NULL,@x_morgen_adv,NULL,'approved','قید فردا ثبت شده است.'),
('occ-turn-de-a1-msg-4-ja','dialogue_turn','turn-de-a1-message-4','Ja',NULL,NULL,@x_ja,NULL,'approved','پاسخ مثبت ثبت شده است.'),
('occ-turn-de-a1-msg-4-moechte','dialogue_turn','turn-de-a1-message-4','möchte',NULL,NULL,@x_moegen,@f_moechte,'approved','صورت اول‌شخص خواستن به فعل پایه متصل است.'),
('occ-turn-de-a1-msg-4-morgen','dialogue_turn','turn-de-a1-message-4','morgen',NULL,NULL,@x_morgen_adv,NULL,'approved','قید فردا ثبت شده است.')
ON DUPLICATE KEY UPDATE owner_type=VALUES(owner_type),owner_key=VALUES(owner_key),surface=VALUES(surface),lexeme_id=VALUES(lexeme_id),lexeme_form_id=VALUES(lexeme_form_id),resolution_status=VALUES(resolution_status),resolution_notes=VALUES(resolution_notes);

SET @si_guten=(SELECT id FROM source_items WHERE item_key='srcitem-de-guten-tag'); SET @si_nameq=(SELECT id FROM source_items WHERE item_key='srcitem-de-wie-heissen-sie'); SET @si_namea=(SELECT id FROM source_items WHERE item_key='srcitem-de-ich-heisse-paul'); SET @si_wohnq=(SELECT id FROM source_items WHERE item_key='srcitem-de-wo-wohnen-sie'); SET @si_wohna=(SELECT id FROM source_items WHERE item_key='srcitem-de-ich-wohne-oesterreich');
SET @si_vor=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-vorname'); SET @si_fam=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-familienname'); SET @si_addr=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-adresse'); SET @si_stadt=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-stadt'); SET @si_first=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-example-first'); SET @si_family=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-example-family'); SET @si_street=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-example-street'); SET @si_city=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-example-city');
SET @si_alpha1=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-alpha-1'); SET @si_alpha2=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-alpha-2'); SET @si_alpha3=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-alpha-3'); SET @si_alpha4=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-alpha-4'); SET @si_alpha5=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-alpha-5'); SET @si_alpha6=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-form-alpha-6');
SET @si_open=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-sign-open'); SET @si_closed=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-sign-closed'); SET @si_enter=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-sign-entrance'); SET @si_exit=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-sign-exit');
SET @si_qcall=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-q-call'); SET @si_acall=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-a-call'); SET @si_qpick=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-q-pickup'); SET @si_apick=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-a-pickup'); SET @si_mon=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-monday'); SET @si_even=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-evening'); SET @si_over=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-day-after'); SET @si_ten=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-ten'); SET @si_after=(SELECT id FROM source_items WHERE item_key='srcitem-de-a1-msg-afternoon');

INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES
('dialogue_turn','turn-de-a1-form-1',@si_guten,'verbatim','متن هدف عین منبع موجود است.'),('dialogue_turn','turn-de-a1-form-2',@si_guten,'verbatim','متن هدف عین منبع موجود است.'),('dialogue_turn','turn-de-a1-form-3',@si_nameq,'verbatim','متن هدف عین منبع موجود است.'),('dialogue_turn','turn-de-a1-form-4',@si_namea,'verbatim','متن هدف عین منبع موجود است.'),('dialogue_turn','turn-de-a1-form-5',@si_wohnq,'verbatim','متن هدف عین منبع موجود است.'),('dialogue_turn','turn-de-a1-form-6',@si_wohna,'verbatim','متن هدف عین منبع موجود است.'),
('dialogue_turn','turn-de-a1-message-1',@si_qcall,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-message-2',@si_acall,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-message-3',@si_qpick,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-message-4',@si_apick,'verbatim','متن هدف عین منبع است.'),
('lexeme','lex-de-vorname',@si_vor,'verbatim','واژه عین منبع ثبت شده است.'),('lexeme','lex-de-familienname',@si_fam,'verbatim','واژه عین منبع ثبت شده است.'),('lexeme','lex-de-stadt',@si_stadt,'verbatim','واژه عین منبع ثبت شده است.'),('lexeme','lex-de-buchstabieren',@si_first,'other','فعل از دستور منبع استخراج شده است.'),
('lexeme','lex-de-offen',@si_open,'verbatim','تابلو عین منبع ثبت شده است.'),('lexeme','lex-de-geschlossen',@si_closed,'verbatim','تابلو عین منبع ثبت شده است.'),('lexeme','lex-de-eingang',@si_enter,'verbatim','تابلو عین منبع ثبت شده است.'),('lexeme','lex-de-ausgang',@si_exit,'verbatim','تابلو عین منبع ثبت شده است.'),
('lexeme','lex-de-anrufen',@si_qcall,'other','فعل از پرسش منبع استخراج شده است.'),('lexeme','lex-de-montag',@si_mon,'other','نام روز از پیام منبع استخراج شده است.'),('lexeme','lex-de-nachmittag',@si_after,'other','زمان روز از پیام منبع استخراج شده است.'),('lexeme','lex-de-uebermorgen',@si_over,'other','قید زمان از پیام منبع استخراج شده است.'),('lexeme','lex-de-morgen-adverb',@si_qcall,'other','قید فردا از پرسش منبع استخراج شده و از مدخل صبح جدا ثبت شده است.'),
('activity','act-de-a1-form-fields-matching',@si_vor,'source_items_grouped_for_matching','برچسب فرم از منبع است.'),('activity','act-de-a1-form-fields-matching',@si_fam,'source_items_grouped_for_matching','برچسب فرم از منبع است.'),('activity','act-de-a1-form-fields-matching',@si_addr,'source_items_grouped_for_matching','برچسب فرم از منبع است.'),('activity','act-de-a1-form-fields-matching',@si_stadt,'source_items_grouped_for_matching','برچسب فرم از منبع است.'),
('activity','act-de-a1-form-first-name-fill',@si_first,'other','مقدار نام کوچک از مثال منبع انتخاب شده است.'),('activity','act-de-a1-form-first-name-fill',@si_family,'other','گزینهٔ نام خانوادگی از مثال منبع آمده است.'),('activity','act-de-a1-form-first-name-fill',@si_street,'other','گزینهٔ خیابان از مثال منبع آمده است.'),('activity','act-de-a1-form-first-name-fill',@si_city,'other','گزینهٔ شهر از مثال منبع آمده است.'),
('activity','act-de-a1-common-signs-matching',@si_open,'source_items_grouped_for_matching','تابلو از منبع است.'),('activity','act-de-a1-common-signs-matching',@si_closed,'source_items_grouped_for_matching','تابلو از منبع است.'),('activity','act-de-a1-common-signs-matching',@si_enter,'source_items_grouped_for_matching','تابلو از منبع است.'),('activity','act-de-a1-common-signs-matching',@si_exit,'source_items_grouped_for_matching','تابلو از منبع است.'),
('activity','act-de-a1-alphabet-pronunciation',@si_alpha1,'other','خط الفبا عین منبع است.'),('activity','act-de-a1-alphabet-pronunciation',@si_alpha2,'other','خط الفبا عین منبع است.'),('activity','act-de-a1-alphabet-pronunciation',@si_alpha3,'other','خط الفبا عین منبع است.'),('activity','act-de-a1-alphabet-pronunciation',@si_alpha4,'other','خط الفبا عین منبع است.'),('activity','act-de-a1-alphabet-pronunciation',@si_alpha5,'other','خط الفبا عین منبع است.'),('activity','act-de-a1-alphabet-pronunciation',@si_alpha6,'other','خط الفبا عین منبع است.'),
('activity','act-de-a1-message-listen-callback',@si_mon,'other','متن صوت مستقل عین پیام منبع است.'),('activity','act-de-a1-message-listen-callback',@si_even,'options_selected_from_source_material','عبارت زمانی گزینه از پیام منبع گرفته شده است.'),('activity','act-de-a1-message-listen-callback',@si_over,'options_selected_from_source_material','عبارت زمانی گزینه از پیام منبع گرفته شده است.'),
('activity','act-de-a1-message-reading-matching',@si_mon,'source_items_grouped_for_matching','پیام کامل از منبع است.'),('activity','act-de-a1-message-reading-matching',@si_even,'source_items_grouped_for_matching','پیام کامل از منبع است.'),('activity','act-de-a1-message-reading-matching',@si_over,'source_items_grouped_for_matching','پیام کامل از منبع است.'),('activity','act-de-a1-message-reading-matching',@si_ten,'source_items_grouped_for_matching','پیام کامل از منبع است.'),
('activity','act-de-a1-message-write-order',@si_after,'sentence_tokenized_for_word_order','پیام عین منبع برای مرتب‌سازی بخش‌بندی شده است.');

UPDATE language_levels SET coverage=JSON_SET(coverage,'$.gaps[2]','ده واحد محتوایی به بازبینی رسیده‌اند؛ مرحلهٔ بعد بررسی سراسری پوشش هدف‌ها و رفع شکاف‌های واقعی پیش از تغییر وضعیت سطح است.','$.gaps[3]','پوشش شنیدن، خواندن، نوشتن و گفتار اکنون در واحدهای محتوایی توزیع شده است؛ در بررسی سراسری باید کفایت و توازن آن‌ها دوباره سنجیده شود.'),notes='A1 همچنان در مرحلهٔ ساخت و بررسی است. ده واحد محتوایی در وضعیت بازبینی‌اند. مرحلهٔ بعد، بررسی سراسری هدف‌های ارتباطی، زبانی و موقعیتی و رفع هر شکاف واقعی پیش از انتقال کل سطح به بازبینی است.' WHERE id=@level;
COMMIT;
