-- German Pre-A1 activity expansion: 3-6 purposeful activities per final lesson.
-- Generated once from canonical authoring JSON; safe to reapply.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='Pre-A1' LIMIT 1);
UPDATE lessons SET status='qa' WHERE language_level_id=@level AND status='final';
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-hallo-role-match',l.id,3,'matching','هر عبارت را به کاربردش وصل کن.','بعد از استفاده در مکالمه و تشخیص خداحافظی، این مرحله نقش دو عبارت پایه را بدون افزودن زبان تازه از هم جدا می‌کند.',NULL,'{"pairs":[{"left":"Hallo!","leftFa":"سلام!","rightFa":"شروع گفت‌وگو"},{"left":"Tschüss!","leftFa":"خداحافظ!","rightFa":"پایان گفت‌وگو"}]}','["source_items_grouped_for_matching","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-hallo'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-hallo','lex-de-tschuess') WHERE av.activity_key='act-de-hallo-role-match';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-hallo-role-match',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-wikibooks-de-basic-greetings') AND si.source_text IN ('Hallo!','Tschüss!');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-gm-farewell-response',l.id,3,'choose_response','گفت‌وگوی صبحگاهی تمام شده؛ پاسخ مناسب را انتخاب کن.','پس از تمرکز روی سلام صبحگاهی، یک بازیابی کوتاه از پایان مکالمه کمک می‌کند زبان‌آموز شروع و پایان را در یک توالی کامل نگه دارد.',NULL,'{"contextFa":"صبح است و گفت‌وگو تمام شده.","options":[{"textTarget":"Tschüss!","translationFa":"خداحافظ!","correct":true},{"textTarget":"Guten Morgen!","translationFa":"صبح بخیر!","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-guten-morgen'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-guten-morgen','lex-de-tschuess') WHERE av.activity_key='act-de-gm-farewell-response';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-gm-farewell-response',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-guten-morgen','src-wiktionary-de-hallo','src-wikibooks-de-basic-greetings') AND si.source_text IN ('Guten Morgen!','Tschüss!');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-pizza-fill-mag',l.id,3,'fill_blank','جملهٔ علاقه را کامل کن.','این مرحله تفاوت «mag» و «magst» را در همان جملهٔ منبع‌دار بازیابی می‌کند و شکل اول‌شخص را تثبیت می‌کند.',NULL,'{"sourceText":"Ich mag Pizza.","sourceTextFa":"من پیتزا دوست دارم.","blankedText":"Ich ___ Pizza.","blankedTextFa":"من پیتزا ___ دارم.","choices":["mag","magst"],"answer":"mag"}','["source_sentence_blank_created","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-pizza-like'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-moegen','lex-de-pizza') WHERE av.activity_key='act-de-pizza-fill-mag';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-pizza-fill-mag',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-magst-du-pizza','src-libra-de-ich-mag-pizza','src-wiktionary-de-moegen','src-wiktionary-de-pizza','src-wiktionary-de-hallo') AND si.source_text IN ('Ich mag Pizza.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-pizza-question-vs-answer',l.id,4,'multiple_choice','کدام جمله دربارهٔ علاقهٔ خودت است؟','پس از ساخت جمله، زبان‌آموز باید پرسش و پاسخ را از هم تشخیص دهد تا نقش «mag» و «magst» فقط حفظ شکلی نباشد.',NULL,'{"options":[{"textTarget":"Ich mag Pizza.","translationFa":"من پیتزا دوست دارم.","correct":true},{"textTarget":"Magst du Pizza?","translationFa":"پیتزا دوست داری؟","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-pizza-like'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-moegen','lex-de-pizza') WHERE av.activity_key='act-de-pizza-question-vs-answer';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-pizza-question-vs-answer',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-magst-du-pizza','src-libra-de-ich-mag-pizza','src-wiktionary-de-moegen','src-wiktionary-de-pizza','src-wiktionary-de-hallo') AND si.source_text IN ('Ich mag Pizza.','Magst du Pizza?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-ja-nein-meaning-check',l.id,3,'true_false','درست یا غلط؟ «Nein!» یعنی پاسخ منفی.','پس از انتخاب پاسخ در بافت، یک بررسی معنایی بسیار کوتاه بازیابی مستقیم «nein» را تثبیت می‌کند.',NULL,'{"statementTarget":"Nein!","statementFa":"«Nein!» پاسخ منفی است.","answer":true}','["persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-ja-nein'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-nein') WHERE av.activity_key='act-de-ja-nein-meaning-check';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-ja-nein-meaning-check',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-wikibooks-de-magst-du-pizza','src-wiktionary-de-ja','src-wiktionary-de-nein') AND si.source_text IN ('Nein!');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-danke-bitte-role-match',l.id,3,'matching','تشکر و پاسخ به تشکر را به هم وصل کن.','بعد از انتخاب «Bitte!» در پاسخ، این مرحله نقش دو عبارت را به‌صورت دوطرفه تثبیت می‌کند.',NULL,'{"pairs":[{"left":"Danke!","leftFa":"ممنون!","rightFa":"تشکر"},{"left":"Bitte!","leftFa":"خواهش می‌کنم!","rightFa":"پاسخ به تشکر"}]}','["source_items_grouped_for_matching","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-danke-bitte'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-danke','lex-de-bitte') WHERE av.activity_key='act-de-danke-bitte-role-match';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-danke-bitte-role-match',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-wiktionary-de-danke','src-wiktionary-de-bitte') AND si.source_text IN ('Bitte!','Danke!');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-apology-response-choice',l.id,3,'choose_response','در پاسخ به «Entschuldigung.» کدام عبارت مناسب‌تر است؟','این فعالیت پاسخ آرام به عذرخواهی را از جفت اجتماعی تشکر جدا می‌کند و بازیابی کاربردی می‌سازد.',NULL,'{"promptTarget":"Entschuldigung.","promptFa":"ببخشید.","options":[{"textTarget":"Kein Problem.","translationFa":"مشکلی نیست.","correct":true},{"textTarget":"Danke!","translationFa":"ممنون!","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-entschuldigung'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-entschuldigung','lex-de-kein-problem','lex-de-danke') WHERE av.activity_key='act-de-apology-response-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-apology-response-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-entschuldigung','src-wiktionary-de-kein-problem','src-wiktionary-de-danke','src-wiktionary-de-bitte') AND si.source_text IN ('Danke!','Entschuldigung.','Kein Problem.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-apology-formula-choice',l.id,4,'multiple_choice','کدام عبارت خودِ عذرخواهی است؟','در مرحلهٔ پایانی، زبان‌آموز باید عبارت آغازگر عذرخواهی را از یک عبارت اجتماعی آشنای دیگر تشخیص دهد.',NULL,'{"options":[{"textTarget":"Entschuldigung.","translationFa":"ببخشید.","correct":true},{"textTarget":"Danke!","translationFa":"ممنون!","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-entschuldigung'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-entschuldigung','lex-de-danke') WHERE av.activity_key='act-de-apology-formula-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-apology-formula-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-entschuldigung','src-wiktionary-de-kein-problem','src-wiktionary-de-danke','src-wiktionary-de-bitte') AND si.source_text IN ('Danke!','Entschuldigung.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-name-fill-heisse',l.id,3,'fill_blank','پاسخ معرفی نام را کامل کن.','جای‌خالی روی فرم «heiße» تمرکز می‌کند تا زبان‌آموز آن را از «heißt» در پرسش جدا کند.',NULL,'{"sourceText":"Ich heiße Iris.","sourceTextFa":"اسم من آیریس است.","blankedText":"Ich ___ Iris.","blankedTextFa":"اسم من آیریس است.","choices":["heiße","heißt"],"answer":"heiße"}','["source_sentence_blank_created","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-name-exchange'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-heissen') WHERE av.activity_key='act-de-name-fill-heisse';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-name-fill-heisse',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-wikibooks-de-wie-heisst-du','src-wiktionary-de-heissen') AND si.source_text IN ('Ich heiße Iris.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-name-question-role',l.id,4,'multiple_choice','کدام عبارت سؤالِ نام است؟','بعد از بازیابی پاسخ، تشخیص سؤال از جواب نقش دو فرم «heißt» و «heiße» را در ارتباط واقعی روشن می‌کند.',NULL,'{"options":[{"textTarget":"Wie heißt du?","translationFa":"اسمت چیه؟","correct":true},{"textTarget":"Ich heiße Iris.","translationFa":"اسم من آیریس است.","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-name-exchange'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-heissen') WHERE av.activity_key='act-de-name-question-role';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-name-question-role',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-wikibooks-de-wie-heisst-du','src-wiktionary-de-heissen') AND si.source_text IN ('Ich heiße Iris.','Wie heißt du?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-wellbeing-response',l.id,3,'choose_response','به «Wie geht''s?» پاسخ مناسب بده.','پس از کامل‌کردن پرسش، این مرحله جفت پرسش و پاسخ را با بازیابی مستقیم و کم‌فشار می‌بندد.',NULL,'{"promptTarget":"Wie geht''s?","promptFa":"حالت چطوره؟","options":[{"textTarget":"Gut.","translationFa":"خوبم.","correct":true},{"textTarget":"Hallo!","translationFa":"سلام!","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-wellbeing'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-wie-gehts','lex-de-gut','lex-de-hallo') WHERE av.activity_key='act-de-wellbeing-response';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-wellbeing-response',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-wikibooks-de-basic-greetings') AND si.source_text IN ('Gut.','Hallo!','Wie geht''s?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-simple-choice-fill',l.id,3,'fill_blank','پرسش انتخاب را کامل کن.','این بازیابی روی فرم «möchtest» تمرکز می‌کند و آن را از فرم آشنای «magst» جدا نگه می‌دارد.',NULL,'{"sourceText":"Was möchtest du?","sourceTextFa":"چی می‌خوای؟","blankedText":"Was ___ du?","blankedTextFa":"چی می‌خوای؟","choices":["möchtest","magst"],"answer":"möchtest"}','["source_sentence_blank_created","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-simple-choice'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-moegen') WHERE av.activity_key='act-de-simple-choice-fill';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-simple-choice-fill',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-oak-de-was-moechtest-du','src-wiktionary-de-moechten','src-wiktionary-de-pizza') AND si.source_text IN ('Was möchtest du?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-simple-choice-response',l.id,4,'choose_response','برای «Was möchtest du?» یک پاسخ مناسب انتخاب کن.','در پایان، زبان‌آموز پرسش تازه را به گزینهٔ آشنای «Pizza.» وصل می‌کند تا معنی آن در کاربرد تثبیت شود.',NULL,'{"promptTarget":"Was möchtest du?","promptFa":"چی می‌خوای؟","options":[{"textTarget":"Pizza.","translationFa":"پیتزا.","correct":true},{"textTarget":"Hallo!","translationFa":"سلام!","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-simple-choice'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-moegen','lex-de-pizza','lex-de-hallo') WHERE av.activity_key='act-de-simple-choice-response';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-simple-choice-response',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wiktionary-de-hallo','src-oak-de-was-moechtest-du','src-wiktionary-de-moechten','src-wiktionary-de-pizza') AND si.source_text IN ('Hallo!','Pizza.','Was möchtest du?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-residence-question-choice',l.id,3,'multiple_choice','کدام سؤال دربارهٔ محل زندگی است؟','پس از تطبیق پرسش و پاسخ، تشخیص خود سؤال‌ها از هم مانع قاطی‌شدن «wohnen» و «kommen» می‌شود.',NULL,'{"options":[{"textTarget":"Wo wohnen Sie?","translationFa":"کجا زندگی می‌کنید؟","correct":true},{"textTarget":"Woher kommen Sie?","translationFa":"اهل کجا هستید؟","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-residence-origin'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-wohnen','lex-de-kommen') WHERE av.activity_key='act-de-residence-question-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-residence-question-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-residence-origin') AND si.source_text IN ('Wo wohnen Sie?','Woher kommen Sie?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-residence-word-order',l.id,4,'word_order','پاسخ محل زندگی را دوباره بساز.','بازسازی جملهٔ کامل، الگوی «Ich wohne in ...» را از تشخیص به بازیابی فعال می‌برد.',NULL,'{"sourceText":"Ich wohne in Österreich.","sourceTextFa":"من در اتریش زندگی می‌کنم.","tokens":["Ich","wohne","in","Österreich."],"answer":["Ich","wohne","in","Österreich."]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-residence-origin'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-wohnen','lex-de-oesterreich') WHERE av.activity_key='act-de-residence-word-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-residence-word-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-residence-origin') AND si.source_text IN ('Ich wohne in Österreich.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-age-question-choice',l.id,3,'multiple_choice','کدام پرسش دربارهٔ سن است؟','بعد از تمرین گفتاری و شنیداری عدد، تشخیص پرسش سن کمک می‌کند معنی کل الگو حفظ شود.',NULL,'{"options":[{"textTarget":"Wie alt bist du?","translationFa":"چند سالته؟","correct":true},{"textTarget":"Ich bin 20 Jahre alt.","translationFa":"من ۲۰ ساله هستم.","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-age-numbers'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-alt') WHERE av.activity_key='act-de-age-question-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-age-question-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-age-time') AND si.source_text IN ('Ich bin 20 Jahre alt.','Wie alt bist du?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-age-word-order',l.id,4,'word_order','پاسخ سن را دوباره بساز.','این مرحله الگوی کامل گفتن سن را از تشخیص عدد به تولید ساختاری منتقل می‌کند.',NULL,'{"sourceText":"Ich bin 20 Jahre alt.","sourceTextFa":"من ۲۰ ساله هستم.","tokens":["Ich","bin","20","Jahre","alt."],"answer":["Ich","bin","20","Jahre","alt."]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-age-numbers'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-alt','lex-de-jahr','lex-de-zwanzig') WHERE av.activity_key='act-de-age-word-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-age-word-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-age-time') AND si.source_text IN ('Ich bin 20 Jahre alt.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-time-question-match',l.id,4,'matching','پرسش روز و ساعت را به پاسخ مناسب وصل کن.','این مرحله دو نوع اطلاعات نزدیک را کنار هم مقایسه می‌کند تا زبان‌آموز فقط عدد ساعت را حفظ نکند.',NULL,'{"pairs":[{"left":"Welcher Tag ist heute?","leftFa":"امروز چه روزی است؟","right":"Heute ist Dienstag.","rightFa":"امروز سه‌شنبه است."},{"left":"Wie spät ist es?","leftFa":"ساعت چنده؟","right":"Es ist 6.30 Uhr.","rightFa":"ساعت ۶:۳۰ است."}]}','["source_items_grouped_for_matching","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-day-time'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-heute','lex-de-dienstag','lex-de-uhr') WHERE av.activity_key='act-de-time-question-match';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-time-question-match',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-age-time') AND si.source_text IN ('Es ist 6.30 Uhr.','Heute ist Dienstag.','Welcher Tag ist heute?','Wie spät ist es?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-time-word-order',l.id,5,'word_order','جملهٔ ساعت را دوباره بساز.','بازسازی جملهٔ شنیده‌شده، دریافت شنیداری را به بازیابی فعال همان ساختار متصل می‌کند.',NULL,'{"sourceText":"Es ist 6.30 Uhr.","sourceTextFa":"ساعت ۶:۳۰ است.","tokens":["Es","ist","6.30","Uhr."],"answer":["Es","ist","6.30","Uhr."]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-day-time'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-uhr') WHERE av.activity_key='act-de-time-word-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-time-word-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-age-time') AND si.source_text IN ('Es ist 6.30 Uhr.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-birthday-question-order',l.id,3,'word_order','پرسش تاریخ تولد را دوباره بساز.','پس از گفت‌وگو و تکمیل پاسخ، بازسازی خود پرسش باعث می‌شود هر دو سمت تبادل بازیابی شوند.',NULL,'{"sourceText":"Wann hast du Geburtstag?","sourceTextFa":"تولدت کیه؟","tokens":["Wann","hast","du","Geburtstag?"],"answer":["Wann","hast","du","Geburtstag?"]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-birthday-date'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-geburtstag') WHERE av.activity_key='act-de-birthday-question-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-birthday-question-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-birthday-question','src-wikibooks-de-birthday') AND si.source_text IN ('Wann hast du Geburtstag?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-birthday-month-check',l.id,4,'true_false','درست یا غلط؟ این جمله یک تاریخ تولد در نوامبر می‌گوید.','بررسی معنی ماه در جملهٔ کامل کمک می‌کند تمرین فقط روی شکل «dreizehnten» متوقف نماند.',NULL,'{"statementTarget":"Ich habe am dreizehnten November Geburtstag.","statementFa":"این تاریخ تولد در ماه نوامبر است.","answer":true}','["persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-birthday-date'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-geburtstag','lex-de-november') WHERE av.activity_key='act-de-birthday-month-check';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-birthday-month-check',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-birthday-question','src-wikibooks-de-birthday') AND si.source_text IN ('Ich habe am dreizehnten November Geburtstag.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-phone-word-order',l.id,3,'word_order','جملهٔ شماره تلفن را دوباره بساز.','پس از تشخیص شنیداری، بازسازی همان جمله باعث می‌شود الگوی گفتن شماره نیز فعالانه تمرین شود.',NULL,'{"sourceText":"Meine Telefonnummer lautet 789.","sourceTextFa":"شماره تلفن من ۷۸۹ است.","tokens":["Meine","Telefonnummer","lautet","789."],"answer":["Meine","Telefonnummer","lautet","789."]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-phone-number'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-telefonnummer') WHERE av.activity_key='act-de-phone-word-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-phone-word-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-phone','src-wikibooks-de-phone-example') AND si.source_text IN ('Meine Telefonnummer lautet 789.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-phone-question-choice',l.id,4,'multiple_choice','کدام عبارت سؤالِ شماره تلفن است؟','این مرحله پرسش را از پاسخ جدا می‌کند تا زبان‌آموز هر دو نقش را در تبادل تشخیص دهد.',NULL,'{"options":[{"textTarget":"Wie lautet deine Telefonnummer?","translationFa":"شماره تلفنت چیه؟","correct":true},{"textTarget":"Meine Telefonnummer lautet 789.","translationFa":"شماره تلفن من ۷۸۹ است.","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-phone-number'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-telefonnummer') WHERE av.activity_key='act-de-phone-question-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-phone-question-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-phone','src-wikibooks-de-phone-example') AND si.source_text IN ('Meine Telefonnummer lautet 789.','Wie lautet deine Telefonnummer?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-object-answer-choice',l.id,3,'multiple_choice','کدام پاسخ می‌گوید «این یک کتاب است»؟','بعد از بازسازی یک پاسخ، این مرحله دو پاسخ هم‌ساخت را از نظر معنی واژهٔ پایانی مقایسه می‌کند.',NULL,'{"options":[{"textTarget":"Das ist ein Buch.","translationFa":"این یک کتاب است.","correct":true},{"textTarget":"Das ist eine Karte.","translationFa":"این یک کارت است.","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-basic-object'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-buch','lex-de-karte') WHERE av.activity_key='act-de-object-answer-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-object-answer-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-basic-object') AND si.source_text IN ('Das ist ein Buch.','Das ist eine Karte.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-object-question-check',l.id,4,'true_false','درست یا غلط؟ «Was ist das?» یک پرسش است.','این بررسی کوتاه نقش عبارت را تثبیت می‌کند و از حفظ صرفِ پاسخ جلوگیری می‌کند.',NULL,'{"statementTarget":"Was ist das?","statementFa":"این یک پرسش اطلاعاتی ساده است.","answer":true}','["persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-basic-object'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-buch','lex-de-karte') WHERE av.activity_key='act-de-object-question-check';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-object-question-check',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-basic-object') AND si.source_text IN ('Was ist das?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-personal-review-match',l.id,4,'matching','هر پرسش شخصی را به پاسخ مناسب وصل کن.','مرور چندهدفه باید علاوه بر فرم آزاد، بازیابی ساختاری پرسش و پاسخ‌های مهم را هم دوباره فعال کند.',NULL,'{"pairs":[{"left":"Wo wohnen Sie?","leftFa":"کجا زندگی می‌کنید؟","right":"Ich wohne in Österreich.","rightFa":"من در اتریش زندگی می‌کنم."},{"left":"Wie alt bist du?","leftFa":"چند سالته؟","right":"Ich bin 20 Jahre alt.","rightFa":"من ۲۰ ساله هستم."}]}','["source_items_grouped_for_matching","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-personal-review'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-wohnen','lex-de-oesterreich','lex-de-alt','lex-de-jahr','lex-de-zwanzig') WHERE av.activity_key='act-de-personal-review-match';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-personal-review-match',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-residence-origin','src-wikibooks-de-age-time','src-wikibooks-de-birthday','src-wikibooks-de-phone') AND si.source_text IN ('Ich bin 20 Jahre alt.','Ich wohne in Österreich.','Wie alt bist du?','Wo wohnen Sie?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-personal-review-phone-check',l.id,5,'true_false','درست یا غلط؟ این جمله یک شماره تلفن را بیان می‌کند.','این مرحلهٔ کوتاه یک هدف اطلاعات شخصی دیگر را بعد از فرم و شنیدن دوباره بازیابی می‌کند.',NULL,'{"statementTarget":"Meine Telefonnummer lautet 789.","statementFa":"این جمله یک شماره تلفن را بیان می‌کند.","answer":true}','["persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-personal-review'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-telefonnummer') WHERE av.activity_key='act-de-personal-review-phone-check';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-personal-review-phone-check',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-residence-origin','src-wikibooks-de-age-time','src-wikibooks-de-birthday','src-wikibooks-de-phone') AND si.source_text IN ('Meine Telefonnummer lautet 789.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-food-eat-word-order',l.id,3,'word_order','پاسخ مربوط به چیزی که می‌خوری را دوباره بساز.','بعد از تطبیق دو جفت پرسش و پاسخ، بازسازی پاسخ «essen» بازیابی فعال فعل تازه را اضافه می‌کند.',NULL,'{"sourceText":"Ich esse Reis.","sourceTextFa":"من برنج می‌خورم.","tokens":["Ich","esse","Reis."],"answer":["Ich","esse","Reis."]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-food-today'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-essen','lex-de-reis') WHERE av.activity_key='act-de-food-eat-word-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-food-eat-word-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-lesson-002') AND si.source_text IN ('Ich esse Reis.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-food-available-choice',l.id,4,'multiple_choice','کدام جمله می‌گوید امروز چه غذایی موجود است؟','این مقایسهٔ معنایی تفاوت «غذای موجود» و «چیزی که فرد می‌خورد» را روشن نگه می‌دارد.',NULL,'{"options":[{"textTarget":"Heute gibt es Suppe.","translationFa":"امروز سوپ داریم.","correct":true},{"textTarget":"Ich esse Reis.","translationFa":"من برنج می‌خورم.","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-food-today'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-heute','lex-de-suppe','lex-de-essen','lex-de-reis') WHERE av.activity_key='act-de-food-available-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-food-available-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-lesson-002') AND si.source_text IN ('Heute gibt es Suppe.','Ich esse Reis.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-simple-order-response',l.id,3,'choose_response','به سؤال سفارش پاسخ مناسب بده.','بعد از بازسازی سفارش، این مرحله پرسش رسمی را دوباره به پاسخ کاربردی آن وصل می‌کند.',NULL,'{"promptTarget":"Was möchten Sie bitte?","promptFa":"لطفاً چی میل دارید؟","options":[{"textTarget":"Eine Tasse Kaffee bitte!","translationFa":"یک فنجان قهوه لطفاً!","correct":true},{"textTarget":"Guten Tag!","translationFa":"روز بخیر!","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-simple-order'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-moegen','lex-de-bitte','lex-de-tasse','lex-de-kaffee') WHERE av.activity_key='act-de-simple-order-response';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-simple-order-response',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-lesson-002') AND si.source_text IN ('Eine Tasse Kaffee bitte!','Guten Tag!','Was möchten Sie bitte?');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-simple-order-function-check',l.id,4,'true_false','درست یا غلط؟ این عبارت یک سفارش کوتاه و مؤدبانه است.','در پایان زبان‌آموز باید نقش کل عبارت را بفهمد، نه اینکه فقط ترتیب واژه‌ها را حفظ کرده باشد.',NULL,'{"statementTarget":"Eine Tasse Kaffee bitte!","statementFa":"این یک سفارش کوتاه و مؤدبانه است.","answer":true}','["persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-simple-order'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-bitte','lex-de-tasse','lex-de-kaffee') WHERE av.activity_key='act-de-simple-order-function-check';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-simple-order-function-check',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-lesson-002') AND si.source_text IN ('Eine Tasse Kaffee bitte!');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-need-word-order',l.id,3,'word_order','جملهٔ نیاز را دوباره بساز.','پس از تطبیق، بازسازی جملهٔ «brauchen» آن را از تشخیص به تولید فعال منتقل می‌کند.',NULL,'{"sourceText":"Ich brauche eine Hose.","sourceTextFa":"من یک شلوار لازم دارم.","tokens":["Ich","brauche","eine","Hose."],"answer":["Ich","brauche","eine","Hose."]}','["sentence_tokenized_for_word_order","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-need-and-buy'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-brauchen','lex-de-hose') WHERE av.activity_key='act-de-need-word-order';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-need-word-order',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-lesson-004') AND si.source_text IN ('Ich brauche eine Hose.');
INSERT INTO activities (activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status)
SELECT 'act-de-buy-sentence-choice',l.id,4,'multiple_choice','کدام جمله دربارهٔ خرید است؟','مرحلهٔ پایانی تفاوت معنایی «نیاز داشتن» و «خریدن» را با دو جملهٔ کامل منبع‌دار می‌سنجد.',NULL,'{"options":[{"textTarget":"Ich kaufe ein Hemd und ein Paar Schuhe.","translationFa":"من یک پیراهن و یک جفت کفش می‌خرم.","correct":true},{"textTarget":"Ich brauche eine Hose.","translationFa":"من یک شلوار لازم دارم.","correct":false}]}','["options_selected_from_source_material","persian_translation_added"]',NULL,'not_required'
FROM lessons l WHERE l.lesson_key='de-pre-a1-lesson-need-and-buy'
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
INSERT IGNORE INTO activity_lexemes (activity_id,lexeme_id)
SELECT av.id,lx.id FROM activities av JOIN lexemes lx ON lx.lexeme_key IN ('lex-de-brauchen','lex-de-hose','lex-de-kaufen','lex-de-hemd','lex-de-schuhe') WHERE av.activity_key='act-de-buy-sentence-choice';
INSERT IGNORE INTO provenance_links (entity_type,entity_key,source_item_id,transformation,notes)
SELECT 'activity','act-de-buy-sentence-choice',si.id,'other','متن هدف این فعالیت عیناً از آیتم منبع موجود گرفته شده است.' FROM source_items si JOIN sources s ON s.id=si.source_id WHERE s.source_key IN ('src-wikibooks-de-lesson-004') AND si.source_text IN ('Ich brauche eine Hose.','Ich kaufe ein Hemd und ein Paar Schuhe.');
UPDATE lessons SET status='final' WHERE language_level_id=@level;
COMMIT;
