-- German A1 educational audit fixes, 2026-09-18.
-- No German learner-facing text is authored or corrected here.
-- Five lessons are fully replaced with reusable source-backed German.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-weather-appendix','German/Appendices/Vocabulary/Weather','واژگان و عبارت‌های سادهٔ آب‌وهوا','Wikibooks contributors','de','website','https://en.wikibooks.org/wiki/German/Appendices/Vocabulary/Weather','Das Wetter: basic current-weather questions and simple condition phrases including sunny, rainy, cloudy and snow.','بخش آب‌وهوا؛ پرسش دربارهٔ هوای یک شهر و عبارت‌های سادهٔ آفتابی، بارانی، ابری و برفی.',NULL,'maintained_current','صفحهٔ زندهٔ واژگان آب‌وهوا در ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ بررسی شد. فقط پرسش‌های کوتاه و عبارت‌های سادهٔ وضعیت فعلی هوا که در نسخهٔ جاری صفحه حضور دارند برای A1 استفاده می‌شوند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — German/Appendices/Vocabulary/Weather','reuse_with_attribution','2026-09-18','این منبع برای ساده‌سازی دو درس آب‌وهوا استفاده می‌شود تا ساختارهای سنگین‌تر پیش‌بینی و توصیه از مسیر تولیدی A1 حذف شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-transport-dialogue-current','Ungarisch: Themengebiete: Dialoge — Dialog 3','گفت‌وگوی کوتاه اتوبوس، قطار و سکو','Wikibooks contributors','de','website','https://de.wikibooks.org/wiki/Ungarisch:_Themengebiete:_Dialoge','Dialog 3: bus stop, next train, departure time and platform information.','گفت‌وگوی ۳؛ پرسش دربارهٔ توقف اتوبوس و زمان و سکوی قطار.',NULL,'maintained_current','صفحهٔ زندهٔ گفت‌وگوهای ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ بررسی شد. بخش انتخاب‌شده گفت‌وگوی کوتاه و معاصر دربارهٔ توقف اتوبوس، زمان حرکت قطار و شمارهٔ سکو دارد و برای A1 مناسب است.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Ungarisch: Themengebiete: Dialoge — Dialog 3','reuse_with_attribution','2026-09-18','فقط جمله‌های آلمانی خودِ گفت‌وگوی ۳ دربارهٔ حمل‌ونقل استفاده می‌شوند؛ هیچ جملهٔ آلمانی تازه برای تکمیل گفت‌وگو ساخته نمی‌شود.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-021-time-appointment' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-time-1','885','بخش ۸۸۵','Ich begleite Sie noch ein Stück. Ist Ihnen das recht?',UNHEX(SHA2('Ich begleite Sie noch ein Stück. Ist Ihnen das recht?',256)),'نمونهٔ موافقت با برنامه.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-021-time-appointment' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-time-2','885','بخش ۸۸۵','Ja, ich bin einverstanden.',UNHEX(SHA2('Ja, ich bin einverstanden.',256)),'پاسخ موافقت.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-021-time-appointment' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-time-3','885','بخش ۸۸۵','Wir gehen nicht ins Theater. Ist Ihnen das recht?',UNHEX(SHA2('Wir gehen nicht ins Theater. Ist Ihnen das recht?',256)),'نمونهٔ دوم موافقت با برنامه.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-021-time-appointment' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-time-4','885','بخش ۸۸۵','Ja, das ist mir recht.',UNHEX(SHA2('Ja, das ist mir recht.',256)),'پاسخ موافقت دوم.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-021-time-appointment' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-time-5','886','بخش ۸۸۶','Es tut mir leid, heute geht es nicht.',UNHEX(SHA2('Es tut mir leid, heute geht es nicht.',256)),'نمونهٔ رد مؤدبانه.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-021-time-appointment' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-time-6','887','بخش ۸۸۷','Morgen geht es vielleicht.',UNHEX(SHA2('Morgen geht es vielleicht.',256)),'نمونهٔ تعویق.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-directions' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-dir-1','Directions','بخش مسیرها','Wie komme ich zum Bahnhof?',UNHEX(SHA2('Wie komme ich zum Bahnhof?',256)),'جای‌گذاری مقصد ایستگاه در الگوی منبع.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-directions' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-dir-2','Directions','بخش مسیرها','Rechts abbiegen.',UNHEX(SHA2('Rechts abbiegen.',256)),'راهنمایی راست.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-directions' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-dir-3','Directions','بخش مسیرها','Wie komme ich zum Flughafen?',UNHEX(SHA2('Wie komme ich zum Flughafen?',256)),'جای‌گذاری مقصد فرودگاه در الگوی منبع.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-directions' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-dir-4','Directions','بخش مسیرها','geradeaus',UNHEX(SHA2('geradeaus',256)),'راهنمایی مستقیم.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikivoyage-german-phrasebook-directions' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-dir-5','Directions','بخش مسیرها','Links abbiegen.',UNHEX(SHA2('Links abbiegen.',256)),'راهنمایی چپ.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-1','Dialog 3','گفت‌وگوی ۳','Entschuldigung, hält dieser Bus am Hauptbahnhof?',UNHEX(SHA2('Entschuldigung, hält dieser Bus am Hauptbahnhof?',256)),'پرسش توقف اتوبوس.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-2','Dialog 3','گفت‌وگوی ۳','Ja, das ist die nächste Haltestelle.',UNHEX(SHA2('Ja, das ist die nächste Haltestelle.',256)),'پاسخ دربارهٔ ایستگاه بعدی.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-3','Dialog 3','گفت‌وگوی ۳','Vielen Dank.',UNHEX(SHA2('Vielen Dank.',256)),'تشکر.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-4','Dialog 3','گفت‌وگوی ۳','Wann fährt der nächste Zug nach Budapest?',UNHEX(SHA2('Wann fährt der nächste Zug nach Budapest?',256)),'پرسش زمان حرکت قطار.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-5','Dialog 3','گفت‌وگوی ۳','In 20 Minuten von Gleis 3.',UNHEX(SHA2('In 20 Minuten von Gleis 3.',256)),'پاسخ زمان و سکو.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-6','Dialog 3','گفت‌وگوی ۳','Perfekt, danke für die Information.',UNHEX(SHA2('Perfekt, danke für die Information.',256)),'تشکر از اطلاعات.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-transport-dialogue-current' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-transport-7','Dialog 3','گفت‌وگوی ۳','Gleich dort, neben der Treppe.',UNHEX(SHA2('Gleich dort, neben der Treppe.',256)),'گزینهٔ منبع‌دار دربارهٔ مکان.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-1','Das Wetter','بخش آب‌وهوا','Wie ist das Wetter in Berlin?',UNHEX(SHA2('Wie ist das Wetter in Berlin?',256)),'پرسش سادهٔ هوا.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-2','Das Wetter','بخش آب‌وهوا','Es ist sonnig',UNHEX(SHA2('Es ist sonnig',256)),'وضعیت آفتابی.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-3','Das Wetter','بخش آب‌وهوا','Es ist bewölkt',UNHEX(SHA2('Es ist bewölkt',256)),'وضعیت ابری.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-4','Das Wetter','بخش آب‌وهوا','Es ist regnerisch',UNHEX(SHA2('Es ist regnerisch',256)),'وضعیت بارانی.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-5','Das Wetter','بخش آب‌وهوا','Es regnet',UNHEX(SHA2('Es regnet',256)),'بارش باران.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-6','Das Wetter','بخش آب‌وهوا','Es schneit',UNHEX(SHA2('Es schneit',256)),'بارش برف.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-weather-appendix' LIMIT 1);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-audit-weather-7','Das Wetter','بخش آب‌وهوا','Es nieselt',UNHEX(SHA2('Es nieselt',256)),'بارش نم‌نم.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-reschedule-exact-time',@level,'دو نفر دربارهٔ مناسب‌بودن دو برنامهٔ ساده صحبت می‌کنند و موافقت خود را با دو پاسخ منبع‌دار بیان می‌کنند.','app','چهار نوبت عین نمونه‌های موافقت در بخش ۸۸۵ منبع انتخاب شده‌اند؛ متن آلمانی بازنویسی نشده است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-reschedule-exact-time' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-reschedule-exact-time-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Ich begleite Sie noch ein Stück. Ist Ihnen das recht?','کمی دیگر همراهتان می‌آیم. برایتان مناسب است؟',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-reschedule-exact-time-1';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-reschedule-exact-time-1',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-reschedule-exact-time-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ja, ich bin einverstanden.','بله، موافقم.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-reschedule-exact-time-2';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-reschedule-exact-time-2',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-reschedule-exact-time-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wir gehen nicht ins Theater. Ist Ihnen das recht?','به تئاتر نمی‌رویم. برایتان مناسب است؟',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-reschedule-exact-time-3';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-reschedule-exact-time-3',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-reschedule-exact-time-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ja, das ist mir recht.','بله، برای من مناسب است.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-reschedule-exact-time-4';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-reschedule-exact-time-4',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-train-arrival-station',@level,'مسافر مسیر ایستگاه قطار و فرودگاه را می‌پرسد و دو راهنمایی بسیار کوتاه را می‌شنود.','learner','پرسش‌های مسیر با جای‌گذاری مستقیم مقصد در الگوی خود منبع ساخته شده‌اند و پاسخ‌های جهت نیز عین عبارت‌های عبارت‌نامه هستند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-train-arrival-station' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-train-arrival-station-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wie komme ich zum Bahnhof?','چطور به ایستگاه قطار برسم؟',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-train-arrival-station-1';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-train-arrival-station-1',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-train-arrival-station-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Rechts abbiegen.','به راست بپیچید.',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-train-arrival-station-2';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-train-arrival-station-2',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-train-arrival-station-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wie komme ich zum Flughafen?','چطور به فرودگاه برسم؟',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-train-arrival-station-3';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-train-arrival-station-3',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-train-arrival-station-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','geradeaus','مستقیم.',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-train-arrival-station-4';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-train-arrival-station-4',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-transport-arrival',@level,'مسافر ابتدا دربارهٔ توقف اتوبوس در ایستگاه مرکزی و سپس زمان حرکت و سکوی قطار سؤال می‌کند.','learner','شش نوبت عین گفت‌وگوی ۳ منبع نگه داشته شده‌اند و هیچ جملهٔ آلمانی برای اتصال صحنه ساخته نشده است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-transport-arrival' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-transport-arrival-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Entschuldigung, hält dieser Bus am Hauptbahnhof?','ببخشید، این اتوبوس در ایستگاه مرکزی توقف می‌کند؟',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-transport-arrival-1';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-transport-arrival-1',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-transport-arrival-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Ja, das ist die nächste Haltestelle.','بله، ایستگاه بعدی است.',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-transport-arrival-2';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-transport-arrival-2',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-transport-arrival-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Vielen Dank.','خیلی ممنون.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-transport-arrival-3';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-transport-arrival-3',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-transport-arrival-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wann fährt der nächste Zug nach Budapest?','قطار بعدی به بوداپست چه زمانی حرکت می‌کند؟',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-transport-arrival-4';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-transport-arrival-4',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-transport-arrival-5',@dlg,5,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','In 20 Minuten von Gleis 3.','۲۰ دقیقهٔ دیگر از سکوی ۳.',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-transport-arrival-5';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-transport-arrival-5',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-transport-arrival-6',@dlg,6,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Perfekt, danke für die Information.','عالی، ممنون بابت اطلاعات.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-transport-arrival-6';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-transport-arrival-6',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-weather-rain-plan',@level,'دو پاسخ بسیار سادهٔ وضعیت فعلی هوا برای آفتابی و ابری بودن تمرین می‌شوند.','app','پرسش و هر دو پاسخ عین بخش واژگان آب‌وهوای منبع‌اند؛ فقط ترجمهٔ فارسی و نقش شخصیت‌ها اضافه شده است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-rain-plan' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-rain-plan-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie ist das Wetter in Berlin?','هوا در برلین چطور است؟',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-rain-plan-1';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-rain-plan-1',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-rain-plan-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Es ist sonnig','هوا آفتابی است.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-rain-plan-2';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-rain-plan-2',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-rain-plan-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie ist das Wetter in Berlin?','هوا در برلین چطور است؟',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-rain-plan-3';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-rain-plan-3',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-rain-plan-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Es ist bewölkt','هوا ابری است.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-rain-plan-4';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-rain-plan-4',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-weather-temperature',@level,'دو پاسخ بسیار سادهٔ وضعیت فعلی هوا برای باران و برف تمرین می‌شوند.','app','پرسش و هر دو پاسخ عین بخش واژگان آب‌وهوای منبع‌اند و متن آلمانی دستکاری نشده است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-temperature' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-temperature-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie ist das Wetter in Berlin?','هوا در برلین چطور است؟',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-temperature-1';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-temperature-1',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-temperature-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Es regnet','باران می‌بارد.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-temperature-2';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-temperature-2',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-temperature-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie ist das Wetter in Berlin?','هوا در برلین چطور است؟',FALSE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-temperature-3';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-temperature-3',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status,audio_url,audio_storage_path,audio_source_hash,audio_provider,audio_model_id,audio_voice_name,audio_voice_id,audio_generated_at) VALUES
('turn-de-a1-weather-temperature-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Es schneit','برف می‌بارد.',TRUE,'stale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn),audio_status='stale',audio_url=NULL,audio_storage_path=NULL,audio_source_hash=NULL,audio_provider=NULL,audio_model_id=NULL,audio_voice_name=NULL,audio_voice_id=NULL,audio_generated_at=NULL;
DELETE FROM provenance_links WHERE entity_type='dialogue_turn' AND entity_key='turn-de-a1-weather-temperature-4';
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('dialogue_turn','turn-de-a1-weather-temperature-4',@si,'verbatim','متن آلمانی از منبع ثبت‌شده آمده است.');
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-time-plans-appointment' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-time-plans-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET status='qa',title_fa='این برنامه براتون مناسبه؟',activity_selection_rationale='به‌جای دستکاری جملهٔ آلمانی مشکل‌دار قبلی، کل درس با نمونه‌های صحیح و عیناً منبع‌دارِ موافقت با برنامه جایگزین شده است.',sequence_rationale='مکالمه دو نمونهٔ موافقت را در بافت می‌آورد، سپس پاسخ مناسب انتخاب می‌شود و در پایان یک پاسخ کوتاه بازسازی می‌شود.',template_signature='conversation_speaking>choose_response>word_order',audio_status='stale',notes='بازبینی کامل ۱۸ سپتامبر ۲۰۲۶: کل درس بدون اصلاح دستی آلمانی با محتوای منبع‌دار جایگزین شد.' WHERE id=@lesson;
DELETE p FROM provenance_links p JOIN activities a ON p.entity_type='activity' AND p.entity_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE o FROM lexeme_occurrences o JOIN activities a ON o.owner_type='activity' AND o.owner_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE FROM activities WHERE lesson_id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-time-review-conversation',@lesson,1,'conversation_speaking','در دو برنامهٔ کوتاه، مناسب‌بودن پیشنهاد را بفهم و موافقت کن.','چهار نوبت عین بخش موافقت منبع هستند و خطای جملهٔ قبلی را بدون بازنویسی آلمانی حذف می‌کنند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-reschedule-exact-time' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-time-review-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-time-review-matching',@lesson,2,'choose_response','برای این پیشنهاد، پاسخ موافقت را انتخاب کن.','گزینهٔ درست و گزینه‌های دیگر همگی از نمونه‌های همان منبع انتخاب شده‌اند.',NULL,CAST('{"promptTarget":"Ich begleite Sie noch ein Stück. Ist Ihnen das recht?","promptFa":"کمی دیگر همراهتان می‌آیم. برایتان مناسب است؟","options":[{"textTarget":"Ja, ich bin einverstanden.","translationFa":"بله، موافقم.","correct":true},{"textTarget":"Es tut mir leid, heute geht es nicht.","translationFa":"متأسفم، امروز نمی‌شود.","correct":false},{"textTarget":"Morgen geht es vielleicht.","translationFa":"فردا شاید بشود.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-time-review-matching' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-matching',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-matching',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-matching',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-matching',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-time-review-order',@lesson,3,'word_order','پاسخ کوتاه موافقت را بساز.','این پاسخ عین نمونهٔ منبع است و به بازیابی فعال منتقل می‌شود.',NULL,CAST('{"sourceText":"Ja, das ist mir recht.","sourceTextFa":"بله، برای من مناسب است.","tokens":["Ja,","das","ist","mir","recht."],"answer":["Ja,","das","ist","mir","recht."]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-time-review-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-time-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-time-review-order',@si,'sentence_tokenized_for_word_order','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
UPDATE lessons SET status='final',audio_status='stale' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-directions-public-places' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-directions-sequence-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET status='qa',title_fa='ایستگاه و فرودگاه کدام طرف‌اند؟',activity_selection_rationale='درس قبلی با حمل‌ونقل عمومی هم‌پوشانی داشت و به نمونهٔ زمانی ضعیف متکی بود؛ این جایگزین فقط مهارت مسیر و مکان عمومی را با عبارت‌نامهٔ فعلی پوشش می‌دهد.',sequence_rationale='از دو پرسش مسیر و دو پاسخ کوتاه شروع می‌شود، سپس جهت درست تشخیص داده می‌شود و در پایان یک پرسش مسیر بازسازی می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',audio_status='stale',notes='بازبینی کامل ۱۸ سپتامبر ۲۰۲۶: کل درس بدون اصلاح دستی آلمانی با محتوای منبع‌دار جایگزین شد.' WHERE id=@lesson;
DELETE p FROM provenance_links p JOIN activities a ON p.entity_type='activity' AND p.entity_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE o FROM lexeme_occurrences o JOIN activities a ON o.owner_type='activity' AND o.owner_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE FROM activities WHERE lesson_id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-sequence-review-conversation',@lesson,1,'conversation_speaking','خودت گفت‌وگو را شروع کن: مسیر ایستگاه و فرودگاه را بپرس.','پرسش‌ها از الگوی مقصد در منبع و پاسخ‌ها از عبارت‌های جهت همان منبع می‌آیند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-train-arrival-station' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"learner"}' AS JSON),CAST('["other","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-directions-sequence-review-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-sequence-review-choice',@lesson,2,'multiple_choice','کدام عبارت یعنی «به راست بپیچید»؟','سه گزینه همگی عین عبارت‌های مسیر در منبع هستند.',NULL,CAST('{"options":[{"textTarget":"Rechts abbiegen.","translationFa":"به راست بپیچید.","correct":true},{"textTarget":"Links abbiegen.","translationFa":"به چپ بپیچید.","correct":false},{"textTarget":"geradeaus","translationFa":"مستقیم.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-directions-sequence-review-choice' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-directions-sequence-review-fill',@lesson,3,'word_order','پرسش مسیر فرودگاه را بساز.','جمله از الگوی مقصد و نمونهٔ فرودگاهِ خود منبع ساخته شده و فقط به قطعه‌های واژگانی تقسیم می‌شود.',NULL,CAST('{"sourceText":"Wie komme ich zum Flughafen?","sourceTextFa":"چطور به فرودگاه برسم؟","tokens":["Wie","komme","ich","zum","Flughafen?"],"answer":["Wie","komme","ich","zum","Flughafen?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-directions-sequence-review-fill' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-dir-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-directions-sequence-review-fill',@si,'sentence_tokenized_for_word_order','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
UPDATE lessons SET status='final',audio_status='stale' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-public-transport-tickets' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-transport-times-platform' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET status='qa',title_fa='ایستگاه بعدی و سکوی قطار',activity_selection_rationale='درس قبلی پاسخ زمانِ ضعیف و پوشش صوری سکو داشت؛ این درس کامل با یک گفت‌وگوی جاری و منبع‌دار دربارهٔ توقف، زمان و سکو جایگزین شده است.',sequence_rationale='مکالمهٔ واقعی ابتدا توقف اتوبوس و سپس زمان و سکوی قطار را می‌دهد؛ بعد اطلاعات زمان/سکو تشخیص داده و پرسش قطار بازسازی می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',audio_status='stale',notes='بازبینی کامل ۱۸ سپتامبر ۲۰۲۶: کل درس بدون اصلاح دستی آلمانی با محتوای منبع‌دار جایگزین شد.' WHERE id=@lesson;
DELETE p FROM provenance_links p JOIN activities a ON p.entity_type='activity' AND p.entity_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE o FROM lexeme_occurrences o JOIN activities a ON o.owner_type='activity' AND o.owner_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE FROM activities WHERE lesson_id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-transport-arrival-conversation',@lesson,1,'conversation_speaking','خودت گفت‌وگو را شروع کن و اطلاعات توقف، زمان و سکو را بگیر.','شش نوبت عین گفت‌وگوی حمل‌ونقل منبع هستند و هیچ پاسخ آلمانی برای پرکردن صحنه ساخته نشده است.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-transport-arrival' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"learner"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-transport-arrival-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-transport-arrival-choice',@lesson,2,'multiple_choice','کدام پاسخ هم زمان و هم شمارهٔ سکو را می‌دهد؟','گزینه‌ها همگی عین گفت‌وگوی ۳ منبع هستند.',NULL,CAST('{"options":[{"textTarget":"In 20 Minuten von Gleis 3.","translationFa":"۲۰ دقیقهٔ دیگر از سکوی ۳.","correct":true},{"textTarget":"Ja, das ist die nächste Haltestelle.","translationFa":"بله، ایستگاه بعدی است.","correct":false},{"textTarget":"Gleich dort, neben der Treppe.","translationFa":"همان‌جا، کنار پله‌ها.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-transport-arrival-choice' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-7' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-transport-arrival-order',@lesson,3,'word_order','پرسش زمان حرکت قطار بعدی را بساز.','پرسش عین گفت‌وگوی منبع است و به بازیابی هدایت‌شده منتقل می‌شود.',NULL,CAST('{"sourceText":"Wann fährt der nächste Zug nach Budapest?","sourceTextFa":"قطار بعدی به بوداپست چه زمانی حرکت می‌کند؟","tokens":["Wann","fährt","der","nächste","Zug","nach","Budapest?"],"answer":["Wann","fährt","der","nächste","Zug","nach","Budapest?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-transport-arrival-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-transport-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-transport-arrival-order',@si,'sentence_tokenized_for_word_order','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
UPDATE lessons SET status='final',audio_status='stale' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-weather-temperature' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-weather-rain-plan' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET status='qa',title_fa='آفتابی یا ابری؟',activity_selection_rationale='ساختارهای سنگین پیش‌بینی و توصیهٔ درس قبلی حذف شده‌اند؛ این جایگزین فقط عبارت‌های ساده و عیناً منبع‌دارِ وضعیت فعلی هوا را تمرین می‌دهد.',sequence_rationale='مکالمه دو وضعیت ساده را می‌آورد، سپس وضعیت درست تشخیص داده می‌شود و پرسش پایهٔ هوا بازسازی می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',audio_status='stale',notes='بازبینی کامل ۱۸ سپتامبر ۲۰۲۶: کل درس بدون اصلاح دستی آلمانی با محتوای منبع‌دار جایگزین شد.' WHERE id=@lesson;
DELETE p FROM provenance_links p JOIN activities a ON p.entity_type='activity' AND p.entity_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE o FROM lexeme_occurrences o JOIN activities a ON o.owner_type='activity' AND o.owner_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE FROM activities WHERE lesson_id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-rain-conversation',@lesson,1,'conversation_speaking','دو وضعیت سادهٔ آفتابی و ابری را در گفت‌وگو دنبال کن.','چهار نوبت فقط از پرسش و پاسخ‌های سادهٔ منبع تشکیل شده‌اند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-rain-plan' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-rain-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-rain-response',@lesson,2,'multiple_choice','کدام جمله یعنی هوا ابری است؟','سه گزینه عین عبارت‌های وضعیت هوا در منبع هستند.',NULL,CAST('{"options":[{"textTarget":"Es ist bewölkt","translationFa":"هوا ابری است.","correct":true},{"textTarget":"Es ist sonnig","translationFa":"هوا آفتابی است.","correct":false},{"textTarget":"Es ist regnerisch","translationFa":"هوا بارانی است.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-rain-response' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-3' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-response',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-2' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-response',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-4' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-response',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-rain-order',@lesson,3,'word_order','پرسش سادهٔ هوا در برلین را بساز.','پرسش عین منبع است و فقط برای بازسازی به قطعه‌های واژگانی تقسیم شده است.',NULL,CAST('{"sourceText":"Wie ist das Wetter in Berlin?","sourceTextFa":"هوا در برلین چطور است؟","tokens":["Wie","ist","das","Wetter","in","Berlin?"],"answer":["Wie","ist","das","Wetter","in","Berlin?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-rain-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-rain-order',@si,'sentence_tokenized_for_word_order','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
UPDATE lessons SET status='final',audio_status='stale' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-weather-temperature' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-weather-temperature' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET status='qa',title_fa='باران یا برف؟',activity_selection_rationale='عبارت‌های دماسنجِ مصنوعی درس قبلی کنار گذاشته شده‌اند؛ این درس کامل با دو وضعیت بسیار ساده و منبع‌دار باران و برف جایگزین شده است.',sequence_rationale='مکالمه دو وضعیت را معرفی می‌کند، سپس معنی باران تشخیص داده می‌شود و در پایان عبارت برف بازسازی می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',audio_status='stale',notes='بازبینی کامل ۱۸ سپتامبر ۲۰۲۶: کل درس بدون اصلاح دستی آلمانی با محتوای منبع‌دار جایگزین شد.' WHERE id=@lesson;
DELETE p FROM provenance_links p JOIN activities a ON p.entity_type='activity' AND p.entity_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE o FROM lexeme_occurrences o JOIN activities a ON o.owner_type='activity' AND o.owner_key=a.activity_key WHERE a.lesson_id=@lesson;
DELETE FROM activities WHERE lesson_id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-temperature-conversation',@lesson,1,'conversation_speaking','دو وضعیت سادهٔ باران و برف را در گفت‌وگو دنبال کن.','چهار نوبت عین پرسش و پاسخ‌های بخش واژگان آب‌وهوا هستند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-temperature' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-temperature-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-1' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-conversation',@si,'other','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-temperature-choice',@lesson,2,'multiple_choice','کدام جمله یعنی باران می‌بارد؟','سه گزینه همگی عین عبارت‌های منبع هستند.',NULL,CAST('{"options":[{"textTarget":"Es regnet","translationFa":"باران می‌بارد.","correct":true},{"textTarget":"Es schneit","translationFa":"برف می‌بارد.","correct":false},{"textTarget":"Es nieselt","translationFa":"نم‌نم باران می‌بارد.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-temperature-choice' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-5' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-7' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-choice',@si,'options_selected_from_source_material','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-temperature-order',@lesson,3,'word_order','عبارت «برف می‌بارد» را بساز.','عبارت عین منبع است و فقط برای بازیابی به قطعه‌های واژگانی تقسیم شده است.',NULL,CAST('{"sourceText":"Es schneit","sourceTextFa":"برف می‌بارد.","tokens":["Es","schneit"],"answer":["Es","schneit"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-temperature-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
SET @si := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-audit-weather-6' LIMIT 1);
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES('activity','act-de-a1-weather-temperature-order',@si,'sentence_tokenized_for_word_order','فعالیت فقط از متن منبع ثبت‌شده استفاده می‌کند.');
UPDATE lessons SET status='final',audio_status='stale' WHERE id=@lesson;

UPDATE units SET title_fa='زمان، برنامه و قرار',grouping_rationale='واحد از فهم بازهٔ زمانی به دعوت و سپس موافقت یا رد یک برنامه می‌رسد. درس سوم پس از بازبینی کامل با نمونه‌های صحیح و عیناً منبع‌دارِ موافقت جایگزین شده است.',metadata=CAST('{"sourceRefs":["src-wikibooks-de-lesson-021-time-appointment"],"learningTargets":["بازهٔ زمانی یک برنامه را با ساعت شروع و پایان بفهمد.","پرسش و پاسخ دربارهٔ «تا چه زمانی» را در برنامهٔ روزمره بفهمد.","یک دعوت ساده و رد مؤدبانه را دنبال کند.","پرسش دربارهٔ مناسب‌بودن یک برنامه را بفهمد و پاسخ موافقت را تشخیص دهد."]}' AS JSON),notes='هیچ متن آلمانی این واحد برای اصلاح دستی بازنویسی نمی‌شود؛ در بازبینی ۱۸ سپتامبر ۲۰۲۶ درس سوم به‌طور کامل با محتوای منبع‌دار جایگزین شد.' WHERE unit_key='de-a1-unit-time-plans-appointment' AND language_level_id=@level;
UPDATE units SET title_fa='مسیر و مکان‌های عمومی',grouping_rationale='واحد روی سه نیاز مکانی متمرکز است: پیدا کردن هتل و رستوران، پرسیدن و دنبال‌کردن مسیر شهری، و پرسیدن مسیر ایستگاه یا فرودگاه. موضوع زمان قطار از این واحد حذف شده تا با واحد حمل‌ونقل هم‌پوشانی نداشته باشد.',metadata=CAST('{"sourceRefs":["src-wikibooks-german-print-directions","src-wikivoyage-german-phrasebook-directions","src-wikibooks-de-lesson-006-where-when"],"learningTargets":["برای رسیدن به یک مکان عمومی مسیر را به شکل ساده بپرسد.","راهنمایی کوتاه با راست، چپ و مستقیم را بفهمد.","مسیر مکان‌هایی مانند ایستگاه قطار و فرودگاه را در پرسش‌های بسیار ساده دنبال کند."]}' AS JSON),notes='درس سوم در بازبینی ۱۸ سپتامبر ۲۰۲۶ به‌طور کامل با محتوای مسیرِ منبع‌دار جایگزین شد و دیگر از نمونهٔ زمان رسیدن قطار استفاده نمی‌کند.' WHERE unit_key='de-a1-unit-directions-public-places' AND language_level_id=@level;
UPDATE units SET title_fa='بلیت و حمل‌ونقل عمومی',grouping_rationale='واحد سه گام مستقل سفر با حمل‌ونقل عمومی را پوشش می‌دهد: درخواست بلیت، تشخیص وسیله یا توقف درست، و فهم اطلاعات واقعیِ زمان و سکو.',metadata=CAST('{"sourceRefs":["src-wikivoyage-german-phrasebook-transport","src-wikivoyage-german-phrasebook-directions","src-wikibooks-de-transport-dialogue-current"],"learningTargets":["برای یک مقصد ساده بلیت بخواهد.","قطار یا اتوبوس درست را با پرسش دربارهٔ مقصد و توقف تشخیص دهد.","اطلاعات سادهٔ توقف، زمان حرکت و شمارهٔ سکو را در یک گفت‌وگوی کوتاه بفهمد."]}' AS JSON),notes='در بازبینی ۱۸ سپتامبر ۲۰۲۶ ادعای آموزش قیمت بلیت حذف شد و درس سوم با گفت‌وگوی منبع‌دارِ واقعی دربارهٔ توقف، زمان و سکو جایگزین شد.' WHERE unit_key='de-a1-unit-public-transport-tickets' AND language_level_id=@level;
UPDATE units SET title_fa='آب‌وهوا',grouping_rationale='واحد از پرسش دربارهٔ هوای فعلی به تشخیص وضعیت‌های بسیار سادهٔ آفتابی، ابری، بارانی و برفی می‌رود. دو درس سنگین‌تر قبلی در بازبینی کامل با محتوای ساده‌تر و عیناً منبع‌دار جایگزین شدند.',metadata=CAST('{"sourceRefs":["src-wikibooks-german-print-weather","src-wikibooks-de-weather-appendix"],"learningTargets":["دربارهٔ هوای فعلی یک شهر سؤال کند و پاسخ ساده را بفهمد.","وضعیت‌های سادهٔ آفتابی و ابری را در پاسخ کوتاه تشخیص دهد.","وضعیت‌های سادهٔ باران و برف را از هم تشخیص دهد."]}' AS JSON),notes='واژگان تخصصی، ساختارهای سنگین توصیه و عبارت‌های مصنوعی دماسنج از مسیر تولیدی این واحد حذف شده‌اند.' WHERE unit_key='de-a1-unit-weather-temperature' AND language_level_id=@level;
UPDATE units SET title_fa='سلامت، پزشک و داروخانه',grouping_rationale='واحد از بیان مستقیم علامت شروع می‌کند، سپس دارو و داروخانه را پوشش می‌دهد و در پایان به پیگیری حال بیمار و بیان بهترشدن می‌رسد.',metadata=CAST('{"sourceRefs":["src-wikibooks-de-lesson-018-health"],"learningTargets":["علائم بسیار رایج بیماری را در پرسش و پاسخ کوتاه بیان و تشخیص دهد.","دارو و محل گرفتن دارو را در یک موقعیت سادهٔ پزشکی بفهمد.","با الگوی سادهٔ «دیگر ندارم» بهترشدن یک علامت را بیان کند."]}' AS JSON),notes='ادعای آموزش نسخه در بازبینی ۱۸ سپتامبر ۲۰۲۶ حذف شد، چون فعالیت‌های فعلی این واحد نسخه را به‌صورت مستقیم آموزش نمی‌دهند.' WHERE unit_key='de-a1-unit-health-doctor-pharmacy' AND language_level_id=@level;
UPDATE language_levels SET
notes='A1 شامل ۱۳ واحد و ۳۹ درس است. در بازبینی کامل ۱۸ سپتامبر ۲۰۲۶، پنج درس دارای خطای واقعی، هم‌پوشانی یا سطح نامناسب بدون اصلاح دستی متن آلمانی به‌طور کامل با محتوای عیناً منبع‌دار جایگزین شدند. وضعیت صوتی پس از هر تغییر محتوای نمایش‌داده‌شونده به زبان‌آموز باید از فرایند صوت مرجع دوباره محاسبه شود.',
audio_status='stale',
coverage=JSON_SET(coverage,
  '$.communicativeTargets[16]','گرفتن بلیت و فهم اطلاعات بسیار سادهٔ حمل‌ونقل عمومی، توقف، زمان و سکو',
  '$.communicativeTargets[17]','پرسیدن و فهم هوای فعلی و وضعیت‌های سادهٔ آفتابی، ابری، بارانی و برفی',
  '$.linguisticTargets[11]','خواندن و تلفظ واضح حروف، واژه‌ها و جمله‌های کوتاه در حد فعالیت‌های منبع‌دار موجود',
  '$.situations[11]','بلیت، قطار، اتوبوس، توقف و سکو',
  '$.situations[12]','آب‌وهوا، آفتاب، ابر، باران و برف')
WHERE id=@level;

COMMIT;
