-- German A1 Unit 6 — multi-item food/drink ordering and simple preference.
-- Base content never overwrites generated audio state.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);
SET @jonas := (SELECT id FROM characters WHERE character_key='char-de-jonas' LIMIT 1);
SET @lena := (SELECT id FROM characters WHERE character_key='char-de-lena' LIMIT 1);
INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-007-food-order','Deutschkurs für Anfänger/Lektion 007','سفارش چندقلمی و ترجیح ساده','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_007','Items 286 and 288: simple preferences and multi-item snack-bar ordering with an additional-item prompt.','بخش‌های ۲۸۶ و ۲۸۸؛ ترجیح ساده و سفارش خوراکی و نوشیدنی با پرسش دربارهٔ قلم دیگری که مشتری می‌خواهد.','2025-01-04','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۷ سپتامبر ۲۰۲۶ بررسی شد و آخرین ویرایش ثبت‌شدهٔ آن ۴ ژانویهٔ ۲۰۲۵ است. جمله‌های انتخاب‌شده دربارهٔ سفارش چندقلمی، افزودن یک قلم دیگر و بیان ترجیح ساده در بازبینی فعلی طبیعی و مناسب A1 هستند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 007','reuse_with_attribution','2026-09-17','استفاده به بخش‌های ۲۸۶ و ۲۸۸ محدود است. بخش ۲۸۸ یک سفارش دو مرحله‌ای منسجم و چند نمونهٔ جایگزین دارد و بخش ۲۸۶ ترجیح ساده با رد یک خوراکی یا نوشیدنی را فراهم می‌کند. جمله‌های آلمانی بدون بازنویسی وارد محتوا می‌شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
SET @src := (SELECT id FROM sources WHERE source_key='src-wikibooks-de-lesson-007-food-order' LIMIT 1);
INSERT INTO units(unit_key,language_level_id,sequence_index,title_fa,grouping_rationale,status,metadata,notes) VALUES
('de-a1-unit-expanded-food-order',@level,6,'سفارش گسترده‌تر غذا و نوشیدنی','سطح پیشین سفارش تک‌قلمی را معرفی کرده بود. این واحد همان موقعیت را به سفارش چندمرحله‌ای گسترش می‌دهد: یک خوراکی، پرسش فروشنده برای قلم دیگر، افزودن نوشیدنی و تشخیص ترجیح ساده. همهٔ این اجزا در دو بخش نزدیک از یک منبع واحد قرار دارند.','review',JSON_OBJECT('sourceRefs',JSON_ARRAY('src-wikibooks-de-lesson-007-food-order'),'learningTargets',JSON_ARRAY('سفارش بیش از یک قلم','فهم پرسش چیز دیگری','تشخیص ترجیح ساده','فهم تکه و فنجان')),'بازبینی پوشش انجام شد. گفت‌وگوی اصلی سفارش دو قلم را پوشش می‌دهد، تمرین‌های همان منبع چند ترکیب دیگر و ترجیح ساده را اضافه می‌کنند و نسبت به سفارش تک‌قلمی سطح پیشین گسترش واقعی ایجاد شده است. برای هدف فعلی این واحد شکاف ضروری مستقلی برای درس دوم پیدا نشد.')
ON DUPLICATE KEY UPDATE sequence_index=VALUES(sequence_index),title_fa=VALUES(title_fa),grouping_rationale=VALUES(grouping_rationale),status=IF(status='final',status,VALUES(status)),metadata=VALUES(metadata),notes=VALUES(notes);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-expanded-food-order' LIMIT 1);
SET @t_food := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-comm-food-order' LIMIT 1);
SET @t_food_sit := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-sit-cafe-restaurant' LIMIT 1);
SET @t_core := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-core-vocabulary' LIMIT 1);
SET @t_neg := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-negation' LIMIT 1);
SET @t_modal := (SELECT id FROM curriculum_targets WHERE language_level_id=@level AND target_key='a1-ling-modal-request-patterns' LIMIT 1);
INSERT IGNORE INTO unit_targets(unit_id,curriculum_target_id) VALUES(@unit,@t_food),(@unit,@t_food_sit),(@unit,@t_core),(@unit,@t_neg),(@unit,@t_modal);
INSERT INTO source_items(source_id,item_key,locator,locator_fa,source_text,source_text_hash,notes) VALUES
(@src,'srcitem-de-a1-food-1','288','بخش ۲۸۸','Was möchten Sie?',UNHEX(SHA2('Was möchten Sie?',256)),'پرسش آغاز سفارش.'),
(@src,'srcitem-de-a1-food-2','288','بخش ۲۸۸','Ich möchte ein Stück Kuchen.',UNHEX(SHA2('Ich möchte ein Stück Kuchen.',256)),'سفارش خوراکی.'),
(@src,'srcitem-de-a1-food-3','288','بخش ۲۸۸','Noch was bitte?',UNHEX(SHA2('Noch was bitte?',256)),'پرسش دربارهٔ قلم دیگر.'),
(@src,'srcitem-de-a1-food-4','288','بخش ۲۸۸','Ich möchte auch noch eine Tasse Kaffee.',UNHEX(SHA2('Ich möchte auch noch eine Tasse Kaffee.',256)),'افزودن نوشیدنی.'),
(@src,'srcitem-de-a1-food-pref-coffee','286','بخش ۲۸۶','Ich möchte Kaffee, aber keine Milch.',UNHEX(SHA2('Ich möchte Kaffee, aber keine Milch.',256)),'ترجیح قهوه بدون شیر.'),
(@src,'srcitem-de-a1-food-pref-cake','286','بخش ۲۸۶','Ich möchte Kuchen, aber keine Brötchen.',UNHEX(SHA2('Ich möchte Kuchen, aber keine Brötchen.',256)),'ترجیح کیک.'),
(@src,'srcitem-de-a1-food-pref-rice','286','بخش ۲۸۶','Ich möchte Reis, aber keine Suppe.',UNHEX(SHA2('Ich möchte Reis, aber keine Suppe.',256)),'ترجیح برنج.'),
(@src,'srcitem-de-a1-food-three-cake','288','بخش ۲۸۸','Ich möchte drei Stück Kuchen.',UNHEX(SHA2('Ich möchte drei Stück Kuchen.',256)),'نمونهٔ چند تکه کیک.'),
(@src,'srcitem-de-a1-food-coffee-milk-sugar','288','بخش ۲۸۸','Ich möchte noch eine Tasse Kaffee mit Milch und Zucker.',UNHEX(SHA2('Ich möchte noch eine Tasse Kaffee mit Milch und Zucker.',256)),'نمونهٔ قهوه با افزودنی‌ها.')
ON DUPLICATE KEY UPDATE source_id=VALUES(source_id),locator=VALUES(locator),locator_fa=VALUES(locator_fa),source_text=VALUES(source_text),source_text_hash=VALUES(source_text_hash),notes=VALUES(notes);
INSERT INTO lexemes(lexeme_key,language_id,lexeme_type,surface,normalized_surface,lemma,part_of_speech,part_of_speech_fa,cefr_level,translation_fa,usage_note_fa,flashcard_eligible,audio_status) VALUES
('lex-de-kuchen',@de,'word','Kuchen','Kuchen','Kuchen','noun','اسم','A1','کیک','در سفارش کافه برای درخواست یک یا چند تکه کیک استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-stueck',@de,'word','Stück','Stück','Stück','noun','اسم','A1','تکه / عدد','برای شمارش یک یا چند تکه از خوراکی مانند کیک استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-milch',@de,'word','Milch','Milch','Milch','noun','اسم','A1','شیر','در سفارش نوشیدنی و در بیان ترجیح ساده دربارهٔ داشتن یا نداشتن شیر استفاده می‌شود.',TRUE,'blocked_until_level_final'),
('lex-de-noch-was-bitte',@de,'phrase','Noch was bitte?','Noch was bitte?',NULL,NULL,NULL,'A1','چیز دیگری هم؟','در گفت‌وگوی سفارش برای پرسیدن اینکه مشتری قلم دیگری هم می‌خواهد استفاده می‌شود.',TRUE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE language_id=VALUES(language_id),lexeme_type=VALUES(lexeme_type),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),lemma=VALUES(lemma),part_of_speech=VALUES(part_of_speech),part_of_speech_fa=VALUES(part_of_speech_fa),cefr_level=VALUES(cefr_level),translation_fa=VALUES(translation_fa),usage_note_fa=VALUES(usage_note_fa),flashcard_eligible=VALUES(flashcard_eligible);
SET @x_kuchen := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-kuchen'); SET @x_stueck := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-stueck'); SET @x_milch := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-milch'); SET @x_noch := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-noch-was-bitte'); SET @x_moegen := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-moegen'); SET @x_tasse := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-tasse'); SET @x_kaffee := (SELECT id FROM lexemes WHERE lexeme_key='lex-de-kaffee');
INSERT INTO lexeme_forms(lexeme_form_key,lexeme_id,surface,normalized_surface,form_type,features,origin,review_status,notes) VALUES
('lexform-de-moegen-moechte',@x_moegen,'möchte','möchte','inflected',JSON_OBJECT('mood','subjunctive_II','person','1','number','singular'),'source_attested','approved','در پاسخ‌های منبع‌دار سفارش، صورت اول‌شخص مفرد برای بیان خواسته به کار رفته است.')
ON DUPLICATE KEY UPDATE lexeme_id=VALUES(lexeme_id),surface=VALUES(surface),normalized_surface=VALUES(normalized_surface),form_type=VALUES(form_type),features=VALUES(features),origin=VALUES(origin),review_status=VALUES(review_status),notes=VALUES(notes);
SET @f_moechte := (SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-moegen-moechte'); SET @f_moechten := (SELECT id FROM lexeme_forms WHERE lexeme_form_key='lexform-de-moegen-moechten');
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-expanded-food-order',@level,@unit,10,1,'چیز دیگری هم؟','Was möchten Sie? / Noch was bitte?','چه میل دارید؟ / چیز دیگری هم؟','draft','گفت‌وگو سفارش دو مرحله‌ای را می‌سازد؛ سپس ترجیح ساده با سه جملهٔ منبع‌دار سنجیده می‌شود، چهار ترکیب سفارش به معنی فارسی وصل می‌شوند و در پایان پاسخ افزودن قهوه بازسازی می‌شود.','درس از تعامل کامل به تمایز ترجیح، شناخت ترکیب‌های سفارش و بازیابی فعال نوبت مشتری حرکت می‌کند و نسبت به درس خرید قبلی الگوی فعالیت متفاوتی دارد.','conversation_speaking>multiple_choice>matching>word_order','blocked_until_level_final','یک گفت‌وگوی منبع‌دار چهار نوبتی هستهٔ واحد را می‌سازد و تمرین‌های نزدیک همان منبع ترجیح و ترکیب‌های دیگر را اضافه می‌کنند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),source_title=VALUES(source_title),source_title_fa=VALUES(source_title_fa),status=VALUES(status),activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-expanded-food-order');
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role) VALUES(@lesson,@t_food,'introduce'),(@lesson,@t_food_sit,'introduce'),(@lesson,@t_core,'introduce'),(@lesson,@t_neg,'practice'),(@lesson,@t_modal,'practice');
INSERT IGNORE INTO lesson_lexemes(lesson_id,lexeme_id,is_primary,role) VALUES(@lesson,@x_kuchen,TRUE,'introduce'),(@lesson,@x_stueck,TRUE,'introduce'),(@lesson,@x_milch,TRUE,'introduce'),(@lesson,@x_noch,TRUE,'introduce'),(@lesson,@x_moegen,FALSE,'review'),(@lesson,@x_tasse,FALSE,'review'),(@lesson,@x_kaffee,FALSE,'review');
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-expanded-food-order',@level,'یوناس در نقش کارمند کافه سفارش لنا را می‌گیرد. لنا ابتدا یک تکه کیک می‌خواهد و بعد از پرسش یوناس یک فنجان قهوه هم به سفارش اضافه می‌کند.','app','چهار نوبت نخست نمونهٔ ۲۸۸ عیناً حفظ شده‌اند و یک سفارش طبیعی دو مرحله‌ای می‌سازند. نقش کارمند کافهٔ یوناس با خطاب رسمی منبع و سناریوی خدماتی سازگار است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dialogue := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-expanded-food-order');
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-food-order-1',@dialogue,1,@jonas,'app_assigned','unspecified','Was möchten Sie?','چه میل دارید؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-food-order-2',@dialogue,2,@lena,'app_assigned','unspecified','Ich möchte ein Stück Kuchen.','یک تکه کیک می‌خواهم.',TRUE,'blocked_until_level_final'),
('turn-de-a1-food-order-3',@dialogue,3,@jonas,'app_assigned','unspecified','Noch was bitte?','چیز دیگری هم؟',FALSE,'blocked_until_level_final'),
('turn-de-a1-food-order-4',@dialogue,4,@lena,'app_assigned','unspecified','Ich möchte auch noch eine Tasse Kaffee.','یک فنجان قهوه هم می‌خواهم.',TRUE,'blocked_until_level_final')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-expanded-food-conversation',@lesson,1,'conversation_speaking','یک تکه کیک سفارش بده و بعد قهوه را هم به سفارشت اضافه کن.','چهار نوبت پیوستهٔ منبع، سفارش چندقلمی و پرسش رایج فروشنده برای قلم دیگر را بدون جمله‌سازی آزاد پوشش می‌دهند.',@dialogue,JSON_OBJECT('interaction','read_aloud_exchange','openingInitiator','app'),JSON_ARRAY('verbatim_dialogue','persian_translation_added','character_metadata_added'),NULL,'not_required'),
('act-de-a1-food-preference-choice',@lesson,2,'multiple_choice','کدام جمله می‌گوید قهوه می‌خواهم، اما شیر نمی‌خواهم؟','سه جملهٔ کامل و منبع‌دار یک الگوی سادهٔ ترجیح و رد را با خوراکی‌های متفاوت مقایسه می‌کنند.',NULL,JSON_OBJECT('options',JSON_ARRAY(JSON_OBJECT('textTarget','Ich möchte Kaffee, aber keine Milch.','translationFa','قهوه می‌خواهم، اما شیر نمی‌خواهم.','correct',TRUE),JSON_OBJECT('textTarget','Ich möchte Kuchen, aber keine Brötchen.','translationFa','کیک می‌خواهم، اما نان گرد نمی‌خواهم.','correct',FALSE),JSON_OBJECT('textTarget','Ich möchte Reis, aber keine Suppe.','translationFa','برنج می‌خواهم، اما سوپ نمی‌خواهم.','correct',FALSE))),JSON_ARRAY('options_selected_from_source_material','persian_translation_added'),NULL,'not_required'),
('act-de-a1-food-combinations-matching',@lesson,3,'matching','هر ترکیب سفارش را به معنی درستش وصل کن.','چهار ترکیب از نمونه‌های بخش ۲۸۸ تکه، فنجان و افزودنی‌های ساده را در بافت سفارش تثبیت می‌کنند.',NULL,JSON_OBJECT('pairs',JSON_ARRAY(JSON_OBJECT('left','ein Stück Kuchen','leftFa','یک تکه کیک','right','یک تکه کیک','rightFa','یک تکه کیک'),JSON_OBJECT('left','eine Tasse Kaffee','leftFa','یک فنجان قهوه','right','یک فنجان قهوه','rightFa','یک فنجان قهوه'),JSON_OBJECT('left','drei Stück Kuchen','leftFa','سه تکه کیک','right','سه تکه کیک','rightFa','سه تکه کیک'),JSON_OBJECT('left','eine Tasse Kaffee mit Milch und Zucker','leftFa','یک فنجان قهوه با شیر و شکر','right','قهوه با شیر و شکر','rightFa','قهوه با شیر و شکر'))),JSON_ARRAY('source_items_grouped_for_matching','persian_translation_added'),NULL,'not_required'),
('act-de-a1-food-add-coffee-order',@lesson,4,'word_order','جملهٔ اضافه کردن قهوه به سفارش را دوباره بساز.','آخرین نوبت مشتری پس از فهم و تشخیص به بازیابی فعال منتقل می‌شود.',NULL,JSON_OBJECT('sourceText','Ich möchte auch noch eine Tasse Kaffee.','sourceTextFa','یک فنجان قهوه هم می‌خواهم.','tokens',JSON_ARRAY('Ich','möchte','auch','noch','eine','Tasse','Kaffee.'),'answer',JSON_ARRAY('Ich','möchte','auch','noch','eine','Tasse','Kaffee.')),JSON_ARRAY('sentence_tokenized_for_word_order','persian_translation_added'),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=VALUES(audio_text_target);
SET @a1 := (SELECT id FROM activities WHERE activity_key='act-de-a1-expanded-food-conversation'); SET @a2 := (SELECT id FROM activities WHERE activity_key='act-de-a1-food-preference-choice'); SET @a3 := (SELECT id FROM activities WHERE activity_key='act-de-a1-food-combinations-matching'); SET @a4 := (SELECT id FROM activities WHERE activity_key='act-de-a1-food-add-coffee-order');
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id) VALUES(@a1,@t_food),(@a1,@t_food_sit),(@a1,@t_modal),(@a2,@t_food),(@a2,@t_neg),(@a3,@t_food),(@a3,@t_core),(@a4,@t_food),(@a4,@t_modal);
INSERT IGNORE INTO activity_lexemes(activity_id,lexeme_id) VALUES(@a1,@x_kuchen),(@a1,@x_stueck),(@a1,@x_noch),(@a1,@x_moegen),(@a1,@x_tasse),(@a1,@x_kaffee),(@a2,@x_moegen),(@a2,@x_kaffee),(@a2,@x_milch),(@a2,@x_kuchen),(@a3,@x_kuchen),(@a3,@x_stueck),(@a3,@x_milch),(@a3,@x_tasse),(@a3,@x_kaffee),(@a4,@x_moegen),(@a4,@x_tasse),(@a4,@x_kaffee);
INSERT INTO lexeme_occurrences(occurrence_key,owner_type,owner_key,surface,start_offset,end_offset,lexeme_id,lexeme_form_id,resolution_status,resolution_notes) VALUES
('occ-turn-de-a1-food-1-moechten','dialogue_turn','turn-de-a1-food-order-1','möchten',NULL,NULL,@x_moegen,@f_moechten,'approved','صورت رسمی خواستن به فعل پایه متصل است.'),
('occ-turn-de-a1-food-2-moechte','dialogue_turn','turn-de-a1-food-order-2','möchte',NULL,NULL,@x_moegen,@f_moechte,'approved','صورت اول‌شخص خواستن به فعل پایه متصل است.'),
('occ-turn-de-a1-food-2-stueck','dialogue_turn','turn-de-a1-food-order-2','Stück',NULL,NULL,@x_stueck,NULL,'approved','اتصال واحد تکه تأیید شده است.'),
('occ-turn-de-a1-food-2-kuchen','dialogue_turn','turn-de-a1-food-order-2','Kuchen',NULL,NULL,@x_kuchen,NULL,'approved','اتصال کیک تأیید شده است.'),
('occ-turn-de-a1-food-3-noch','dialogue_turn','turn-de-a1-food-order-3','Noch was bitte?',NULL,NULL,@x_noch,NULL,'approved','عبارت پرسش قلم دیگر ثبت شده است.'),
('occ-turn-de-a1-food-4-moechte','dialogue_turn','turn-de-a1-food-order-4','möchte',NULL,NULL,@x_moegen,@f_moechte,'approved','صورت اول‌شخص خواستن به فعل پایه متصل است.'),
('occ-turn-de-a1-food-4-tasse','dialogue_turn','turn-de-a1-food-order-4','Tasse',NULL,NULL,@x_tasse,NULL,'approved','اتصال فنجان تأیید شده است.'),
('occ-turn-de-a1-food-4-kaffee','dialogue_turn','turn-de-a1-food-order-4','Kaffee',NULL,NULL,@x_kaffee,NULL,'approved','اتصال قهوه تأیید شده است.')
ON DUPLICATE KEY UPDATE owner_type=VALUES(owner_type),owner_key=VALUES(owner_key),surface=VALUES(surface),lexeme_id=VALUES(lexeme_id),lexeme_form_id=VALUES(lexeme_form_id),resolution_status=VALUES(resolution_status),resolution_notes=VALUES(resolution_notes);
SET @si1 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-1'); SET @si2 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-2'); SET @si3 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-3'); SET @si4 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-4'); SET @sip1 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-pref-coffee'); SET @sip2 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-pref-cake'); SET @sip3 := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-pref-rice'); SET @si3cake := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-three-cake'); SET @sicms := (SELECT id FROM source_items WHERE item_key='srcitem-de-a1-food-coffee-milk-sugar');
INSERT IGNORE INTO provenance_links(entity_type,entity_key,source_item_id,transformation,notes) VALUES
('dialogue_turn','turn-de-a1-food-order-1',@si1,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-food-order-2',@si2,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-food-order-3',@si3,'verbatim','متن هدف عین منبع است.'),('dialogue_turn','turn-de-a1-food-order-4',@si4,'verbatim','متن هدف عین منبع است.'),
('lexeme','lex-de-kuchen',@si2,'other','واژه از جملهٔ منبع استخراج شده است.'),('lexeme','lex-de-stueck',@si2,'other','واژه از جملهٔ منبع استخراج شده است.'),('lexeme','lex-de-milch',@sip1,'other','واژه از جملهٔ منبع استخراج شده است.'),('lexeme','lex-de-noch-was-bitte',@si3,'verbatim','عبارت عین منبع ثبت شده است.'),('lexeme_form','lexform-de-moegen-moechte',@si2,'other','صورت صرفی از جملهٔ منبع‌دار استخراج شده است.'),
('activity','act-de-a1-food-preference-choice',@sip1,'options_selected_from_source_material','گزینهٔ درست عین منبع است.'),('activity','act-de-a1-food-preference-choice',@sip2,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),('activity','act-de-a1-food-preference-choice',@sip3,'options_selected_from_source_material','گزینهٔ مقایسه‌ای عین منبع است.'),('activity','act-de-a1-food-combinations-matching',@si2,'source_items_grouped_for_matching','ترکیب تکهٔ کیک از جملهٔ منبع استخراج شده است.'),('activity','act-de-a1-food-combinations-matching',@si4,'source_items_grouped_for_matching','ترکیب فنجان قهوه از جملهٔ منبع استخراج شده است.'),('activity','act-de-a1-food-combinations-matching',@si3cake,'source_items_grouped_for_matching','ترکیب سه تکه کیک از جملهٔ منبع استخراج شده است.'),('activity','act-de-a1-food-combinations-matching',@sicms,'source_items_grouped_for_matching','ترکیب قهوه با شیر و شکر از جملهٔ منبع استخراج شده است.'),('activity','act-de-a1-food-add-coffee-order',@si4,'sentence_tokenized_for_word_order','جملهٔ عین منبع برای مرتب‌سازی بخش‌بندی شده است.');
UPDATE language_levels SET coverage=JSON_SET(coverage,'$.gaps[2]','شش واحد نخست به بازبینی رسیده‌اند؛ مرحلهٔ بعد زمان، برنامه و قرار است که در واحد روتین عمداً برای پوشش مستقل به تعویق افتاد.'),notes='A1 همچنان در مرحلهٔ ساخت تدریجی است. شش واحد نخست در بازبینی‌اند. مرحلهٔ بعد زمان، برنامه و قرار است؛ این هدف پس از روتین روزانه عمداً مستقل نگه داشته شد تا ساعت سادهٔ سطح پیشین با برنامه و قرار A1 اشتباه گرفته نشود.' WHERE id=@level;
COMMIT;
