-- Synchronize source records expanded/added by the A1 replacement lessons.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-bll-a1-lesson-2','BLL German/A1/Lesson 2','پرسیدن دربارهٔ شغل و زبان‌های در حال یادگیری','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/BLL_German/A1/Lesson_2','Main text and exercises: formal first meeting and identity check, origin/residence, plus asking about profession and languages being learned.','متن اصلی و بخش تمرین‌ها؛ برخورد رسمی اولیه و تأیید هویت، مبدأ و محل زندگی، و پرسش دربارهٔ شغل و زبان‌های در حال یادگیری.','2025-10-18','contemporary_verified','صفحهٔ زندهٔ Wikibooks در ۱۷ سپتامبر ۲۰۲۶ دوباره بررسی شد. آخرین ویرایش ثبت‌شدهٔ آن ۱۸ اکتبر ۲۰۲۵ است و الگوهای مؤدبانهٔ پرسیدن دربارهٔ شغل و زبان‌های در حال یادگیری با آلمانی معیار معاصر سازگارند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — BLL German/A1/Lesson 2','reuse_with_attribution','2026-09-17','برای A1 از دو بخش مستقل استفاده می‌شود: متن برخورد رسمی با فرد ناآشنا برای نام، مبدأ و محل زندگی؛ و جفت‌های تمرینی شغل و زبان. جمله‌های آلمانی بدون بازنویسی آزاد استفاده می‌شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-007-room-objects','Deutschkurs für Anfänger/Lektion 007','اتاق و وسایل سادهٔ داخل آن','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_007','Items 271, 274/274a, 275 and selected safe vocabulary from 280: room objects, ownership, and asking where personal belongings are.','بخش‌های ۲۷۱، ۲۷۴ و پاسخ آن، ۲۷۵ و چند واژهٔ سالم از ۲۸۰؛ وسایل اتاق، مالکیت و پرسیدن محل وسایل شخصی.','2025-01-04','contemporary_verified','صفحهٔ زندهٔ Wikibooks در ۱۷ سپتامبر ۲۰۲۶ بررسی شد؛ آخرین ویرایش ثبت‌شدهٔ صفحه ۴ ژانویهٔ ۲۰۲۵ است. برای این رکورد فقط جفت‌های روشن و مستقیمِ پرسش و پاسخ دربارهٔ اتاق و وسایل آن و واژه‌های سالم همان بخش‌ها استفاده می‌شوند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 007','reuse_with_attribution','2026-09-17','برای واحد خانه، بخش ۲۷۵ نیز استفاده می‌شود: پرسش‌های Wo ist/sind mein/meine ... و پاسخ‌های Ihr/Ihre ... ist/sind hier. نمونه‌های مشکوک بخش‌های دیگر وارد محتوا نمی‌شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-004','Deutschkurs für Anfänger/Lektion 004','منبع نیاز، خرید و قیمت ساده','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_004','Items 124–132 and 148–150: needs versus buying, clothing/goods, and price/total exchanges with Euro and Cent.','بخش‌های ۱۲۴ تا ۱۳۲ و ۱۴۸ تا ۱۵۰؛ نیاز در برابر خرید، کالا و لباس، و پرسش/پاسخ قیمت و جمع کل با یورو و سنت.',NULL,'maintained_current','صفحهٔ زندهٔ Wikibooks در ۱۷ سپتامبر ۲۰۲۶ دوباره بررسی شد؛ الگوهای «brauchen»، «kaufen» و پرسیدن/گفتن قیمت برای کاربرد آموزشی معاصر معتبرند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 004','reuse_with_attribution','2026-09-17','این منبع برای دو مهارت مستقل A1 استفاده می‌شود: تمایز brauchen/kaufen در انتخاب کالا، و پرسیدن/فهمیدن قیمت دقیق و جمع کل.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-007-food-order','Deutschkurs für Anfänger/Lektion 007','سفارش چندقلمی و ترجیح ساده','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_007','Items 282 and 286–288: coffee customization, simple preferences, multi-item ordering, and unavailable-item substitutions.','بخش ۲۸۲ و ۲۸۶ تا ۲۸۸؛ شخصی‌سازی قهوه، ترجیح ساده، سفارش چندقلمی و جایگزین وقتی یک قلم موجود نیست.','2025-01-04','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۷ سپتامبر ۲۰۲۶ بررسی شد و آخرین ویرایش ثبت‌شدهٔ آن ۴ ژانویهٔ ۲۰۲۵ است. جمله‌های انتخاب‌شده دربارهٔ سفارش چندقلمی، افزودن یک قلم دیگر و بیان ترجیح ساده در بازبینی فعلی طبیعی و مناسب A1 هستند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 007','reuse_with_attribution','2026-09-17','بخش ۲۸۲ برای سفارش قهوه با شیر/شکر و بخش ۲۸۷ برای الگوی «Nein, aber es gibt ...» اضافه شده‌اند. متن آلمانی منبع بدون بازنویسی آزاد استفاده می‌شود.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-021-time-appointment','Deutschkurs für Anfänger/Lektion 021','زمان‌بندی و قرار روزمره','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_021','Selected items 850, 851, 853, 862, 877, 885, 886 and 887: schedule duration, exact-time negotiation, agreement, invitation and alternate-day responses.','بخش‌های ۸۵۰، ۸۵۱، ۸۵۳، ۸۶۲، ۸۷۷، ۸۸۵، ۸۸۶ و ۸۸۷؛ بازهٔ زمانی، مذاکرهٔ ساعت دقیق، توافق، دعوت و پیشنهاد روز جایگزین.','2021-03-30','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ دوباره بررسی شد. آخرین ویرایش صفحه ۳۰ مارس ۲۰۲۱ است؛ فقط جمله‌های ساده و پایدار آلمانی معیار دربارهٔ بازهٔ زمانی، دعوت، زمان قرار، موافقت یا رد و برنامهٔ روز بعد انتخاب شدند و در بازبینی فعلی همچنان طبیعی و قابل‌استفاده‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 021','reuse_with_attribution','2026-09-18','علاوه بر درس‌های برنامه و دعوت، جفت‌های بخش‌های ۸۷۷ و ۸۸۶ برای رد یک ساعت مشخص و تأیید ساعت/محل جایگزین استفاده می‌شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-german-print-directions','German/Print version — Gespräch 5-2: Der Engländer in Österreich','گفت‌وگوی پرسیدن مسیر شهرداری','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/German/Print_version','Lesson 3.05, Gespräch 5-2 — locating a hotel and restaurant, then asking for and following the route to the Rathaus in St. Pölten.','درس ۳.۰۵، گفت‌وگوی ۵-۲؛ پیدا کردن هتل و رستوران و سپس پرسیدن و دنبال‌کردن مسیر شهرداری سنت پولتن.','2024-06-05','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ بررسی شد؛ آخرین ویرایش صفحه ۵ ژوئن ۲۰۲۴ ثبت شده است. چهار نوبت انتخاب‌شده دربارهٔ پرسیدن مسیر شهرداری، درخواست تکرار و راهنمایی «راست، دور گوشه و مستقیم» در بازبینی فعلی همچنان آلمانی معیار و طبیعی‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — German/Print version','reuse_with_attribution','2026-09-18','گفت‌وگوی ۵-۲ در دو کاربرد A1 استفاده می‌شود: چهار نوبت نخست برای هتل/رستوران و بخش بعدی برای مسیر شهرداری. متن آلمانی منبع حفظ می‌شود.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-024-short-messages','Deutschkurs für Anfänger/Lektion 024','پیام کوتاه تماس و هماهنگی','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_024','Items 1007, 1010 and selected question-answer pair from 1020: callback messages, short coordination, and train arrival time.','بخش‌های ۱۰۰۷ و ۱۰۱۰ و جفت پرسش‌وپاسخ انتخاب‌شده از ۱۰۲۰؛ پیام تماس، هماهنگی کوتاه و زمان رسیدن قطار.','2024-12-04','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ دوباره بررسی شد و آخرین ویرایش ثبت‌شدهٔ آن ۴ دسامبر ۲۰۲۴ است. پیام‌های تماس و جفت‌های کوتاه هماهنگی انتخاب‌شده در بازبینی فعلی طبیعی و مناسب ارتباط روزمره‌اند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 024','reuse_with_attribution','2026-09-18','بخش‌های ۱۰۰۷ و ۱۰۱۰ برای پیام‌های تماس باقی می‌مانند؛ از ۱۰۲۰ فقط «Wann kommt der Zug an? – Der Zug kommt 16.20 Uhr an.» برای درس سفر A1 استفاده می‌شود.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-de-lesson-006-where-when','Deutschkurs für Anfänger/Lektion 006','پرسش‌های زمان و مکان برای قطار و خدمات ضروری','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/Deutschkurs_f%C3%BCr_Anf%C3%A4nger/Lektion_006','Items 254–255: asking when a train departs, where the station is, and where to find essential places or a doctor.','بخش‌های ۲۵۴ و ۲۵۵؛ زمان حرکت قطار، محل ایستگاه و پیدا کردن مکان یا پزشک.','2025-11-13','contemporary_verified','صفحهٔ زندهٔ ویکی‌بوکس در ۱۸ سپتامبر ۲۰۲۶ بررسی شد؛ آخرین ویرایش ثبت‌شده ۱۳ نوامبر ۲۰۲۵ است. برای این رکورد فقط پرسش‌های کوتاه و پایدار «Wann/Wo» دربارهٔ قطار، ایستگاه و خدمات ضروری استفاده می‌شوند.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — Deutschkurs für Anfänger/Lektion 006','reuse_with_attribution','2026-09-18','این رکورد برای محتوای A1 مربوط به زمان حرکت/مکان ایستگاه و پرسش «Wo finde ich einen Arzt?» ساخته شده است؛ بخش‌های دستوری یا واژگانی دیگر صفحه وارد درس نمی‌شوند.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);

INSERT INTO sources(source_key,title,title_fa,organization_or_author,language_code,source_type,url,locator,locator_fa,published_or_updated_at,modernity_status,currency_evidence,license_name,license_url,attribution_text,reuse_status,retrieved_at,notes) VALUES
('src-wikibooks-german-print-shopping-service','German/Print version — Going Shopping','درخواست کمک در فروشگاه لباس','Wikibooks contributors','de','course','https://en.wikibooks.org/wiki/German/Print_version','Level one shopping dialogue, boutique section: offer of help, finding a skirt in the right size, and locating the fitting room.','گفت‌وگوی خرید، بخش بوتیک؛ پیشنهاد کمک، پیدا کردن سایز مناسب و پرسیدن محل اتاق پرو.','2024-06-05','contemporary_verified','نسخهٔ زندهٔ German/Print version در ۱۸ سپتامبر ۲۰۲۶ بررسی شد. گفت‌وگوی بوتیک در نسخهٔ فعلی صفحه وجود دارد و درخواست کمک، سایز و اتاق پرو برای کاربرد روزمرهٔ معاصر مناسب است.','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Wikibooks contributors — German/Print version','reuse_with_attribution','2026-09-18','فقط شش نوبت پیوستهٔ بخش بوتیک، از «Darf ich Ihnen helfen?» تا «Dort drüben.»، برای درس خدمات A1 استفاده می‌شود.')
ON DUPLICATE KEY UPDATE title=VALUES(title),title_fa=VALUES(title_fa),organization_or_author=VALUES(organization_or_author),language_code=VALUES(language_code),source_type=VALUES(source_type),url=VALUES(url),locator=VALUES(locator),locator_fa=VALUES(locator_fa),published_or_updated_at=VALUES(published_or_updated_at),modernity_status=VALUES(modernity_status),currency_evidence=VALUES(currency_evidence),license_name=VALUES(license_name),license_url=VALUES(license_url),attribution_text=VALUES(attribution_text),reuse_status=VALUES(reuse_status),retrieved_at=VALUES(retrieved_at),notes=VALUES(notes);
COMMIT;
