-- Replace first seven A1 depth lessons with new source-backed content.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);

-- de-a1-lesson-integrated-introduction-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-find-person-formal',@level,'دو نفر برای نخستین بار رسمی با هم آشنا می‌شوند؛ یکی دنبال لیزا مولر است و بعد دربارهٔ نام، مبدأ و محل زندگی صحبت می‌کنند.','app','همهٔ جمله‌های آلمانی از متن اصلی منبع گرفته شده‌اند؛ شخصیت‌های برنامه فقط نقش‌های صحنه را اجرا می‌کنند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-find-person-formal' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-person-formal-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','Guten Tag! Ich suche Lisa Müller. Sind Sie Lisa Müller?','روز بخیر! دنبال لیزا مولر می‌گردم. شما لیزا مولر هستید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-person-formal-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-mia' LIMIT 1),'app_assigned','unspecified','Ja, und Sie? Wie heißen Sie?','بله، و شما؟ اسمتان چیست؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-person-formal-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','Ich heiße Lutz Schmidt.','اسم من لوتس اشمیت است.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-person-formal-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-mia' LIMIT 1),'app_assigned','unspecified','Woher kommen Sie? Kommen Sie aus Österreich?','اهل کجا هستید؟ از اتریش می‌آیید؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-person-formal-5',@dlg,5,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','Nein, ich komme aus Deutschland und ich wohne hier in Bern.','نه، من از آلمان می‌آیم و اینجا در برن زندگی می‌کنم.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-extended-introduction' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-integrated-introduction-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='اول مطمئن شو با چه کسی حرف می‌زنی',activity_selection_rationale='این درس به‌جای مرور شغل و زبان، مهارت تازهٔ شروع گفت‌وگوی رسمی با فرد ناآشنا و جداکردن مبدأ از محل زندگی را اضافه می‌کند.',sequence_rationale='از تشخیص هویت در مکالمه به فهم پاسخ مبدأ/محل زندگی و سپس ساخت پرسش مبدأ حرکت می‌کند.',template_signature='conversation_speaking>multiple_choice>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-intro-review-conversation',@lesson,1,'conversation_speaking','مکالمه را اجرا کن و اول مطمئن شو طرف مقابل همان کسی است که دنبالش می‌گردی.','مکالمهٔ منبع‌دار برخورد رسمی، نام، مبدأ و محل زندگی را در یک صحنهٔ واقعی کنار هم می‌آورد.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-find-person-formal' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-intro-review-choice',@lesson,2,'multiple_choice','کدام پاسخ هم مبدأ و هم محل زندگی را می‌گوید؟','زبان‌آموز باید بین معرفی نام و پاسخ کامل مبدأ/محل زندگی تمایز بگذارد.',NULL,CAST('{"options":[{"textTarget":"Nein, ich komme aus Deutschland und ich wohne hier in Bern.","translationFa":"نه، من از آلمان می‌آیم و اینجا در برن زندگی می‌کنم.","correct":true},{"textTarget":"Ich heiße Lutz Schmidt.","translationFa":"اسم من لوتس اشمیت است.","correct":false},{"textTarget":"Ja, und Sie? Wie heißen Sie?","translationFa":"بله، و شما؟ اسمتان چیست؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-intro-review-order',@lesson,3,'word_order','پرسش «اهل کجا هستید؟» را بساز.','بازسازی پرسش، تفاوت Woher با معرفی صرفِ نام را فعال می‌کند.',NULL,CAST('{"sourceText":"Woher kommen Sie?","sourceTextFa":"اهل کجا هستید؟","tokens":["Woher","kommen","Sie?"],"answer":["Woher","kommen","Sie?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-family-profile-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-family-study-residence',@level,'مکس از پاول دربارهٔ محل تحصیل برادر و محل زندگی خواهر خانواده می‌پرسد.','app','دو جفت پرسش‌وپاسخ از تمرین خانواده بدون بازنویسی متن آلمانی کنار هم قرار گرفته‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-family-study-residence' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-family-study-residence-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','Wo studiert euer Bruder?','برادرتان کجا درس می‌خواند؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-family-study-residence-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Unser Bruder studiert in Berlin.','برادر ما در برلین درس می‌خواند.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-family-study-residence-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-max' LIMIT 1),'app_assigned','unspecified','Wo wohnt eure Schwester?','خواهرتان کجا زندگی می‌کند؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-family-study-residence-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Unsere Schwester wohnt in Hamburg.','خواهر ما در هامبورگ زندگی می‌کند.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-family-and-close-people' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-family-profile-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='برادرت کجا درس می‌خونه؟ خواهرت کجا زندگی می‌کنه؟',activity_selection_rationale='این درس محور تازهٔ مکان را به واحد خانواده اضافه می‌کند؛ دو درس قبلی بیشتر روی نام، سن و شغل متمرکز بودند.',sequence_rationale='مکالمه دو کاربرد مکان را معرفی می‌کند، تمرین تشخیص فعل‌ها را جدا می‌کند و بازسازی پرسشِ محل زندگی تولید هدایت‌شده می‌دهد.',template_signature='conversation_speaking>multiple_choice>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-family-review-conversation',@lesson,1,'conversation_speaking','دربارهٔ محل تحصیل برادر و محل زندگی خواهر گفت‌وگو کن.','دو جفت پرسش‌وپاسخ منبع‌دار اطلاعات مکانی تازه‌ای به پروفایل خانواده اضافه می‌کنند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-family-study-residence' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-family-review-matching',@lesson,2,'multiple_choice','کدام جمله دربارهٔ محل تحصیل برادر است؟','تمرین تفاوت studieren و wohnen را در همان بافت خانواده می‌سنجد.',NULL,CAST('{"options":[{"textTarget":"Unser Bruder studiert in Berlin.","translationFa":"برادر ما در برلین درس می‌خواند.","correct":true},{"textTarget":"Unsere Schwester wohnt in Hamburg.","translationFa":"خواهر ما در هامبورگ زندگی می‌کند.","correct":false},{"textTarget":"Unser Vater ist LKW-Fahrer.","translationFa":"پدر ما رانندهٔ کامیون است.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-family-review-order',@lesson,3,'word_order','پرسش محل زندگی خواهر را بساز.','پرسش Wo + wohnen برای انتقال مهارت از فهم به تولید هدایت‌شده انتخاب شده است.',NULL,CAST('{"sourceText":"Wo wohnt eure Schwester?","sourceTextFa":"خواهرتان کجا زندگی می‌کند؟","tokens":["Wo","wohnt","eure","Schwester?"],"answer":["Wo","wohnt","eure","Schwester?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-home-description-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-find-belongings',@level,'آیریس وسایل شخصی‌اش را پیدا نمی‌کند و پاول جای آن‌ها را نشان می‌دهد.','app','جمله‌ها از تمرین ۲۷۵ منبع انتخاب شده‌اند و تفاوت mein/meine با Ihr/Ihre را در یک موقعیت کاربردی نشان می‌دهند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-find-belongings' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-belongings-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wo ist mein Heft?','دفترم کجاست؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-belongings-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ihr Heft ist hier.','دفتر شما اینجاست.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-belongings-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wo ist meine Tasche?','کیفم کجاست؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-find-belongings-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ihre Tasche ist hier.','کیف شما اینجاست.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-home-and-nearby' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-home-description-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='وسایلم کجاست؟',activity_selection_rationale='به‌جای مرور جهت‌های اتاق، این درس یک نیاز واقعی تازه را پوشش می‌دهد: پیدا کردن وسایل شخصی و پاسخ‌دادن با شکل مؤدبانهٔ مالکیت.',sequence_rationale='مکالمه مفرد را معرفی می‌کند، تمرین تشخیص مفرد/جمع را گسترش می‌دهد و تطبیق چند وسیله دامنه را وسیع‌تر می‌کند.',template_signature='conversation_speaking>multiple_choice>matching',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-home-review-conversation',@lesson,1,'conversation_speaking','وسایل گم‌شده را بپرس و پاسخ محل آن‌ها را بده.','مکالمهٔ منبع‌دار mein/meine و Ihr/Ihre را در موقعیت پیدا کردن وسایل فعال می‌کند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-find-belongings' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-home-review-order',@lesson,2,'multiple_choice','اگر دربارهٔ چند کتاب صحبت می‌کنیم، کدام پاسخ درست است؟','مفرد و جمع با پاسخ‌های واقعی همان تمرین از هم تفکیک می‌شوند.',NULL,CAST('{"options":[{"textTarget":"Ihre Bücher sind hier.","translationFa":"کتاب‌های شما اینجاست.","correct":true},{"textTarget":"Ihr Heft ist hier.","translationFa":"دفتر شما اینجاست.","correct":false},{"textTarget":"Ihre Tasche ist hier.","translationFa":"کیف شما اینجاست.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-home-review-matching',@lesson,3,'matching','هر سؤال را به پاسخ درستش وصل کن.','چهار جفت منبع‌دار دامنه را از دفتر و کیف به مداد و کتاب‌ها گسترش می‌دهند.',NULL,CAST('{"pairs":[{"left":"Wo ist mein Heft?","leftFa":"دفترم کجاست؟","right":"Ihr Heft ist hier.","rightFa":"دفتر شما اینجاست."},{"left":"Wo ist mein Bleistift?","leftFa":"مدادم کجاست؟","right":"Ihr Bleistift ist hier.","rightFa":"مداد شما اینجاست."},{"left":"Wo ist meine Tasche?","leftFa":"کیفم کجاست؟","right":"Ihre Tasche ist hier.","rightFa":"کیف شما اینجاست."},{"left":"Wo sind meine Bücher?","leftFa":"کتاب‌هایم کجاست؟","right":"Ihre Bücher sind hier.","rightFa":"کتاب‌های شما اینجاست."}]}' AS JSON),CAST('["source_items_grouped_for_matching","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-daily-routine-day-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-afternoon-evening-routine',@level,'آیریس دربارهٔ کارهای بعدازظهر و شب پاول می‌پرسد؛ پاسخ‌ها خرید روزانه و فعالیت‌های شبانه را پوشش می‌دهند.','app','دو بخش استفاده‌نشدهٔ تمرین روتین روزانه برای گسترش دامنه از صبح/مدرسه به بعدازظهر و شب انتخاب شده‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-afternoon-evening-routine' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-afternoon-evening-routine-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Was machen Sie nachmittags?','بعدازظهرها چه کار می‌کنید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-afternoon-evening-routine-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Nachmittags gehe ich in die Stadt und mache Einkäufe.','بعدازظهرها به شهر می‌روم و خرید می‌کنم.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-afternoon-evening-routine-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Was machen Sie abends?','شب‌ها چه کار می‌کنید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-afternoon-evening-routine-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Abends höre ich Radio, sehe fern und lese Zeitung.','شب‌ها رادیو گوش می‌دهم، تلویزیون می‌بینم و روزنامه می‌خوانم.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-daily-routine-work-school' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-daily-routine-day-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='بعدازظهر و شب چه کار می‌کنی؟',activity_selection_rationale='دو درس قبلی صبح، کار، مدرسه و برگشت به خانه را پوشش می‌دهند؛ این درس عمداً دامنه را به خرید بعدازظهر و فعالیت‌های شب گسترش می‌دهد.',sequence_rationale='ابتدا دو بخش تازهٔ روز در مکالمه می‌آیند، سپس تشخیص زمان سنجیده می‌شود و در پایان جملهٔ شب بازسازی می‌شود.',template_signature='conversation_speaking>multiple_choice>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-daily-review-conversation',@lesson,1,'conversation_speaking','برنامهٔ بعدازظهر و شب را در گفت‌وگو دنبال کن.','دو پاسخ استفاده‌نشدهٔ منبع، نیمهٔ دوم روز را به روتین اضافه می‌کنند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-afternoon-evening-routine' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-daily-review-matching',@lesson,2,'multiple_choice','کدام جمله دربارهٔ بعدازظهر است؟','زبان‌آموز باید نشانهٔ زمانی و محتوای فعالیت را هم‌زمان تشخیص دهد.',NULL,CAST('{"options":[{"textTarget":"Nachmittags gehe ich in die Stadt und mache Einkäufe.","translationFa":"بعدازظهرها به شهر می‌روم و خرید می‌کنم.","correct":true},{"textTarget":"Abends höre ich Radio, sehe fern und lese Zeitung.","translationFa":"شب‌ها رادیو گوش می‌دهم، تلویزیون می‌بینم و روزنامه می‌خوانم.","correct":false},{"textTarget":"Vormittags arbeite ich im Betrieb.","translationFa":"پیش از ظهرها در محل کار کار می‌کنم.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-daily-review-response',@lesson,3,'word_order','جملهٔ فعالیت‌های شب را دوباره بساز.','بازسازی یک جملهٔ چندفعلی ساده، دامنهٔ روتین را فراتر از یک فعل منفرد می‌برد.',NULL,CAST('{"sourceText":"Abends höre ich Radio, sehe fern und lese Zeitung.","sourceTextFa":"شب‌ها رادیو گوش می‌دهم، تلویزیون می‌بینم و روزنامه می‌خوانم.","tokens":["Abends","höre","ich","Radio,","sehe","fern","und","lese","Zeitung."],"answer":["Abends","höre","ich","Radio,","sehe","fern","und","lese","Zeitung."]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-shopping-price-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-shopping-needs-buying',@level,'فروشنده می‌پرسد مشتری چه چیزی لازم دارد و در نهایت چه چیزی می‌خرد.','app','دو الگوی مستقل brauchen و kaufen از بخش خرید منبع کنار هم قرار گرفته‌اند تا نیاز و تصمیم خرید از هم تفکیک شوند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-shopping-needs-buying' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-needs-buying-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Was brauchen Sie?','چه چیزی لازم دارید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-needs-buying-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ich brauche eine Tasche.','یک کیف لازم دارم.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-needs-buying-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Was kaufen Sie?','چه چیزی می‌خرید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-needs-buying-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Ich kaufe eine Tasche.','یک کیف می‌خرم.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-shopping-quantity-payment' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-shopping-price-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='چی لازم داری؟ چی می‌خری؟',activity_selection_rationale='این درس پیش از تراکنش مقدار و پرداخت، مرحلهٔ واقعیِ انتخاب کالا را اضافه می‌کند: اول نیاز، بعد تصمیم خرید.',sequence_rationale='مکالمه تفاوت دو فعل را در یک کالای ثابت روشن می‌کند؛ تطبیق نمونه‌ها دامنه را گسترش می‌دهد و بازسازی پرسش نیاز تولید هدایت‌شده می‌دهد.',template_signature='conversation_speaking>matching>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-price-review-conversation',@lesson,1,'conversation_speaking','بگو چه چیزی لازم داری و بعد چه چیزی می‌خری.','ثابت نگه‌داشتن کالا باعث می‌شود تفاوت brauchen و kaufen بدون حواس‌پرتی واژگانی دیده شود.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-shopping-needs-buying' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-price-review-matching',@lesson,2,'matching','هر جمله را به «نیاز» یا «خرید» وصل کن.','نمونه‌های مختلفِ لباس و کالا الگوی فعل را از یک مثال منفرد جدا می‌کنند.',NULL,CAST('{"pairs":[{"left":"Ich brauche eine Tasche.","leftFa":"یک کیف لازم دارم.","right":"نیاز: Tasche","rightFa":"نیاز: کیف"},{"left":"Ich brauche eine Hose.","leftFa":"یک شلوار لازم دارم.","right":"نیاز: Hose","rightFa":"نیاز: شلوار"},{"left":"Ich kaufe eine Tasche.","leftFa":"یک کیف می‌خرم.","right":"خرید: Tasche","rightFa":"خرید: کیف"},{"left":"Ich kaufe ein Paar Schuhe.","leftFa":"یک جفت کفش می‌خرم.","right":"خرید: Schuhe","rightFa":"خرید: کفش"}]}' AS JSON),CAST('["source_items_grouped_for_matching","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-price-review-order',@lesson,3,'word_order','پرسش «چه چیزی لازم دارید؟» را بساز.','پرسش پایهٔ نیاز برای شروع خرید به بازیابی فعال منتقل می‌شود.',NULL,CAST('{"sourceText":"Was brauchen Sie?","sourceTextFa":"چه چیزی لازم دارید؟","tokens":["Was","brauchen","Sie?"],"answer":["Was","brauchen","Sie?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-shopping-checkout-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-shopping-price-total',@level,'مشتری دو بار دربارهٔ قیمت می‌پرسد و پاسخ‌ها عدد یورو و سنت را در قالب واقعی نشان می‌دهند.','app','دو صورت پرسش قیمت و دو پاسخ دقیق یورو/سنت از تمرین‌های قیمت منبع استفاده شده‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-shopping-price-total' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-price-total-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie viel kostet das?','این چقدر قیمت دارد؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-price-total-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Das kostet 70 Euro und 92 Cent.','۷۰ یورو و ۹۲ سنت قیمت دارد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-price-total-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Was kostet das?','قیمت این چقدر است؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-shopping-price-total-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Das kostet 35 Euro und 15 Cent.','۳۵ یورو و ۱۵ سنت قیمت دارد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-shopping-quantity-payment' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-shopping-checkout-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='قیمت دقیق و جمع خرید',activity_selection_rationale='به‌جای تکرار صندوقِ درس اصلی، این درس خواندن دقیق یورو/سنت و تفاوت قیمت یک کالا با جمع کل را آموزش می‌دهد.',sequence_rationale='مکالمه دو صورت پرسش قیمت را معرفی می‌کند، انتخاب چند صورت پرسش را مقایسه می‌کند و در پایان جمع کل با عدد دقیق تکمیل می‌شود.',template_signature='conversation_speaking>multiple_choice>fill_blank',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-checkout-review-conversation',@lesson,1,'conversation_speaking','دو روش پرسیدن قیمت و پاسخ یورو/سنت را اجرا کن.','جمله‌های منبع‌دار مهارت خواندن قیمت دقیق را مستقل از مقدار کالا تمرین می‌دهند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-shopping-price-total' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-checkout-review-response',@lesson,2,'multiple_choice','کدام پرسش دربارهٔ جمع کل خرید است؟','تفاوت kostet با macht در کاربرد فروشگاهی به‌صورت معنایی سنجیده می‌شود.',NULL,CAST('{"options":[{"textTarget":"Wie viel macht das bitte?","translationFa":"جمعش لطفاً چقدر می‌شود؟","correct":true},{"textTarget":"Wie viel kostet das?","translationFa":"این چقدر قیمت دارد؟","correct":false},{"textTarget":"Was kostet das?","translationFa":"قیمت این چقدر است؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-shopping-checkout-review-order',@lesson,3,'fill_blank','جمع کل را با عدد درست کامل کن.','تمرین عدد دقیق یورو و سنت، فهم شنیداری/خواندنی قیمت را به بازیابی هدایت‌شده وصل می‌کند.',NULL,CAST('{"sourceText":"Das macht 63 Euro und 10 Cent.","sourceTextFa":"جمعش ۶۳ یورو و ۱۰ سنت می‌شود.","blankedText":"Das macht ___.","blankedTextFa":"جمعش ___ می‌شود.","choices":["63 Euro und 10 Cent","35 Euro und 15 Cent","70 Euro und 92 Cent"],"choicesFa":["۶۳ یورو و ۱۰ سنت","۳۵ یورو و ۱۵ سنت","۷۰ یورو و ۹۲ سنت"],"answer":"63 Euro und 10 Cent"}' AS JSON),CAST('["source_sentence_blank_created","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

-- de-a1-lesson-food-preference-review
INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-coffee-customization',@level,'در کافه، مشتری قهوه سفارش می‌دهد و مشخص می‌کند آن را فقط با شکر می‌خواهد.','app','چهار نوبت پیوسته از سفارش قهوه در منبع انتخاب شده‌اند؛ هدف تازه، شخصی‌سازی سفارش است.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-coffee-customization' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-coffee-customization-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Was möchten Sie?','چه میل دارید؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-coffee-customization-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Bitte eine Tasse Kaffee.','لطفاً یک فنجان قهوه.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-coffee-customization-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Mit Milch und Zucker?','با شیر و شکر؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-coffee-customization-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Bitte nur mit Zucker.','لطفاً فقط با شکر.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-expanded-food-order' AND language_level_id=@level LIMIT 1);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-food-preference-review' AND language_level_id=@level LIMIT 1);
UPDATE lessons SET unit_id=@unit,title_fa='قهوه‌ات رو چطور می‌خوای؟',activity_selection_rationale='این درس به‌جای مرور دوست‌داشتن/نداشتن، مهارت تازهٔ شخصی‌سازی سفارش را اضافه می‌کند؛ چیزی که در سفارش واقعی بسیار پرتکرار است.',sequence_rationale='از سفارش پایه به انتخاب افزودنی و سپس پرسیدن موجودبودن قلم دیگر می‌رسد.',template_signature='conversation_speaking>choose_response>word_order',status='final',audio_status='pending',notes='محتوای قبلی این درس به‌طور کامل با یک هدف آموزشی مستقل و منبع‌دار جایگزین شده است.' WHERE id=@lesson;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-food-preference-review-conversation',@lesson,1,'conversation_speaking','قهوه سفارش بده و دقیق بگو چه چیزی داخلش می‌خواهی.','چهار نوبت منبع‌دار سفارش و شخصی‌سازی نوشیدنی را به‌صورت پیوسته تمرین می‌کنند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-coffee-customization' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-food-preference-review-choice',@lesson,2,'choose_response','برای «Mit Milch und Zucker?» پاسخ درست را انتخاب کن.','پاسخ فقط با شکر مستقیماً مهارت تعیین ترجیح در سفارش را می‌سنجد.',NULL,CAST('{"promptTarget":"Mit Milch und Zucker?","promptFa":"با شیر و شکر؟","options":[{"textTarget":"Bitte nur mit Zucker.","translationFa":"لطفاً فقط با شکر.","correct":true},{"textTarget":"Bitte eine Tasse Kaffee.","translationFa":"لطفاً یک فنجان قهوه.","correct":false},{"textTarget":"Gibt es auch Kuchen?","translationFa":"کیک هم دارید؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-food-preference-review-order',@lesson,3,'word_order','بعد از نوشیدنی بپرس آیا کیک هم هست.','این پرسش سفارش را از یک قلم به بررسی قلم دوم گسترش می‌دهد.',NULL,CAST('{"sourceText":"Gibt es auch Kuchen?","sourceTextFa":"کیک هم هست؟","tokens":["Gibt","es","auch","Kuchen?"],"answer":["Gibt","es","auch","Kuchen?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required')
ON DUPLICATE KEY UPDATE lesson_id=VALUES(lesson_id),position_index=VALUES(position_index),activity_type=VALUES(activity_type),instruction_fa=VALUES(instruction_fa),selection_reason=VALUES(selection_reason),dialogue_id=VALUES(dialogue_id),payload=VALUES(payload),transformations=VALUES(transformations),audio_text_target=NULL,audio_status='not_required';

UPDATE language_levels SET audio_status='pending' WHERE id=@level;
COMMIT;
