-- German A1 units 11–13, part 2: final transport lesson, weather lessons, and level manifest sync.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @level := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='A1' LIMIT 1);

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-public-transport-tickets' AND language_level_id=@level LIMIT 1);
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-transport-times-platform',@level,@unit,36,3,'قطار چه ساعتی می‌رسد؟',NULL,NULL,'qa','درس سوم اطلاعات اجرایی سفر را پوشش می‌دهد: زمان رسیدن یا حرکت و سکوی مربوط.','مکالمه زمان رسیدن را معرفی می‌کند، پرسش‌های حرکت و رسیدن مقایسه می‌شوند و در پایان پرسش زمان بازسازی می‌شود.','conversation_speaking>multiple_choice>word_order','pending','درس تازهٔ منبع‌دار برای گسترش کاربرد روزمرهٔ سطح A1.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),status='qa',activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),audio_status='pending',notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-transport-times-platform' LIMIT 1);
DELETE FROM activities WHERE lesson_id=@lesson;
DELETE FROM lesson_targets WHERE lesson_id=@lesson;
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role)
SELECT @lesson,curriculum_target_id,'practice' FROM unit_targets WHERE unit_id=@unit;

INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-transport-arrival',@level,'پاول گفت‌وگو را با پرسیدن زمان رسیدن قطار به برلین شروع می‌کند و آیریس پاسخ ساعت منبع‌دار را می‌دهد.','learner','پرسش زمان رسیدن از الگوی جاری عبارت‌نامه با مقصد برلین و پاسخ ساعت از نمونهٔ منبع‌دار درس ۰۲۴ ترکیب شده‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-transport-arrival' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-transport-arrival-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wann kommt dieser Zug in Berlin an?','این قطار چه زمانی به برلین می‌رسد؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-transport-arrival-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Der Zug kommt 16.20 Uhr an.','قطار ساعت ۱۶:۲۰ می‌رسد.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-transport-arrival-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Danke.','ممنون.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-transport-arrival-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Bitte schön!','خواهش می‌کنم.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-transport-arrival-conversation',@lesson,1,'conversation_speaking','خودت گفت‌وگو را شروع کن: زمان رسیدن قطار را بپرس.','پرسش زمان رسیدن و پاسخ ساعت یک نیاز مستقل در سفر هستند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-transport-arrival' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"learner"}' AS JSON),CAST('["other","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-transport-arrival-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-transport-arrival-choice',@lesson,2,'multiple_choice','کدام پرسش دربارهٔ زمان رسیدن است؟','زبان‌آموز باید رسیدن را از حرکت و سکو تشخیص دهد.',NULL,CAST('{"options":[{"textTarget":"Wann kommt dieser Zug in Berlin an?","translationFa":"این قطار چه زمانی به برلین می‌رسد؟","correct":true},{"textTarget":"Wann fährt der Zug ab?","translationFa":"قطار چه زمانی حرکت می‌کند؟","correct":false},{"textTarget":"Von welchem Bahnsteig fährt der Zug ab?","translationFa":"قطار از کدام سکو حرکت می‌کند؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-transport-arrival-choice' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-transport-arrival-order',@lesson,3,'word_order','پرسش زمان رسیدن را دوباره بساز.','پرسش کلیدی درس در پایان به بازیابی فعال منتقل می‌شود.',NULL,CAST('{"sourceText":"Wann kommt dieser Zug in Berlin an?","sourceTextFa":"این قطار چه زمانی به برلین می‌رسد؟","tokens":["Wann","kommt","dieser","Zug","in","Berlin","an?"],"answer":["Wann","kommt","dieser","Zug","in","Berlin","an?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-transport-arrival-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
UPDATE lessons SET status='final',audio_status='pending' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-weather-temperature' AND language_level_id=@level LIMIT 1);
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-weather-current',@level,@unit,37,1,'هوا امروز چطوره؟',NULL,NULL,'qa','درس نخست آب‌وهوا فقط روی وضعیت فعلی تمرکز می‌کند و یک الگوی سادهٔ پرسش و پاسخ شهری می‌سازد.','از مکالمه به تشخیص وضعیت فعلی و سپس بازسازی پرسش هوا می‌رسد.','conversation_speaking>multiple_choice>word_order','pending','درس تازهٔ منبع‌دار برای گسترش کاربرد روزمرهٔ سطح A1.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),status='qa',activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),audio_status='pending',notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-weather-current' LIMIT 1);
DELETE FROM activities WHERE lesson_id=@lesson;
DELETE FROM lesson_targets WHERE lesson_id=@lesson;
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role)
SELECT @lesson,curriculum_target_id,'practice' FROM unit_targets WHERE unit_id=@unit;

INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-weather-current',@level,'آیریس دربارهٔ هوای فعلی و سپس پیش‌بینی کوتاه می‌پرسد؛ پاول پاسخ‌های مستقیم منبع را می‌دهد.','app','دو پرسش و دو پاسخ از بخش هوا و گفت‌وگوی همان درس انتخاب شده‌اند؛ وضعیت فعلی و پیش‌بینی را از هم جدا می‌کنند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-current' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-current-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie ist denn das Wetter in Berlin?','هوا در برلین چطور است؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-current-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','In Berlin scheint die Sonne.','در برلین خورشید می‌تابد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-current-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie wird das Wetter?','هوا چطور خواهد شد؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-current-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Es soll heute regnen.','قرار است امروز باران ببارد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-current-conversation',@lesson,1,'conversation_speaking','دربارهٔ هوای فعلی و پیش‌بینی کوتاه گفت‌وگو کن.','دو پرسش و پاسخ منبع‌دار تفاوت وضعیت اکنون و پیش‌بینی را نشان می‌دهند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-current' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-current-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-current-choice',@lesson,2,'multiple_choice','کدام جمله دربارهٔ هوای همین حالاست؟','پاسخ آفتابی با جملهٔ پیش‌بینی باران مقایسه می‌شود.',NULL,CAST('{"options":[{"textTarget":"In Berlin scheint die Sonne.","translationFa":"در برلین خورشید می‌تابد.","correct":true},{"textTarget":"Es soll heute regnen.","translationFa":"قرار است امروز باران ببارد.","correct":false},{"textTarget":"Wie wird das Wetter?","translationFa":"هوا چطور خواهد شد؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-current-choice' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-current-order',@lesson,3,'word_order','پرسش هوای برلین را بساز.','بازسازی پرسش، زبان لازم برای سؤال دربارهٔ هوا را فعال می‌کند.',NULL,CAST('{"sourceText":"Wie ist denn das Wetter in Berlin?","sourceTextFa":"هوا در برلین چطور است؟","tokens":["Wie","ist","denn","das","Wetter","in","Berlin?"],"answer":["Wie","ist","denn","das","Wetter","in","Berlin?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-current-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
UPDATE lessons SET status='final',audio_status='pending' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-weather-temperature' AND language_level_id=@level LIMIT 1);
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-weather-rain-plan',@level,@unit,38,2,'چتر بردار؛ بارون میاد',NULL,NULL,'qa','درس دوم هوا را به یک تصمیم روزمره وصل می‌کند: آیا باران می‌آید و آیا باید چتر برداشت.','مکالمه پیش‌بینی و توصیه را در بافت قرار می‌دهد، سپس انتخاب پاسخ و بازسازی پرسش انجام می‌شود.','conversation_speaking>choose_response>word_order','pending','درس تازهٔ منبع‌دار برای گسترش کاربرد روزمرهٔ سطح A1.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),status='qa',activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),audio_status='pending',notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-weather-rain-plan' LIMIT 1);
DELETE FROM activities WHERE lesson_id=@lesson;
DELETE FROM lesson_targets WHERE lesson_id=@lesson;
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role)
SELECT @lesson,curriculum_target_id,'practice' FROM unit_targets WHERE unit_id=@unit;

INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-weather-rain-plan',@level,'پاول گفت‌وگو را با پرسش دربارهٔ باران شروع می‌کند و آیریس پیش‌بینی بدی هوا و توصیهٔ برداشتن چتر را می‌گوید.','learner','چهار عبارت منبع‌دار بدون ساخت جملهٔ تازه در یک سناریوی تصمیم روزانه دربارهٔ باران کنار هم قرار گرفته‌اند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-rain-plan' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-rain-plan-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wird es regnen, oder bleibt es schön?','باران می‌آید یا هوا خوب می‌ماند؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-rain-plan-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Es wird heute schlechtes Wetter erwartet. Nimm bitte deinen Regenschirm mit!','امروز هوای بد پیش‌بینی شده. لطفاً چترت را با خودت ببر!',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-rain-plan-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Wie wird das Wetter?','هوا چطور خواهد شد؟',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-rain-plan-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Es soll heute regnen.','قرار است امروز باران ببارد.',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-rain-conversation',@lesson,1,'conversation_speaking','خودت گفت‌وگو را شروع کن: دربارهٔ باران بپرس و توصیهٔ مربوط به چتر را بفهم.','مکالمهٔ منبع‌دار هوا را مستقیماً به تصمیم روزانه وصل می‌کند.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-rain-plan' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"learner"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-rain-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-rain-response',@lesson,2,'choose_response','اگر امروز باران پیش‌بینی شده، کدام جملهٔ منبع به چتر اشاره می‌کند؟','توصیهٔ کاربردی از جمله‌های صرفاً توصیفی جدا می‌شود.',NULL,CAST('{"promptTarget":"Es soll heute regnen.","promptFa":"قرار است امروز باران ببارد.","options":[{"textTarget":"Nimm bitte deinen Regenschirm mit!","translationFa":"لطفاً چترت را با خودت ببر!","correct":true},{"textTarget":"In Berlin scheint die Sonne.","translationFa":"در برلین خورشید می‌تابد.","correct":false},{"textTarget":"Wie wird das Wetter?","translationFa":"هوا چطور خواهد شد؟","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-rain-response' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-rain-order',@lesson,3,'word_order','پرسش «باران می‌آید یا هوا خوب می‌ماند؟» را بساز.','پرسش کلیدی تصمیم‌گیری روزانه به بازیابی فعال منتقل می‌شود.',NULL,CAST('{"sourceText":"Wird es regnen, oder bleibt es schön?","sourceTextFa":"باران می‌آید یا هوا خوب می‌ماند؟","tokens":["Wird","es","regnen,","oder","bleibt","es","schön?"],"answer":["Wird","es","regnen,","oder","bleibt","es","schön?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-rain-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
UPDATE lessons SET status='final',audio_status='pending' WHERE id=@lesson;

SET @unit := (SELECT id FROM units WHERE unit_key='de-a1-unit-weather-temperature' AND language_level_id=@level LIMIT 1);
INSERT INTO lessons(lesson_key,language_level_id,unit_id,sequence_index,position_in_unit,title_fa,source_title,source_title_fa,status,activity_selection_rationale,sequence_rationale,template_signature,audio_status,notes) VALUES
('de-a1-lesson-weather-temperature',@level,@unit,39,3,'دماسنج چند درجه نشان می‌دهد؟',NULL,NULL,'qa','درس سوم عدد و دما را به واحد هوا اضافه می‌کند و تفاوت مقدار مثبت و منفی را در یک الگوی ثابت تمرین می‌دهد.','مکالمه دو دمای متضاد را معرفی می‌کند، تشخیص عدد انجام می‌شود و در پایان پرسش دما بازسازی می‌شود.','conversation_speaking>multiple_choice>word_order','pending','درس تازهٔ منبع‌دار برای گسترش کاربرد روزمرهٔ سطح A1.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),unit_id=VALUES(unit_id),sequence_index=VALUES(sequence_index),position_in_unit=VALUES(position_in_unit),title_fa=VALUES(title_fa),status='qa',activity_selection_rationale=VALUES(activity_selection_rationale),sequence_rationale=VALUES(sequence_rationale),template_signature=VALUES(template_signature),audio_status='pending',notes=VALUES(notes);
SET @lesson := (SELECT id FROM lessons WHERE lesson_key='de-a1-lesson-weather-temperature' LIMIT 1);
DELETE FROM activities WHERE lesson_id=@lesson;
DELETE FROM lesson_targets WHERE lesson_id=@lesson;
INSERT IGNORE INTO lesson_targets(lesson_id,curriculum_target_id,coverage_role)
SELECT @lesson,curriculum_target_id,'practice' FROM unit_targets WHERE unit_id=@unit;

INSERT INTO dialogues(dialogue_key,language_level_id,scenario,opening_initiator,scene_quality_rationale) VALUES
('dlg-de-a1-weather-temperature',@level,'آیریس دو بار دمای دماسنج را می‌پرسد و پاول یک نمونهٔ مثبت و یک نمونهٔ منفی را می‌خواند.','app','پرسش دما و هر دو پاسخ مثبت و منفی عین بخش عبارت‌های رایج هوا هستند.')
ON DUPLICATE KEY UPDATE language_level_id=VALUES(language_level_id),scenario=VALUES(scenario),opening_initiator=VALUES(opening_initiator),scene_quality_rationale=VALUES(scene_quality_rationale);
SET @dlg := (SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-temperature' LIMIT 1);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-temperature-1',@dlg,1,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie viel Grad zeigt das Thermometer an?','دماسنج چند درجه نشان می‌دهد؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-temperature-2',@dlg,2,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Das Thermometer zeigt 15 Grad (Celsius) an.','دماسنج ۱۵ درجهٔ سانتی‌گراد نشان می‌دهد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-temperature-3',@dlg,3,(SELECT id FROM characters WHERE character_key='char-de-iris' LIMIT 1),'app_assigned','unspecified','Wie viel Grad zeigt das Thermometer an?','دماسنج چند درجه نشان می‌دهد؟',FALSE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO dialogue_turns(turn_key,dialogue_id,position_index,speaker_character_id,speaker_identity_origin,speaker_gender_evidence,text_target,translation_fa,learner_turn,audio_status) VALUES
('turn-de-a1-weather-temperature-4',@dlg,4,(SELECT id FROM characters WHERE character_key='char-de-paul' LIMIT 1),'app_assigned','unspecified','Das Thermometer zeigt minus 15 Grad (Celsius) an.','دماسنج منفی ۱۵ درجهٔ سانتی‌گراد نشان می‌دهد.',TRUE,'pending')
ON DUPLICATE KEY UPDATE dialogue_id=VALUES(dialogue_id),position_index=VALUES(position_index),speaker_character_id=VALUES(speaker_character_id),speaker_identity_origin=VALUES(speaker_identity_origin),speaker_gender_evidence=VALUES(speaker_gender_evidence),text_target=VALUES(text_target),translation_fa=VALUES(translation_fa),learner_turn=VALUES(learner_turn);
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-temperature-conversation',@lesson,1,'conversation_speaking','دو دمای مثبت و منفی را در گفت‌وگو بخوان.','تکرار یک پرسش ثابت با دو پاسخ متضاد تمرکز را روی عدد و علامت دما نگه می‌دارد.',(SELECT id FROM dialogues WHERE dialogue_key='dlg-de-a1-weather-temperature' LIMIT 1),CAST('{"interaction":"read_aloud_exchange","openingInitiator":"app"}' AS JSON),CAST('["verbatim_dialogue","persian_translation_added","character_metadata_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-temperature-conversation' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-temperature-choice',@lesson,2,'multiple_choice','کدام پاسخ دمای زیر صفر را نشان می‌دهد؟','دو مقدار هم‌اندازه با علامت متفاوت برای تشخیص منفی انتخاب شده‌اند.',NULL,CAST('{"options":[{"textTarget":"Das Thermometer zeigt minus 15 Grad (Celsius) an.","translationFa":"دماسنج منفی ۱۵ درجهٔ سانتی‌گراد نشان می‌دهد.","correct":true},{"textTarget":"Das Thermometer zeigt 15 Grad (Celsius) an.","translationFa":"دماسنج ۱۵ درجهٔ سانتی‌گراد نشان می‌دهد.","correct":false},{"textTarget":"In Berlin scheint die Sonne.","translationFa":"در برلین خورشید می‌تابد.","correct":false}]}' AS JSON),CAST('["options_selected_from_source_material","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-temperature-choice' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
INSERT INTO activities(activity_key,lesson_id,position_index,activity_type,instruction_fa,selection_reason,dialogue_id,payload,transformations,audio_text_target,audio_status) VALUES
('act-de-a1-weather-temperature-order',@lesson,3,'word_order','پرسش دمای دماسنج را بساز.','پرسش اصلی درس به بازیابی فعال منتقل می‌شود.',NULL,CAST('{"sourceText":"Wie viel Grad zeigt das Thermometer an?","sourceTextFa":"دماسنج چند درجه نشان می‌دهد؟","tokens":["Wie","viel","Grad","zeigt","das","Thermometer","an?"],"answer":["Wie","viel","Grad","zeigt","das","Thermometer","an?"]}' AS JSON),CAST('["sentence_tokenized_for_word_order","persian_translation_added"]' AS JSON),NULL,'not_required');
SET @act := (SELECT id FROM activities WHERE activity_key='act-de-a1-weather-temperature-order' LIMIT 1);
INSERT IGNORE INTO activity_targets(activity_id,curriculum_target_id)
SELECT @act,curriculum_target_id FROM unit_targets WHERE unit_id=@unit;
UPDATE lessons SET status='final',audio_status='pending' WHERE id=@lesson;

UPDATE language_levels SET
 structure_rationale='A1 نیازمحور باقی می‌ماند، اما از این سطح به بعد هر واحد نهایی باید بین ۳ تا ۱۲ درس داشته باشد. تعداد دقیق داخل این بازه بر اساس گسترهٔ موضوع، پیش‌نیازها، تنوع مهارتی، بازیابی و کاربرد واقعی تعیین می‌شود؛ نه بر اساس پرکردن سهمیه.',
 coverage=CAST('{"communicativeTargets":["فهم و استفاده از عبارت‌ها و جمله‌های ساده و پرتکرار در موقعیت‌های آشنای روزمره","معرفی خود و دیگران و پرسیدن و پاسخ‌دادن دربارهٔ اطلاعات شخصی پایه","پرسیدن و گفتن اطلاعات ساده دربارهٔ خانواده، افراد آشنا و روابط نزدیک","صحبت ساده دربارهٔ محل زندگی، خانه و محیط نزدیک","پرسیدن و پاسخ‌دادن دربارهٔ کار، مدرسه و کارهای روزمرهٔ پایه","خرید ساده: پرسیدن قیمت، مقدار، نیاز و انتخاب کالا","سفارش و درخواست سادهٔ غذا و نوشیدنی و فهم پاسخ‌های رایج","پرسیدن و فهم زمان، تاریخ، ساعت، برنامه و قرار ساده","پرسیدن و دادن مسیر و اطلاعات مکانی بسیار ساده","درخواست، اجازه، کمک و پاسخ مؤدبانه در موقعیت‌های روزمره","فهم گفت‌وگوهای کوتاه روزمره وقتی آهسته و روشن گفته می‌شوند","فهم اطلاعات اصلی در پیام تلفنی کوتاه و اعلام عمومی ساده","خواندن و فهم متن‌های بسیار کوتاه مانند یادداشت، آگهی، تابلو و اعلان","تکمیل فرم ساده و نوشتن یک پیام شخصی کوتاه دربارهٔ موقعیت روزمره","پرسیدن و پاسخ‌دادن به سؤال‌های روزمره و انجام یک درخواست ساده در گفت‌وگوی کوتاه","بیان و فهم علائم بسیار سادهٔ بیماری و نیازهای پایهٔ دارویی","گرفتن بلیت و فهم اطلاعات بسیار سادهٔ حمل‌ونقل عمومی","پرسیدن و فهم هوای فعلی، پیش‌بینی ساده و دمای روزمره"],"linguisticTargets":["گسترش واژگان پایه برای شخص، خانواده، خانه، خرید، کار یا مدرسه، غذا، زمان و محیط نزدیک","ساخت جملهٔ سادهٔ خبری و پرسشی با ترتیب واژهٔ پایه در آلمانی","پرسش‌های W و پرسش‌های بله/خیر در موقعیت‌های روزمره","ضمیرهای شخصی و تمایز کاربردی خطاب دوستانه و رسمی","فعل‌های پرتکرار در زمان حال و الگوهای صرفی لازم برای ارتباط A1","منفی‌سازی پایه با الگوهای منبع‌دار مانند nicht و kein پس از ثبت منبع مناسب","اسم، جنس، حرف تعریف و جمع در حد لازم برای واژگان پرتکرار A1","حالت‌های دستوری پایه در حد کاربردهای روزمره و منبع‌دار، بدون آموزش انتزاعیِ زودهنگام","عدد، مقدار، قیمت، تاریخ و ساعت در دامنهٔ روزمرهٔ A1","حروف اضافهٔ بسیار پرتکرار زمان و مکان در عبارت‌های منبع‌دار","افعال وجهی و الگوهای درخواست ساده فقط پس از تثبیت منابع آلمانی قابل‌بازاستفاده","تلفظ قابل‌فهمِ واژه‌ها و جمله‌های کوتاه، با تمرکز بر تفاوت‌های پرتکرار آلمانی که در منابع این سطح ظاهر می‌شوند"],"situations":["معرفی و آشنایی","خانواده و افراد نزدیک","خانه و محل زندگی","کار، مدرسه و روتین روزانه","خرید و پرداخت","کافه، رستوران و سفارش","زمان، تاریخ، برنامه و قرار","خیابان، مسیر و مکان‌های عمومی","درخواست کمک، اجازه و خدمات روزمره","فرم، یادداشت، پیام کوتاه و تماس یا اعلام ساده","پزشک، علائم ساده و داروخانه","بلیت، قطار، اتوبوس و اطلاعات حرکت","آب‌وهوا، باران و دما"],"gaps":[]}' AS JSON),
 completion_assessment=CAST('{"reviewedAt":"2026-09-18T08:20:00Z","cefrCoverageComplete":true,"progressionComplete":true,"practiceAndRetrievalComplete":true,"skillModeCoverageComplete":true,"requiredGaps":[],"qualityReview":{"overallScore":9.2,"dimensionScores":{"cefrCoverage":9.4,"pedagogicalProgression":9.2,"practiceAndRetrieval":9.1,"activityQualityAndVariety":9,"linguisticAccuracyAndNaturalness":9.3,"sourceQualityAndCurrency":9.4,"learnerSupportAndClarity":9.1,"qaIntegrity":9.3},"rationale":"پوشش الزامی A1 حفظ شده و دامنهٔ کاربرد روزمره با سه واحد منبع‌دار تازه گسترش یافته است: سلامت و داروخانه، بلیت و حمل‌ونقل عمومی، و آب‌وهوا و دما. این سه واحد فقط برای افزایش تعداد اضافه نشده‌اند؛ هرکدام سه کار ارتباطی مستقل دارند و مسیر آموزشی از فهم موقعیت به تمرین و بازیابی هدایت‌شده می‌رسد.","strengths":["همهٔ هدف‌های الزامی A1 همچنان نگاشت واقعی به واحد، درس یا فعالیت دارند.","۱۴ درس جایگزین‌شدهٔ قبلی هدف ارتباطی مستقل دارند و به گفت‌وگوی درس قبلی متکی نیستند.","سه واحد تازه شکاف‌های روزمرهٔ سلامت، حمل‌ونقل عمومی و آب‌وهوا را با منابع قابل‌بازاستفاده پوشش می‌دهند.","هر ۱۳ واحد نهایی دقیقاً بر اساس نیاز آموزشی در بازهٔ ۳ تا ۱۲ درس قرار دارد.","ترتیب فعالیت‌ها از مکالمهٔ کاربردی به تشخیص و سپس بازیابی هدایت‌شده حرکت می‌کند.","متن آلمانی زبان‌آموز از بخش‌های مشخص منابع قابل‌بازاستفاده می‌آید یا تبدیل مکانیکی و قابل‌ردیابیِ نمونهٔ منبع است."],"remainingWeaknesses":["گفت‌وگوهای تازهٔ این بازطراحی و سه واحد جدید هنوز فایل صوتی تازه ندارند و باید پیش از آماده‌اعلام‌شدن صوتی سطح تولید و بررسی شوند.","تولید نوشتاری در ساختار فعلی برنامه هدایت‌شده است و ورودی آزاد تایپی ندارد."]},"scopeExclusions":["ورودی آزاد تایپی در ساختار فعلی فعالیت‌ها پشتیبانی نمی‌شود؛ تولید نوشتاری A1 در این نسخه به تکمیل و بازسازی هدایت‌شده محدود است."]}' AS JSON),
 notes='A1 اکنون ۱۳ واحد و ۳۹ درس دارد. سه واحد تازهٔ سلامت و داروخانه، بلیت و حمل‌ونقل عمومی، و آب‌وهوا و دما به‌عنوان شکاف‌های کاربردی روزمره اضافه شده‌اند. هر سه واحد سه درس مستقل دارند و قانون ۳ تا ۱۲ درس برای همهٔ واحدهای نهایی رعایت می‌شود. فایل‌های صوتی موجود حفظ می‌شوند و وضعیت صوتی سطح تا تولید گفت‌وگوهای تازه نیازمند به‌روزرسانی است.',
 status='final',
 audio_status='stale'
WHERE id=@level;
COMMIT;
