-- German Pre-A1 matching activities: global matching bound is 4–8 pairs; Pre-A1 uses exactly 4.
-- This migration changes only non-audio matching payloads and learner-facing Persian guidance.
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
START TRANSACTION;
SET @de := (SELECT id FROM languages WHERE code='de' LIMIT 1);
SET @prea1 := (SELECT id FROM language_levels WHERE language_id=@de AND cefr_level='Pre-A1' LIMIT 1);
UPDATE lessons SET status='qa' WHERE language_level_id=@prea1 AND lesson_key IN ('de-pre-a1-lesson-hallo','de-pre-a1-lesson-danke-bitte','de-pre-a1-lesson-entschuldigung','de-pre-a1-lesson-residence-origin','de-pre-a1-lesson-personal-review','de-pre-a1-lesson-day-time','de-pre-a1-lesson-food-today','de-pre-a1-lesson-need-and-buy','de-pre-a1-lesson-ask-price','de-pre-a1-lesson-find-toilet') AND status='final';
UPDATE activities SET instruction_fa='هر عبارت را به کاربردش وصل کن.', selection_reason='چهار عبارت اجتماعی پایهٔ منبع‌دارِ واحد اول را در یک تطبیق کوتاه از هم جدا می‌کند تا مرحلهٔ وصل‌کردن چهار گزینهٔ معنادار داشته باشد.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Hallo!','leftFa','سلام!','right','سلام / شروع گفت‌وگو','rightFa','سلام / شروع گفت‌وگو'),JSON_OBJECT('left','Tschüss!','leftFa','خداحافظ!','right','خداحافظی / پایان گفت‌وگو','rightFa','خداحافظی / پایان گفت‌وگو'),JSON_OBJECT('left','Danke!','leftFa','ممنون!','right','تشکر','rightFa','تشکر'),JSON_OBJECT('left','Bitte!','leftFa','خواهش می‌کنم!','right','پاسخ به تشکر','rightFa','پاسخ به تشکر'))) WHERE activity_key='act-de-hallo-role-match';
UPDATE activities SET instruction_fa='هر عبارت را به کاربردش وصل کن.', selection_reason='چهار عبارت اجتماعی آشنای منبع‌دار را کنار هم می‌گذارد تا تشکر و پاسخ به آن در میان سلام و خداحافظی هم درست تشخیص داده شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Hallo!','leftFa','سلام!','right','سلام / شروع گفت‌وگو','rightFa','سلام / شروع گفت‌وگو'),JSON_OBJECT('left','Tschüss!','leftFa','خداحافظ!','right','خداحافظی / پایان گفت‌وگو','rightFa','خداحافظی / پایان گفت‌وگو'),JSON_OBJECT('left','Danke!','leftFa','ممنون!','right','تشکر','rightFa','تشکر'),JSON_OBJECT('left','Bitte!','leftFa','خواهش می‌کنم!','right','پاسخ به تشکر','rightFa','پاسخ به تشکر'))) WHERE activity_key='act-de-danke-bitte-role-match';
UPDATE activities SET instruction_fa='هر عبارت را به کاربردش وصل کن.', selection_reason='چهار عبارت منبع‌دارِ همین درس را جداگانه تطبیق می‌دهد تا عذرخواهی، پاسخ به عذرخواهی، تشکر و پاسخ به تشکر با چهار گزینهٔ روشن از هم تفکیک شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Entschuldigung.','leftFa','ببخشید.','right','عذرخواهی','rightFa','عذرخواهی'),JSON_OBJECT('left','Kein Problem.','leftFa','مشکلی نیست.','right','پاسخ به عذرخواهی','rightFa','پاسخ به عذرخواهی'),JSON_OBJECT('left','Danke!','leftFa','ممنون!','right','تشکر','rightFa','تشکر'),JSON_OBJECT('left','Bitte!','leftFa','خواهش می‌کنم!','right','پاسخ به تشکر','rightFa','پاسخ به تشکر'))) WHERE activity_key='act-de-entschuldigung-matching';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت دقیق منبع را جداگانه تطبیق می‌دهد تا پرسش و پاسخِ محل زندگی و مبدأ با چهار گزینهٔ مستقل از هم تشخیص داده شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Wo wohnen Sie?','leftFa','کجا زندگی می‌کنید؟','right','پرسش دربارهٔ محل زندگی','rightFa','پرسش دربارهٔ محل زندگی'),JSON_OBJECT('left','Ich wohne in Österreich.','leftFa','من در اتریش زندگی می‌کنم.','right','پاسخ دربارهٔ محل زندگی','rightFa','پاسخ دربارهٔ محل زندگی'),JSON_OBJECT('left','Woher kommen Sie?','leftFa','اهل کجا هستید؟','right','پرسش دربارهٔ مبدأ','rightFa','پرسش دربارهٔ مبدأ'),JSON_OBJECT('left','Ich komme aus Deutschland, und Sie?','leftFa','من اهل آلمان هستم، شما چطور؟','right','پاسخ دربارهٔ مبدأ','rightFa','پاسخ دربارهٔ مبدأ'))) WHERE activity_key='act-de-residence-matching';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت منبع‌دارِ مرور را جداگانه تطبیق می‌دهد تا پرسش و پاسخ سن و محل زندگی با چهار گزینهٔ مستقل بازیابی شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Wo wohnen Sie?','leftFa','کجا زندگی می‌کنید؟','right','پرسش دربارهٔ محل زندگی','rightFa','پرسش دربارهٔ محل زندگی'),JSON_OBJECT('left','Ich wohne in Österreich.','leftFa','من در اتریش زندگی می‌کنم.','right','پاسخ دربارهٔ محل زندگی','rightFa','پاسخ دربارهٔ محل زندگی'),JSON_OBJECT('left','Wie alt bist du?','leftFa','چند سالته؟','right','پرسش دربارهٔ سن','rightFa','پرسش دربارهٔ سن'),JSON_OBJECT('left','Ich bin 20 Jahre alt.','leftFa','من ۲۰ ساله هستم.','right','پاسخ دربارهٔ سن','rightFa','پاسخ دربارهٔ سن'))) WHERE activity_key='act-de-personal-review-match';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت منبع‌دار روز و ساعت را جداگانه تطبیق می‌دهد تا پرسش و پاسخ هر دسته با چهار گزینهٔ مستقل از هم تشخیص داده شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Welcher Tag ist heute?','leftFa','امروز چه روزی است؟','right','پرسش دربارهٔ روز','rightFa','پرسش دربارهٔ روز'),JSON_OBJECT('left','Heute ist Dienstag.','leftFa','امروز سه‌شنبه است.','right','پاسخ دربارهٔ روز','rightFa','پاسخ دربارهٔ روز'),JSON_OBJECT('left','Wie spät ist es?','leftFa','ساعت چنده؟','right','پرسش دربارهٔ ساعت','rightFa','پرسش دربارهٔ ساعت'),JSON_OBJECT('left','Es ist 6.30 Uhr.','leftFa','ساعت ۶:۳۰ است.','right','پاسخ دربارهٔ ساعت','rightFa','پاسخ دربارهٔ ساعت'))) WHERE activity_key='act-de-time-question-match';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت دقیق منبع را جداگانه تطبیق می‌دهد تا پرسش و پاسخ دربارهٔ غذای موجود و چیزی که فرد می‌خورد با چهار گزینهٔ مستقل تمرین شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Was gibt es heute?','leftFa','امروز چی داریم؟','right','پرسش دربارهٔ غذای امروز','rightFa','پرسش دربارهٔ غذای امروز'),JSON_OBJECT('left','Heute gibt es Suppe.','leftFa','امروز سوپ داریم.','right','پاسخ دربارهٔ غذای موجود','rightFa','پاسخ دربارهٔ غذای موجود'),JSON_OBJECT('left','Was essen Sie?','leftFa','شما چی می‌خورید؟','right','پرسش دربارهٔ چیزی که می‌خورید','rightFa','پرسش دربارهٔ چیزی که می‌خورید'),JSON_OBJECT('left','Ich esse Reis.','leftFa','من برنج می‌خورم.','right','پاسخ دربارهٔ خوردن','rightFa','پاسخ دربارهٔ خوردن'))) WHERE activity_key='act-de-food-today-matching';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت دقیق منبع را جداگانه تطبیق می‌دهد تا پرسش و پاسخِ نیاز و خرید با چهار گزینهٔ مستقل از هم متمایز شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Was brauchen Sie?','leftFa','چه چیزی لازم دارید؟','right','پرسش دربارهٔ نیاز','rightFa','پرسش دربارهٔ نیاز'),JSON_OBJECT('left','Ich brauche eine Hose.','leftFa','من یک شلوار لازم دارم.','right','پاسخ دربارهٔ نیاز','rightFa','پاسخ دربارهٔ نیاز'),JSON_OBJECT('left','Und was kaufen Sie?','leftFa','و چه چیزی می‌خرید؟','right','پرسش دربارهٔ خرید','rightFa','پرسش دربارهٔ خرید'),JSON_OBJECT('left','Ich kaufe ein Hemd und ein Paar Schuhe.','leftFa','من یک پیراهن و یک جفت کفش می‌خرم.','right','پاسخ دربارهٔ خرید','rightFa','پاسخ دربارهٔ خرید'))) WHERE activity_key='act-de-need-buy-matching';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت منبع‌دار قیمت را جداگانه تطبیق می‌دهد تا دو شکل پرسش و دو پاسخ عددی با چهار گزینهٔ مستقل خوانده و تشخیص داده شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Wie viel kostet das?','leftFa','این چقدر قیمت دارد؟','right','پرسش قیمت','rightFa','پرسش قیمت'),JSON_OBJECT('left','Das kostet 70 Euro und 92 Cent.','leftFa','این ۷۰ یورو و ۹۲ سنت قیمت دارد.','right','پاسخ قیمت ۷۰ یورو و ۹۲ سنت','rightFa','پاسخ قیمت ۷۰ یورو و ۹۲ سنت'),JSON_OBJECT('left','Was kostet das?','leftFa','قیمت این چقدره؟','right','شکل کوتاه‌تر پرسش قیمت','rightFa','شکل کوتاه‌تر پرسش قیمت'),JSON_OBJECT('left','Das kostet 35 Euro und 15 Cent.','leftFa','این ۳۵ یورو و ۱۵ سنت قیمت دارد.','right','پاسخ قیمت ۳۵ یورو و ۱۵ سنت','rightFa','پاسخ قیمت ۳۵ یورو و ۱۵ سنت'))) WHERE activity_key='act-de-price-match';
UPDATE activities SET instruction_fa='هر عبارت را به نقش درستش وصل کن.', selection_reason='چهار عبارت منبع‌دار گفت‌وگو را جداگانه تطبیق می‌دهد تا شروع مؤدبانه، پاسخ آن، پرسش مکان و پاسخ «نمی‌دانم» با چهار گزینهٔ مستقل تمرین شوند.', payload=JSON_SET(payload,'$.pairMode','target_to_persian','$.pairs',JSON_ARRAY(JSON_OBJECT('left','Entschuldigung!','leftFa','ببخشید!','right','شروع مؤدبانه','rightFa','شروع مؤدبانه'),JSON_OBJECT('left','Bitte?','leftFa','بفرمایید؟','right','پاسخ به شروع مؤدبانه','rightFa','پاسخ به شروع مؤدبانه'),JSON_OBJECT('left','Wo ist die Toilette?','leftFa','سرویس بهداشتی کجاست؟','right','پرسش دربارهٔ مکان','rightFa','پرسش دربارهٔ مکان'),JSON_OBJECT('left','Ich weiß nicht.','leftFa','نمی‌دانم.','right','پاسخ «نمی‌دانم»','rightFa','پاسخ «نمی‌دانم»'))) WHERE activity_key='act-de-toilet-exchange-match';
UPDATE lessons SET status='final' WHERE language_level_id=@prea1 AND lesson_key IN ('de-pre-a1-lesson-hallo','de-pre-a1-lesson-danke-bitte','de-pre-a1-lesson-entschuldigung','de-pre-a1-lesson-residence-origin','de-pre-a1-lesson-personal-review','de-pre-a1-lesson-day-time','de-pre-a1-lesson-food-today','de-pre-a1-lesson-need-and-buy','de-pre-a1-lesson-ask-price','de-pre-a1-lesson-find-toilet');
COMMIT;
